### PR TITLE
Update firmware to swedish

### PR DESCRIPTION
**Pull request by Painkiller56**
Update firmware to swedish

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@Painkiller56 Thank you very much for the updated translation.

But we need the translation of https://github.com/prusa3d/Prusa-Firmware/blob/MK3/lang/po/Firmware_sv.po from the MK3 branch including the new MMU2S messages first.

After the merge I will make a cherry-pick PR for the MK3_3.12 branch (without new MMU2S messages).

Example PRs:
- main PR https://github.com/prusa3d/Prusa-Firmware/pull/3626
- cherry-pick https://github.com/prusa3d/Prusa-Firmware/pull/3662

**Comment by Painkiller56** [comment]
No msgid in po file;

528 #. MSG_DESC_FINDA_DIDNT_GO_OFF c=20 r=8

557 #. MSG_TITLE_FSENSOR_TOO_EARLY c=20

1592 #. MSG_DESC_INVALID_TOOL c=20 r=8

 

The translation is showed as msgid.

 

Sincerely,

 

Bernt

 

 

Från: 3d-gussner ***@***.***> 
Skickat: den 10 oktober 2022 09:56
Till: prusa3d/Prusa-Firmware ***@***.***>
Kopia: Bernt Ahblbäck ***@***.***>; Mention ***@***.***>
Ämne: Re: [prusa3d/Prusa-Firmware] Update firmware to swedish (PR #3669)

 

@Painkiller56 <https://github.com/Painkiller56>  Thank you very much for the updated translation.

But we need the translation of https://github.com/prusa3d/Prusa-Firmware/blob/MK3/lang/po/Firmware_sv.po from the MK3 branch including the new MMU2S messages first.

After the merge I will make a cherry-pick PR for the MK3_3.12 branch (without new MMU2S messages).

Example PRs:

*	main PR #3626 <https://github.com/prusa3d/Prusa-Firmware/pull/3626> 
*	cherry-pick #3662 <https://github.com/prusa3d/Prusa-Firmware/pull/3662>

**Comment by 3d-gussner** [comment]
@Painkiller56 Please contact me via email.

**Comment by Painkiller56** [comment]
Hi,

 

I am home now and available for the rest of the evening, so what is it ?

 

Sincelely,

Bernt

 

 

Från: 3d-gussner ***@***.***> 
Skickat: den 17 oktober 2022 15:02
Till: prusa3d/Prusa-Firmware ***@***.***>
Kopia: Bernt Ahblbäck ***@***.***>; Mention ***@***.***>
Ämne: Re: [prusa3d/Prusa-Firmware] Update firmware to swedish (PR #3669)

 

@Painkiller56 <https://github.com/Painkiller56>  Please contact me via email.

**Comment by 3d-gussner** [comment]
Closing it as it has another PR based on this has been merged.

**Pull request closed without merging**
