### PR TITLE
Remove sm4 line xyze UI

### PR DESCRIPTION
**Pull request by gudnimg**
Cleaning up my fork and found this branch. Changing the file from `.c` to `.cpp` was not building correctly in the Travis build, I never found out why but I suspect it was cache related. Now that we're using CMake it should run fine...

Creating this PR to check if CI passes

### CODE REVIEW

**Comment by gudnimg** [comment]
Nice these changes now pass Github CI :) I guess we can review it then.

**Review by leptun — APPROVED** [review]
looks good 👍

**Comment by sarusani** [comment]
👍 Builds work as expected in VSCode (CMake) windows.

**Review by 3d-gussner — APPROVED** [review]
Works

**Pull request merged**
