### PR TITLE
MK3: Add translations for `Clear TM error` message

### PR DESCRIPTION
**Pull request by 3d-gussner**
Please check if the translations are okay? This menu/message allows to acknowledge or clear a temp model error to "unlock" the printer.
Please vote with
:+1: if okay
:-1:  if needs to be changed  with a comment what is correct.
 
@Hauzman @AttilaSVK @Prime1910 @ingbrzy @shatter136 @Painkiller56 @OS-kar

- [x] Create Cherry-pick PR to MK3_3.12 branch

### CODE REVIEW

**Comment by Hauzman** [comment]
@3d-gussner the Romanian translation is good 👍

**Comment by 3d-gussner** [comment]
> @3d-gussner the Romanian translation is good +1

@Hauzman :1st_place_medal: You are so fast

**Review by ingbrzy — APPROVED** [review]
SK is OK

**Review by leptun — APPROVED** [review]

**Comment by Painkiller56** [comment]
Swedeish is OK.

**Comment by Prime1910** [comment]
Croatian is good👍🏻

**Comment by AttilaSVK** [comment]
👎 In Hungarian the correct text should be: HM hiba törlése
(HM stands for hőmérsékleti modell - that's what I've used elsewhere as
well)

3d-gussner ***@***.***> ezt írta (időpont: 2022. dec. 20., K,
15:31):

**Pull request merged**
