### PR TITLE
Full Graphics Display

### PR DESCRIPTION
**Pull request by tonysmartantzoulatos**
Can i please have some help in what i might be missing in order to make it work with a Full Graphics Display? I am using Ramps board and not MKS.
 I got the following message:
Arduino: 1.8.5 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\dogm_lcd_implementation.h:38:0,

                 from sketch\ultralcd.cpp:143:

sketch\dogm_font_data_marlin.h:12:25: fatal error: utility/u8g.h: No such file or directory

 #include <utility/u8g.h>

                         ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

### CODE REVIEW

**Comment by 3d-gussner** [comment]
You should open a Issue and not a Pull Request

**Comment by 3d-gussner** [comment]
1st google search 
result may help https://forum.arduino.cc/index.php?topic=387710.0
https://www.thingiverse.com/groups/prusa-i3/forums/general/topic:6126

**Comment by tonysmartantzoulatos** [comment]
apologies...newbie on Github. wont happen again. Merry Christmas and thank you for your assistance

**Comment by tonysmartantzoulatos** [comment]
Arduino: 1.6.8 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\dogm_lcd_implementation.h:40:0,

                 from sketch\ultralcd.cpp:143:

sketch\ultralcd_st7920_u8glib_rrd.h: In function 'uint8_t u8g_dev_rrd_st7920_128x64_fn(u8g_t*, u8g_dev_t*, uint8_t, void*)':

sketch\ultralcd_st7920_u8glib_rrd.h:40:95: warning: large integer implicitly truncated to unsigned type [-Woverflow]

 #define ST7920_WRITE_BYTE(a)     {ST7920_SWSPI_SND_8BIT((a)&0xf0);ST7920_SWSPI_SND_8BIT((a)<<4);u8g_10MicroDelay();}

                                                                                               ^

sketch\ultralcd_st7920_u8glib_rrd.h:63:9: note: in expansion of macro 'ST7920_WRITE_BYTE'

         ST7920_WRITE_BYTE(0x3E);       //extended mode + GDRAM active

         ^

sketch\ultralcd_st7920_u8glib_rrd.h:40:95: warning: large integer implicitly truncated to unsigned type [-Woverflow]

 #define ST7920_WRITE_BYTE(a)     {ST7920_SWSPI_SND_8BIT((a)&0xf0);ST7920_SWSPI_SND_8BIT((a)<<4);u8g_10MicroDelay();}

                                                                                               ^

sketch\ultralcd_st7920_u8glib_rrd.h:67:11: note: in expansion of macro 'ST7920_WRITE_BYTE'

           ST7920_WRITE_BYTE(0x80);     //set x = 0

           ^

sketch\ultralcd_st7920_u8glib_rrd.h:40:95: warning: large integer implicitly truncated to unsigned type [-Woverflow]

 #define ST7920_WRITE_BYTE(a)     {ST7920_SWSPI_SND_8BIT((a)&0xf0);ST7920_SWSPI_SND_8BIT((a)<<4);u8g_10MicroDelay();}

                                                                                               ^

sketch\ultralcd_st7920_u8glib_rrd.h:94:13: note: in expansion of macro 'ST7920_WRITE_BYTE'

             ST7920_WRITE_BYTE(0x80);           //x=0

             ^

sketch\ultralcd_st7920_u8glib_rrd.h:40:95: warning: large integer implicitly truncated to unsigned type [-Woverflow]

 #define ST7920_WRITE_BYTE(a)     {ST7920_SWSPI_SND_8BIT((a)&0xf0);ST7920_SWSPI_SND_8BIT((a)<<4);u8g_10MicroDelay();}

                                                                                               ^

sketch\ultralcd_st7920_u8glib_rrd.h:99:13: note: in expansion of macro 'ST7920_WRITE_BYTE'

             ST7920_WRITE_BYTE(0x80 | 8);       //x=64

             ^

In file included from sketch\ultralcd.cpp:143:0:

sketch\dogm_lcd_implementation.h: In function 'void lcd_implementation_clear()':

dogm_lcd_implementation.h:143: error: 'void lcd_implementation_clear()' was declared 'extern' and later 'static' [-fpermissive]

 static void lcd_implementation_clear()

                                      ^

In file included from sketch\ultralcd.cpp:2:0:

ultralcd.h:190: error: previous declaration of 'void lcd_implementation_clear()' [-fpermissive]

 extern void lcd_implementation_clear();

             ^

In file included from sketch\ultralcd.cpp:143:0:

sketch\dogm_lcd_implementation.h: In function 'void lcd_printPGM(const char*)':

dogm_lcd_implementation.h:158: error: 'void lcd_printPGM(const char*)' was declared 'extern' and later 'static' [-fpermissive]

 static void lcd_printPGM(const char* str)

                                         ^

In file included from sketch\ultralcd.cpp:2:0:

ultralcd.h:191: error: previous declaration of 'void lcd_printPGM(const char*)' [-fpermissive]

 extern void lcd_printPGM(const char* str);

             ^

sketch\ultralcd.cpp: In function 'void lcd_status_screen()':

ultralcd.cpp:431: error: 'lcd_implementation_init_noclear' was not declared in this scope

         );

         ^

sketch\ultralcd.cpp: In function 'void lcd_support_menu()':

ultralcd.cpp:283: error: 'lcd_implementation_drawmenu_back_RAM_selected' was not declared in this scope

           lcd_implementation_drawmenu_ ## type ## _selected (_drawLineNr, _label_pstr , ## args ); \

                                                                                                 ^

sketch\ultralcd.cpp:1492:7: note: in expansion of macro 'MENU_ITEM'

       MENU_ITEM(back_RAM, menuData.supportMenu.ip_str, lcd_main_menu);

       ^

ultralcd.cpp:285: error: 'lcd_implementation_drawmenu_back_RAM' was not declared in this scope

           lcd_implementation_drawmenu_ ## type (_drawLineNr, _label_pstr , ## args ); \

                                                                                    ^

sketch\ultralcd.cpp:1492:7: note: in expansion of macro 'MENU_ITEM'

       MENU_ITEM(back_RAM, menuData.supportMenu.ip_str, lcd_main_menu);

       ^

sketch\ultralcd.cpp: In function 'void lcd_unLoadFilament()':

ultralcd.cpp:1511: error: 'lcd' was not declared in this scope

     lcd.setCursor(0, 0);

     ^

sketch\ultralcd.cpp: In function 'void lcd_change_filament()':

ultralcd.cpp:1527: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 1);

   ^

sketch\ultralcd.cpp: In function 'void lcd_wait_interact()':

ultralcd.cpp:1539: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 1);

   ^

sketch\ultralcd.cpp: In function 'void lcd_change_success()':

ultralcd.cpp:1555: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 2);

   ^

sketch\ultralcd.cpp: In function 'void lcd_loading_color()':

ultralcd.cpp:1567: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_loading_filament()':

ultralcd.cpp:1596: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_alright()':

ultralcd.cpp:1634: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_LoadFilament()':

ultralcd.cpp:1728: error: 'lcd' was not declared in this scope

     lcd.setCursor(0, 0);

     ^

sketch\ultralcd.cpp: In function 'void lcd_menu_statistics()':

ultralcd.cpp:1752: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

ultralcd.cpp:1796: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_move_e()':

ultralcd.cpp:1893: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_service_mode_show_result()':

ultralcd.cpp:1905: error: 'lcd_set_custom_characters_degree' was not declared in this scope

  lcd_set_custom_characters_degree();

                                   ^

ultralcd.cpp:1918: error: 'lcd' was not declared in this scope

    lcd.print(distance_from_min[i]);

    ^

ultralcd.cpp:1933: error: 'lcd' was not declared in this scope

   lcd.setCursor(15, 0);

   ^

ultralcd.cpp:1940: error: 'lcd' was not declared in this scope

  lcd.print(bed_skew_angle_mild * 180 / M_PI);

  ^

ultralcd.cpp:1952: error: 'lcd_set_custom_characters_arrows' was not declared in this scope

  lcd_set_custom_characters_arrows();

                                   ^

sketch\ultralcd.cpp: In function 'void _lcd_babystep(int, const char*)':

ultralcd.cpp:2035: error: 'lcd_implementation_drawedit_2' was not declared in this scope

     lcd_implementation_drawedit_2(msg, ftostr13ns(menuData.babyStep.babystepMemMM[axis]));

                                                                                         ^

sketch\ultralcd.cpp: In function 'void pid_extruder()':

ultralcd.cpp:2135: error: 'lcd' was not declared in this scope

  lcd.setCursor(1, 0);

  ^

sketch\ultralcd.cpp: In function 'void lcd_adjust_z()':

ultralcd.cpp:2160: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_wait_for_cool_down()':

ultralcd.cpp:2236: error: 'lcd_set_custom_characters_degree' was not declared in this scope

  lcd_set_custom_characters_degree();

                                   ^

ultralcd.cpp:2240: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 4);

   ^

ultralcd.cpp:2251: error: 'lcd_set_custom_characters' was not declared in this scope

   lcd_set_custom_characters();

                             ^

ultralcd.cpp:2254: error: 'lcd_set_custom_characters_arrows' was not declared in this scope

  lcd_set_custom_characters_arrows();

                                   ^

sketch\ultralcd.cpp: In function 'const char* lcd_display_message_fullscreen_P(const char*, uint8_t&)':

ultralcd.cpp:2364: error: 'lcd' was not declared in this scope

     lcd.setCursor(0, 0);

     ^

ultralcd.cpp:2406: error: 'lcd_set_custom_characters_nextpage' was not declared in this scope

   lcd_set_custom_characters_nextpage();

                                      ^

sketch\ultralcd.cpp: In function 'void lcd_show_fullscreen_message_and_wait_P(const char*)':

ultralcd.cpp:2421: error: 'lcd_set_custom_characters_nextpage' was not declared in this scope

  lcd_set_custom_characters_nextpage();

                                     ^

ultralcd.cpp:2426: error: 'lcd' was not declared in this scope

    lcd.setCursor(19, 3);

    ^

ultralcd.cpp:2437: error: 'lcd_set_custom_characters' was not declared in this scope

     lcd_set_custom_characters();

                               ^

ultralcd.cpp:2450: error: 'lcd' was not declared in this scope

     lcd.setCursor(19, 3);

     ^

sketch\ultralcd.cpp: In function 'int8_t lcd_show_multiscreen_message_yes_no_and_wait_P(const char*, bool, bool)':

ultralcd.cpp:2494: error: 'lcd' was not declared in this scope

      lcd.setCursor(0, 3);

      ^

ultralcd.cpp:2519: error: 'lcd_set_custom_characters' was not declared in this scope

      lcd_set_custom_characters();

                                ^

ultralcd.cpp:2532: error: 'lcd' was not declared in this scope

    lcd.setCursor(0, 3);

    ^

sketch\ultralcd.cpp: In function 'int8_t lcd_show_fullscreen_message_yes_no_and_wait_P(const char*, bool, bool)':

ultralcd.cpp:2549: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 2);

   ^

ultralcd.cpp:2556: error: 'lcd' was not declared in this scope

   lcd.setCursor(1, 2);

   ^

ultralcd.cpp:2574: error: 'lcd' was not declared in this scope

    lcd.setCursor(0, 2);

    ^

sketch\ultralcd.cpp: In function 'void lcd_show_end_stops()':

ultralcd.cpp:2652: error: 'lcd' was not declared in this scope

     lcd.setCursor(0, 0);

     ^

In file included from sketch\temperature.h:24:0,

                 from sketch\ultralcd.cpp:1:

sketch\ultralcd.cpp: In function 'void prusa_stat_printinfo()':

ultralcd.cpp:2888: error: 'longFilenameOLD' was not declared in this scope

  SERIAL_ECHO(longFilenameOLD);

              ^

sketch\Marlin.h:65:44: note: in definition of macro 'SERIAL_PROTOCOL'

 #define SERIAL_PROTOCOL(x) (MYSERIAL.print(x))

                                            ^

sketch\ultralcd.cpp:2888:2: note: in expansion of macro 'SERIAL_ECHO'

  SERIAL_ECHO(longFilenameOLD);

  ^

sketch\ultralcd.cpp: In function 'void lcd_pick_babystep()':

ultralcd.cpp:2914: error: 'lcd' was not declared in this scope

     lcd.setCursor(0, 0);

     ^

sketch\ultralcd.cpp: In function 'void lcd_set_degree()':

ultralcd.cpp:3095: error: 'lcd_set_custom_characters_degree' was not declared in this scope

  lcd_set_custom_characters_degree();

                                   ^

sketch\ultralcd.cpp: In function 'void lcd_set_progress()':

ultralcd.cpp:3099: error: 'lcd_set_custom_characters_progress' was not declared in this scope

  lcd_set_custom_characters_progress();

                                     ^

sketch\ultralcd.cpp: In function 'void lcd_language_menu()':

ultralcd.cpp:283: error: 'lcd_implementation_drawmenu_setlang_selected' was not declared in this scope

           lcd_implementation_drawmenu_ ## type ## _selected (_drawLineNr, _label_pstr , ## args ); \

                                                                                                 ^

sketch\ultralcd.cpp:3116:5: note: in expansion of macro 'MENU_ITEM'

     MENU_ITEM(setlang, MSG_LANGUAGE_NAME_EXPLICIT(i), i);

     ^

ultralcd.cpp:285: error: 'lcd_implementation_drawmenu_setlang' was not declared in this scope

           lcd_implementation_drawmenu_ ## type (_drawLineNr, _label_pstr , ## args ); \

                                                                                    ^

sketch\ultralcd.cpp:3116:5: note: in expansion of macro 'MENU_ITEM'

     MENU_ITEM(setlang, MSG_LANGUAGE_NAME_EXPLICIT(i), i);

     ^

sketch\ultralcd.cpp: In function 'void lcd_wizard(int)':

ultralcd.cpp:3374: error: 'lcd' was not declared in this scope

     lcd.setCursor(0, 4);

     ^

ultralcd.cpp:3380: error: 'lcd_set_custom_characters' was not declared in this scope

     lcd_set_custom_characters();

                               ^

sketch\ultralcd.cpp: In function 'void lcd_mylang_drawmenu(int)':

ultralcd.cpp:3578: error: 'lcd' was not declared in this scope

   lcd.setCursor(0, 0);

   ^

sketch\ultralcd.cpp: In function 'void lcd_mylang_drawcursor(int)':

ultralcd.cpp:3622: error: 'lcd' was not declared in this scope

   if (cursor==1) lcd.setCursor(0, 1);

                  ^

ultralcd.cpp:3623: error: 'lcd' was not declared in this scope

   if (cursor>1 && cursor<LANG_NUM) lcd.setCursor(0, 2);

                                    ^

ultralcd.cpp:3624: error: 'lcd' was not declared in this scope

   if (cursor==LANG_NUM) lcd.setCursor(0, 3);

                         ^

ultralcd.cpp:3626: error: 'lcd' was not declared in this scope

   lcd.print(">");

   ^

sketch\ultralcd.cpp: In function 'void lcd_mylang()':

ultralcd.cpp:3635: error: 'lcd_set_custom_characters_arrows' was not declared in this scope

   lcd_set_custom_characters_arrows();

                                    ^

ultralcd.cpp:3688: error: 'lcd_set_custom_characters_degree' was not declared in this scope

   lcd_set_custom_characters_degree();

                                    ^

sketch\ultralcd.cpp: In function 'void bowden_menu()':

ultralcd.cpp:3698: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'char snmm_stop_print_menu()':

ultralcd.cpp:3814: error: 'lcd' was not declared in this scope

  lcd_print_at_PGM(0,0,MSG_UNLOAD_FILAMENT); lcd.print(":");

                                             ^

sketch\ultralcd.cpp: In function 'char choose_extruder_menu()':

ultralcd.cpp:3866: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 1);

  ^

sketch\ultralcd.cpp: In function 'char reset_menu()':

ultralcd.cpp:3966: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'void lcd_farm_no()':

ultralcd.cpp:4392: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'unsigned char lcd_choose_color()':

ultralcd.cpp:4467: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 1);

  ^

sketch\ultralcd.cpp: In function 'void lcd_confirm_print()':

ultralcd.cpp:4546: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'void lcd_sdcard_stop()':

ultralcd.cpp:4879: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'bool lcd_selftest()':

ultralcd.cpp:5142: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0); lcd_printPGM(MSG_SELFTEST_START);

  ^

sketch\ultralcd.cpp: In function 'void lcd_selftest_error(int, const char*, const char*)':

ultralcd.cpp:5502: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'bool lcd_selftest_fan_dialog(int)':

ultralcd.cpp:5593: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0); lcd_printPGM(MSG_SELFTEST_FAN);

  ^

sketch\ultralcd.cpp: In function 'int lcd_selftest_screen(int, int, int, bool, int)':

ultralcd.cpp:5688: error: 'lcd' was not declared in this scope

  lcd.setCursor(0, 0);

  ^

sketch\ultralcd.cpp: In function 'void lcd_selftest_screen_step(int, int, int, const char*, const char*)':

ultralcd.cpp:5728: error: 'lcd' was not declared in this scope

  lcd.setCursor(_col, _row);

  ^

sketch\ultralcd.cpp: In function 'void lcd_update_enable(bool)':

ultralcd.cpp:5917: error: 'lcd_set_custom_characters_degree' was not declared in this scope

                 lcd_set_custom_characters_degree();

                                                  ^

ultralcd.cpp:5919: error: 'lcd_set_custom_characters_arrows' was not declared in this scope

                 lcd_set_custom_characters_arrows();

                                                  ^

sketch\ultralcd.cpp: In function 'void lcd_connect_printer()':

ultralcd.cpp:6072: error: 'lcd_set_custom_characters_progress' was not declared in this scope

  lcd_set_custom_characters_progress();

                                     ^

ultralcd.cpp:6094: error: 'lcd_set_custom_characters_degree' was not declared in this scope

  lcd_set_custom_characters_degree();

                                   ^

exit status 1
'void lcd_implementation_clear()' was declared 'extern' and later 'static' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by thess** [comment]
@PavelSindler - this is not a PR but a request for support. Please close this.

**Pull request closed without merging**
