### PR TITLE
French language for Prusa i3

### PR DESCRIPTION
**Pull request by kuisac**
The french facebook group https://www.facebook.com/groups/prusai3mk2s propose to add French language for the prusa i3 menu

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@kuisac Did you compile and test the additional language firmware? If so how did you do it, as we are still waiting for a proper how-to compile languages from Prusa development team.
I would like to add Dutch and Portuguese as well and modify few things like Hyperfine Bed Leveling to MK2.5 an MK3.

**Comment by kuisac** [comment]
3d-gussner, no I can't test it now. I will receive my prusa i3 mk3 next week. I just read all code with language parameters and I add the French language. It's not very difficult. 
For the compilation you have all informations on this page : https://github.com/prusa3d/Prusa-Firmware
Dutch language exist on this firmware.

**Comment by 3d-gussner** [comment]
Guess it will be done by https://github.com/prusa3d/Prusa-Firmware/pull/1127

**Comment by 3d-gussner** [comment]
@kuisac I think you can close that one

**Comment by 3d-gussner** [comment]
@kuisac It has been implemented. Can you please close the PR?

**Pull request closed without merging**
