### PR TITLE
Merge duplicate strings in cmdqueue.cpp

### PR DESCRIPTION
**Pull request by DRracer**
Original idea from @GilesBathgate, PR #3322 . This is just a rework on top of current MK3 branch. And, we don't want to have these strings translated...

### CODE REVIEW

**Comment by GilesBathgate** [comment]
@DRracer I don't know much about your compile toolchain, but does the compiler support LTO? (`-flto` in clang). It should optimise for smaller size code in conjunction with the optimise for size compiler flag `-Os`

**Comment by leptun** [comment]
@GilesBathgate We already have LTO enabled. Without LTO the build would exceed the available flash.

**Comment by DRracer** [comment]
@GilesBathgate yes, we are using LTO ... last time I checked, without LTO the firmware exceeds the CPU Flash size by ~50KB :wink: 

And currently we are using avr-gcc-7.3.x which is pretty recent (C++14 and a much more reliable LTO phase than gcc 4.9 which has been used before)

**Comment by GilesBathgate** [comment]
@DRracer There might be some more of these duplicate strings, I tried:

`grep "\".*\"" * -Roh | sort | uniq -d | awk '{ print length, $0 }' | sort -n | cut -d" " -f2-`
Which currently yields: https://gist.github.com/GilesBathgate/58fb9c6182b2856fd728e2d4a29fc051

Although I suspect there are mostly false positives.

**Comment by DRracer** [comment]
@GilesBathgate good point, I looked up a few of them and at least this one: `lcd_puts_at_P(0,3,_n("1/4"));` occurs twice in the source code and also twice in the binary.

@gudnimg a good idea for optimization :wink:

**Comment by GilesBathgate** [comment]
@DRracer Yes cross-referencing them with the ones in the binary using the `strings` command could be a good linting approach ;)

**Comment by GilesBathgate** [comment]
@DRracer Yes cross-referencing them with the ones in the binary using the `strings` command could be a good linting approach ;) Its odd that something like -Os or -flto doesn't remove them :shrug:

**Comment by DRracer** [comment]
-Os and -flto works fine as long as you don't play with multiple sections (which is what we need for the translations). Then the automatic merging of strings at link time stops working.

**Review by leptun — APPROVED** [review]
looks good to me

**Pull request merged**
