### PR TITLE
wizard: Do no set "Self test OK" as an alert message (3.12)

### PR DESCRIPTION
**Pull request by wavexx**
Backport of #3920 for 3.12

### CODE REVIEW

**Comment by 3d-gussner** [comment]
See https://github.com/prusa3d/Prusa-Firmware/pull/3920#issuecomment-1383590585

**Review by 3d-gussner — APPROVED** [review]
Tested on MK404 and real hardware

**Review by DRracer — COMMENTED** [review]
Looks correct to be, but :thinking: I'm afraid what else does this change break

**Comment by wavexx** [comment]
AFAIK we don't have many possible workflows here. Only two paths looking at calls to lcd_selftest()

- manual run via menu:
  * this now matches existing behavior (essentially just exit to status)
- run during the wizard:
  * if all is ok, "self test ok" is not even shown
  * if the next step of the wizard fails, I expect the _new_ failure to be shown, not the "self test ok" message

**Pull request merged**
