### PR TITLE
Fixed typos in language_en.h from lenght to length...

### PR DESCRIPTION
**Pull request by 3d-gussner**
updated some long MSGs (length=xx, lines=yy) in the 'language_en.h' file to get less errors running 'perl langtool.pl'.
To make the translation easier, i tried to keep the lines and tabs between 'language_en.h' and 'language_de.h' file identical.
Removed unused (length=xx, lines=yy) from the 'language_de.h' file; langtool.pl just uses these from the english language 'language_en.h' file.

There are still some error results from langtool.pl i didn't want to change. @PavelSindler can you please check these?
Key MSG_FAN_SPEED, language es, line length: 15, max length: 14
        Velocidad Vent.
Key MSG_KILLED, language es, line length: 20, max length: 17
        PARADA DE EMERGENCIA
Key MSG_NOT_COLOR, language es, line length: 18, max length: 17
        Color no homogeneo
Key MSG_PICK_Z, language es, line length: 20, max length: 17
        Esc. Modelo Adecuado
Key MSG_RESUMING, language es, line length: 20, max length: 17
        Resumiendo impresion
Key MSG_SELFTEST_FAN_NO, language es, line length: 18, max length: 17
        Ventilador no gira
Key MSG_TAKE_EFFECT, language es, line length: 21, max length: 20
         para aplicar cambios
Language: pl
Language: de
Key MSG_ADJUSTZ, language de, line length: 18, max length: 17
        Auto Z einstellen?
Key MSG_DWELL, language de, line length: 19, max length: 17
        Einen Moment bitte.
Key MSG_SELFTEST_NOTCONNECTED, language de, line length: 19, max length: 17
        Nicht angeschlossen

### CODE REVIEW

**Comment by PavelSindler** [comment]
Thank you for this PR. I will check it and merge when I will have more time as there are now tasks with higher priority. There are sometimes messages which are longer than max. length in one particular language and it is ok, when I check it (for example something is shown on screen in more steps then prefered in case of multi screen message). But it can be the best way how to do it. I don't prefer to relax limits too much.

**Comment by 3d-gussner** [comment]
@PavelSindler I can understand that you are quite busy. Do you think that i should try to update the German translation? There are few thing could be improved and it would be great to get them before the final version.

BTW: Before 3.1.0-RC1 I was able to compile an additional language (Dutch) but now it compiles without any issues but on the miniRAMbo got strange results. You wrote a while ago that adding more languages could hit the Atmega limits. I guess i hit the limits now. I decided to limit to 5/6 languages and release different hex files on my github.

**Comment by PavelSindler** [comment]
Correcting german translations in separate PR would be great.
Please keep max. length of messages and don't do many changes. Lets fix the most important things now, don't do unnecessary changes and we can then improve it furthermore in the future.

**Comment by 3d-gussner** [comment]
@PavelSindler I will try to keep the limits under (length<=20) but modify (length=20, lines>2) to get less errors while using langtool.pl.

**Comment by PavelSindler** [comment]
Don't modify lengths and lines to higher values than currently used unless you check it on LCD and make sure, that this limit is set wrongly and can be relaxed.

**Comment by 3d-gussner** [comment]
@PavelSindler Now i just adjust longer messages (length=20, lines=2+) to get rid of langtool.pl errors.
These are working fine in the LCD, and most of them are Wizzard or Calibration messages.

My length changes in the past worked just fine:
- MSG_FAN_SPEED with (length=15) fits under Settings->Temperature and Tune menu and can still show 0-255 values behind
- MSG_KILLED with (length=20) has no other characters/values before or behind
- MSG_NOT_COLOR with (length=18) has no other characters/values before or behind
- MSG_PICK_Z with (length=20) has no other characters/values before or behind
- MSG_RESUMING with (length=20) also works fine and MSG_RESUMING_PRINT has (length=20,lines=1)
- MSG_SELFTEST_FAN_NO with (length=18) is also no problem in the 'Calibration->Selftest' menu
- MSG_TAKE_EFFECT seams not to be used anymore, cannot find it anywhere in the code, except the language files.
-  MSG_ADJUSTZ with (length=18) has no other characters/values before or behind
- MSG_SELFTEST_ERROR with (length=19) has no other characters/values before or behind
- MSG_SELFTEST_NOTCONNECTED with (length=19) has no other characters/values before or behind
- MSG_SELFTEST_WIRINGERROR with (length=18) has no other characters/values behind
- MSG_UNLOAD_FILAMENT with (length=18) has no other characters/values behind

**Pull request closed without merging**
