### PR TITLE
Add M850 code for setting sheet label and offsets

### LINKED ISSUE #2091: Feature Request: Allow uncalibrated sheet to be selected by manually specifying live-z
Feature request for the sheets menu:
Currently, an uncalibrated sheet cannot be selected and you must run the first layer cal on it to use it. 

Please allow selection/use of an uncalibrated sheet via manually entering the offset. Prior to this feature I and many others kept track of our sheets with labels and relative offsets; e.g. I know my smooth sheet is 0.350 thicker than my PC sheet, and they both have a label with their Z values. Being able to calibrate a single sheet and then just dial-in any others based on that value without re-doing the calibration would be a bonus. 

Similarly, sometimes a factory reset is necessary, and if the printer has not been altered, the previous Live-Z values were still valid and it would be nice to be able to just re-enter them and resume printing without needing to possibly swap to PLA, run the calibration, and then change back again to whatever you were using before.

### LINKED ISSUE #2153: Feature Request: Make sheets available via M503 and M500
As changing sheet names and values can be a pain in the bu7t, I would like to suggest to make these available via M503 and M500 gcodes.

This way we could easy change
- Sheet Numbers
- Sheet Names
- Sheet Live-Z values

### LINKED ISSUE #3534: extended "gcode" to rename/manage sheets
editing sheet names and possibly ordering them, is a pain using the printers UI, would it be possible to have some sort of extended commands, or something that we could send using gcode/pronterface/prusaslicer to administer such features?
Usage of the sheets are useful for sheets itself, but also for having sheet+nozzle combos when one often swaps back and forth between a couple nozzles, but using the UI kinda prohibits this usage.

### PR DESCRIPTION
**Pull request by vintagepc**
Per #2091 and #2153 
This adds M-code support for reading and setting sheet labels and offsets to satisfy advanced user needs. Logic being, if you know how to manually send g-codes to your printer, you're advanced enough to handle the responsibility.
I chose 850 because it's near other first-layer/levelling parameters and appears to be unused in official marlin as well.

Usage: 
- M850 S[sheet] Z[offset] L[label] B[Bed temp] P[PINDA temp]
- Z and L are optional, if one or both are missing the current values are reported instead.
- If L and/or Z are specified, the sheet's values are updated.
- Z range is validated
- Sheet index is validated
- Requesting info (no L or Z) on an uncalibrated sheet reports as such.

Note: Pronterface capitalizes anything sent. To use lowercase in your sheet names you'll need to use a different terminal program.

Closes #2091
Closes #2153
Closes #3534

### CODE REVIEW

**Comment by vertigo235** [comment]
ah, cool!

**Comment by DRracer** [comment]
@vintagepc very well ;) . Btw. there is already an M851 for setting z-offset: http://marlinfw.org/docs/gcode/M851.html - which in our terminology is live-adjust-z, aka sheet calibration value.
Do you see fit using/improving the M851?

**Comment by vintagepc** [comment]
@DRracer 🤦‍♂  Not sure how I missed that when looking for available gcodes. I'll update it to be M851 instead.

Also I see I left in a magic number in reading the sheet name; I'll change the 7 to a sizeof() too.
Can I ask what the intent of the additional sheet struct fields is? (bed temp, e.g.) I don't think they are currently used but I'd be happy to implement ability to specify those if it is planned to be relevant.

**Comment by DRracer** [comment]
@vintagepc don't worry, such things happen ;) .
The temperature will be used right away, we are preparing another long awaited/requested feature. Stay tuned ;)

**Comment by vintagepc** [comment]
OK, I'll add optional arguments for those as well then.

**Comment by vintagepc** [comment]
Looking at the code, M851 doesn't look like something I want to interfere with; that sets cs.z_probe_offset which is something entirely different from the live Z value, and used in some critical places (MBL, for example). My printer has it currently set at -0.40. If I'm reading that right it is a correction factor applied to the distance of the nozzle below the edge of the PINDA (e.g., "zip tie" distance). 


Edit: To clarify, the firmware has 851 already implemented, as     
case CUSTOM_M_CODE_SET_Z_PROBE_OFFSET:

**Comment by vintagepc** [comment]
(Updated to support B/P parameters for pinda and bed temp)

**Comment by vintagepc** [comment]
Syncronized with latest MK3

**Comment by bbernhard** [comment]
Hi,

I just wanted to ask about the state of this PR here. I've already seen at least two open pull requests regarding a new gcode command, but unfortunately both of those seem to be stalled. As I am also a maintainer of several open source projects myself, I totally understand that there's only so much time to work on all the bugs and feature requests. But as the Prusa printers have such a nice sheet management system I would really love to see that somehow exposed via gcode - I think it opens a LOT of possibilities for automation and convenience features. 

So, I wanted to kindly ask whether there's any chance to a feature like this merged?

Many thanks,
Bernhard

**Review by 3d-gussner — APPROVED** [review]
Old but good

**Review by wavexx — APPROVED** [review]

**Comment by aaronevers** [comment]
Help article "Prusa-specific G-codes" needs to be updated with the M850 documentation (https://help.prusa3d.com/article/prusa-specific-g-codes_112173).

**Pull request merged**
