### PR TITLE
Update check MMU version and change to MMU3

### PR DESCRIPTION
**Pull request by 3d-gussner**
- [X] Don't check MMU version on MK3 or MK3S with `M862.3`
  - old `MK3MMM2` and `MK3SMMU2S` will not warn on
  - Committed this workaround separately to be a ab to revert in future.

- [x]  Cherry pick to MK3_3.13.0 branch

`M862.2` WILL warn but as it wasn't and isn't and probably never be used in PrusaSlicer profiles, I ignored that.

Tested on MK404

- MK3S with MMU3 enabled :heavy_check_mark: 
  - No warning sending `M862.3 P "MK3SMMU2S"` :heavy_check_mark: 
  - No warning sending `M862.3 P "MK3SMMU3"` :heavy_check_mark: 
  - Warning sending `M862.3 P "MK3MMU2"` :heavy_check_mark: 
  - Warning sending `M862.3 P "MK3MMU3"` :heavy_check_mark: 
- MK3 with MMU3 enabled :heavy_check_mark: 
  - No warning sending `M862.3 P "MK3MMU2"` :heavy_check_mark: 
  - No warning sending `M862.3 P "MK3MMU3"` :heavy_check_mark: 
  - Warning sending `M862.3 P "MK3SMMU2S"` :heavy_check_mark: 
  - Warning sending `M862.3 P "MK3SMMU3"` :heavy_check_mark:

### CODE REVIEW

**Review by DRracer — APPROVED** [review]
looks correct :+1:

**Comment by ojrik** [comment]
Greetings. You forgot MK2.5S MMU3. MMU3 on MK2.5S also works for me.
Firmware MMU3 which is released in Firmware_buddy.

**Comment by Ro3Deee** [comment]
> Firmware MMU3 which is released in Firmware_buddy.

@ojrik , you mean https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/master/lib/Prusa-Firmware-MMU ?
We can compile from this link and load it to MMU? And it works with Prusa-Firmware (compiled from git) on  mk3s?

**Comment by ojrik** [comment]
@petrubecheru ,Yes. https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/master/lib/Prusa-Firmware-MMU.
Compiled and uploaded to MMU2S, (I'm still testing) MK3S works without modification, For my MK2.5S, a small modification in the configuration.

**Comment by Ro3Deee** [comment]
It doesn't work. Buddy version is 2.1.8, this firmware needs 2.1.9.modified by PR https://github.com/prusa3d/Prusa-Firmware/pull/4069 

 I will modify the version (its a number in two files)

**Comment by Ro3Deee** [comment]
<strike>Here is my compiled FW for MK3S+ (3.13.0 unreleased) and MMU (2.1.8)</strike>. 
I edited the prusa fw code to check for 2.1.8 (instead of 2.1.9 modified by PR #4069 ) and it works:

https://github.com/prusa3d/Prusa-Firmware/assets/124100239/da8f3af7-5bc2-4597-b7a2-9a6531a186ef

**Comment by 3d-gussner** [comment]
@petrubecheru I removed your self build zip file. Sorry for that. Please don't share self build hex files here.

Please wait until the MMU3 is officially released (soon).

**Comment by 3d-gussner** [comment]
@petrubecheru Thanks for the :+1:

**Pull request merged**
