### PR TITLE
PFW-1536: Reprint function implemented for MK3S/MK3S+

### PR DESCRIPTION
**Pull request by 3d-gussner**
Cherry picked from https://github.com/prusa3d/Prusa-Firmware/pull/4462 as rebase is a pain and broke things.
This PR is a the same than #3071 but using the current repository of my fork of your firmware

**Kudos to @jfestrada for the idea and original PR.**

To support this functionality I have added a **extern bool variable** which can be read/set from cmdqueue.cpp and **ultralcd.cpp** so when the card reader reaches the EOF the variable isPrintFinished will be set to true and the main menu will show the **REPRINT** option.
How do I know which file we need to reprint? All the information needed to perform the reprint was stored on the EEPROM in case of a power panic and the fw recover this information in order to start the print from SD again, so using that information the function reprint_from_eeprom() has been implemented.

Translations:
- [X] :czech_republic: [same as buddy firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/bfb0ffc745ee6546e7efdba618d0e7c0f4c909cd/src/lang/po/cs/Prusa-Firmware-Buddy_cs.po#L3647-L3648)
- [X] :de: [same as buddy firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/bfb0ffc745ee6546e7efdba618d0e7c0f4c909cd/src/lang/po/de/Prusa-Firmware-Buddy_de.po#L3737-L3738)
- [X] :es: [same as buddy firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/bfb0ffc745ee6546e7efdba618d0e7c0f4c909cd/src/lang/po/es/Prusa-Firmware-Buddy_es.po#L3710-L3711)
- [X] :fr: [same as buddy firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/bfb0ffc745ee6546e7efdba618d0e7c0f4c909cd/src/lang/po/fr/Prusa-Firmware-Buddy_fr.po#L3676-L3677)
- [X] :it: [same as buddy firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/bfb0ffc745ee6546e7efdba618d0e7c0f4c909cd/src/lang/po/it/Prusa-Firmware-Buddy_it.po#L3698-L3699)
- [X] :poland: [same as buddy firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/bfb0ffc745ee6546e7efdba618d0e7c0f4c909cd/src/lang/po/pl/Prusa-Firmware-Buddy_pl.po#L3679-L3680)
- [X] :netherlands: by @3d-gussner @vintagepc please check [Firmware_nl.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-92de134d7cfe75b62e86a4e83716cd95550b11f2ddee228150a9c6faa4d6a34bR2585-R2586)
- [ ] :croatia: @Prime1910 please check [Firmware_hr.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-487d5469566575627c7dc47abf437c52e890de941c1fd8d4db5a2a4d6ef08d64R2577-R2578)
- [x] :hungary: @AttilaSVK please check [Firmware_hu.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-3a7d51d07fb16c60d273b7986aa88a7892939b19a9bad4f3501a153ffb0604e9R2582-R2583)
- [ ] :norway: @OS-kar and @trondkla please check [Firmware_no.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-22e5dd5d54111e837f3b40db65f2a126b09cc4157dcfa1f34b6e5dde0bf4a607R2559-R2560)
- [x] :romania: @leptun and @Hauzman please check [Firmware_ro.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-6774f424618c20ccb1d99bf93cb34bab0b6ee03a55868fa7021a11ef6c28667fR2583-R2584)
- [x] :slovakia: @ingbrzy and @shatter136 please check [Firmware_sk.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-9584ba5c6a2b7618c16dc96fa21d692e9d5d69c393c55f37166bb05e98557fbcR2565-R2566)
- [ ] :sweden: @Painkiller56 please check [Firmware_sv.po](https://github.com/prusa3d/Prusa-Firmware/pull/4462/files#diff-cf46655e0192f28112da2985d28dc728949010730a0ac629dbb7049f9f53a357R2572-R2573)

- [X] LCD Reprint menu only shown
  - [X] SD PrinterState is SDPrintingFinished. 
  - [X] Host/USB PrinterState is HostPrintingFinished AND `M79` timer is running. A `Set Ready` will change the PrinterState and hide the `Reprint` LCD menu

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@jfestrada Please review this PR.

**Comment by jfestrada** [comment]
I hope to be able to review it today night

**Review by gudnimg — APPROVED** [review]
Looks good to me.

**Comment by jfestrada** [comment]
I miss this code on the last part of the function __lcdui_print_percent_done__

```
    enableReprint = true;
    if(usb_timer.running())
    {
        enableReprintUSB = true;
    }else
    {
        enableReprintUSB = false;
    }
```

This is the initialization of the reprint variables in order to control the behavior of the Reprint menu action.

**Comment by 3d-gussner** [comment]
> I miss this code on the last part of the function **lcdui_print_percent_done**
> 
> ```
>     enableReprint = true;
>     if(usb_timer.running())
>     {
>         enableReprintUSB = true;
>     }else
>     {
>         enableReprintUSB = false;
>     }
> ```
> 
> This is the initialization of the reprint variables in order to control the behavior of the Reprint menu action.

@jfestrada Thanks for the review. I use now the `PrinterState` to show the menu. For some reason my last commit wasn't included.  See https://github.com/prusa3d/Prusa-Firmware/pull/4510/commits/d9d42a06781977bd19dcf63f929ad90d6640c28f

**Comment by jfestrada** [comment]
> > I miss this code on the last part of the function **lcdui_print_percent_done**
> > ```
> >     enableReprint = true;
> >     if(usb_timer.running())
> >     {
> >         enableReprintUSB = true;
> >     }else
> >     {
> >         enableReprintUSB = false;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the initialization of the reprint variables in order to control the behavior of the Reprint menu action.
> 
> @jfestrada Thanks for the review. I use now the `PrinterState` to show the menu. For some reason my last commit wasn't included. See [d9d42a0](https://github.com/prusa3d/Prusa-Firmware/commit/d9d42a06781977bd19dcf63f929ad90d6640c28f)

Ok, I see, then everything should be ready.

**Review by gudnimg — APPROVED** [review]

**Comment by 3d-gussner** [comment]
@jfestrada Is it okay that we merge this copy of your great PR to reduce the commit numbers?
Thanks again for providing the PR.

**Comment by jfestrada** [comment]
> @jfestrada Is it okay that we merge this copy of your great PR to reduce the commit numbers?
> Thanks again for providing the PR.

Yes of course, go ahead with the merge!!

**Comment by 3d-gussner** [comment]
@jfestrada While testing few other PrusaLink/OctoPrint related things, I have seen in the [octoprint actions documentation](https://docs.octoprint.org/en/master/features/action_commands.html) that a `// action:start` will re-start the last selected file. Also the `Reprint` menu of a finished host print should not be shown if the host isn't pining the printer with `M79`

What do you think of these changes? 
```
--- a/Firmware/messages.cpp
+++ b/Firmware/messages.cpp
-const char MSG_OCTOPRINT_REPRINT[] PROGMEM_N1 = "// action:reprint"; ////
+const char MSG_OCTOPRINT_START[] PROGMEM_N1 = "// action:start"; ////

--- a/Firmware/messages.h
+++ b/Firmware/messages.h
-extern const char MSG_OCTOPRINT_REPRINT[];
+extern const char MSG_OCTOPRINT_START[];

--- a/Firmware/ultralcd.cpp
+++ b/Firmware/ultralcd.cpp

-        } else if (GetPrinterState() == PrinterState::HostPrintingFinished) {
+        } else if ((GetPrinterState() == PrinterState::HostPrintingFinished) && M79_timer_get_status())  {

-    SERIAL_PROTOCOLLNRPGM(MSG_OCTOPRINT_REPRINT);
+    SERIAL_PROTOCOLLNRPGM(MSG_OCTOPRINT_START);
```
I tested this with [MK404 sim](https://github.com/vintagepc/MK404) and Octoprint and works well.

**Comment by jfestrada** [comment]
With the documentation on my hand I would say that will works out of the box so will be better than deal with a new plugin in order to define the "action". The only concern is about the behavior if you don't have any file selected on octoprint, but that will not happen at least that you restart Octoprint and in that case the printer will reconnect and restart so the reprint menu will disappear. To my mind this change will works and will save some bits.

**Comment by 3d-gussner** [comment]
Yes it will not work if Octoprint restarts as no file is selected.
Still an improvement for a working and stable OctoPrint.
Only requirement we defined for PrusaLink/PrusaConnect is that the printer needs to be "pinged" to enable some host related menus and messages.
So for Octoprint would be a Plugin needed that pings the printer that the host is alive with gcode `M79`.

`M79` is used to ping the printer:
- `Set Ready` menu only shown while the M79_timer is running
- `Reprint` of a finished Host print is only shown while the M79_timer is runnig

**Comment by 3d-gussner** [comment]
@jfestrada Just tested the change 

1. a quick OP print 
2. Reprint and let it finish
3. restart OP
4. connect OP
5. Reprint shown as I have in GCODE scripts some additional changes like `M79 S"OP"` in after printer connected
   a. It sends `// action:start` but OctoPrint just ignores it

**Comment by mhouse1** [comment]
thank you, been waiting for this for a long time, will make operating a print farm much easier.

**Pull request merged**
