### PR TITLE
M860 fix: send busy messages

### PR DESCRIPTION
**Pull request by PavelSindler**

### CODE REVIEW

**Comment by matthew-humphrey** [comment]
Casting my vote for a quick merge and release of this one. I'd love to go back to using octoprint, but won't do it until this fix is in.

**Comment by morimorida** [comment]
I think this will fix the repetier server problem also. +1 to vote for quick merge.

**Comment by stahlfabrik** [comment]
Guys, isn’t it in 3.2.1 already?

**Comment by matthew-humphrey** [comment]
It does not appear to be; the PR is still open, the commit is not in the MK3 branch. and the change to Marlin_main.cpp, is not there if you go look at the source for 3.2.1.

@PavelSindler - can you comment on the status of this?

**Comment by stahlfabrik** [comment]
Ah ok. Sorry my bad! I am away from my computer at the moment so I based my statement solely on (wrong) recollections. I should have checked first

**Comment by matthew-humphrey** [comment]
@stahlfabrik looks like it was just merged, so hopefully will be in the next release. I'm planning on doing my own build to test  it out.

**Comment by stahlfabrik** [comment]
That is a save bet!:-)

**Comment by gdombiak** [comment]
Pretty please, release it soon. :) Cannot use octoprint in a reliable way.

**Comment by benr916** [comment]
Started having problems with this command in the latest version of OctoPrint (1.5.2) and had to remove the line from my startup G-code. Now everything is back to working normally.

**Comment by leptun** [comment]
@benr916 What fw version are you using? I think I recently fixed this.

**Comment by benr916** [comment]
> @benr916 What fw version are you using? I think I recently fixed this.

FW for the printer? Prusa i3 MK3S v3.9.3

**Pull request merged**
