### PR TITLE
:construction: Build with cmake

### PR DESCRIPTION
**Pull request by vintagepc**
Rework the firmware to be more like the Buddy FW in that it has bootstrap.py to retrieve the toolchain, and cmake for the build to make it platform-agnostic; also gets rid of the arduino IDE build dependency.

- [x] I need to resync this with the MK3 branch. 
- [ ] Note multilanguage builds are not quite functional yet.

### CODE REVIEW

**Review by DRracer — APPROVED** [review]
very nice :+1: 
Just one question: do you plan to subtract something from the number of commits to match the build server?

**Comment by vintagepc** [comment]
Not unless it's required... seems like a good opportunity to scuttle that legacy anchor nobody seems to understand anymore :wink: 
The build server could always do this by overriding the appropriate cmake var though.

**Comment by arekm** [comment]
Usuall cmake way (cmake standard) doesn't work for me and README.md wasn't updated sadly, so what's the way to build using cmake?

```
[arekm@ixion Prusa-Firmware]$ mkdir build
[arekm@ixion Prusa-Firmware]$ cd build
[arekm@ixion build]$ cmake ../
-- Found Python3: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter
CMake Warning (dev) at cmake/ProjectVersion.cmake:30 (SET):
  Cannot set "PROJECT_VERSION": current scope has no parent.
Call Stack (most recent call first):
  CMakeLists.txt:23 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Project version: 3.13.0
-- Project version with short suffix: 3.13.0+6389
CMake Warning at CMakeLists.txt:48 (MESSAGE):


  ***************** YOUR ATTENTION PLEASE *****************

  CMake support is experimental.  There is no guarantee at this time.  If you
  have problems you are encouraged to fall back to the tried-and-true
  methods.

  *********************** THANK YOU **********************

  We now return to your regularly scheduled Firmware Build.


-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Language maximum size (from config.h): 13568 bytes
-- Configuring done
CMake Error at CMakeLists.txt:495 (add_executable):
  Cannot find source file:

    Tests/AutoDeplete_test.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:495 (add_executable):
  No SOURCES given to target: tests


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by vintagepc** [comment]
It is still a WIP that is rough around the edges (hence the message), but it now works similar to the 32-bit firmware for the Mini - namely:
- Run python utils/bootstrap.py to download all the dependencies
- Open project with VS code and select the appropriate "Local AVR GCC" kit
- Configure
- Build target
The error you are getting is using a non-avr compiler, which cannot build the firmware, only the tests (which , to my knowledge, have been broken for a while)

Once we finish polishing things to the point where it's ready for general use the instructions will be updated.

**Comment by vintagepc** [comment]
You'll know it's set up/configured right if the VS code cmake pane looks like this, with all the different language targets for all of the possible printers:
image

**Comment by arekm** [comment]
Thanks. More questions.

GUIs... There will be no cmdline way at all or just "not yet" ? (My opinion is that requiring GUI for build is a wrong way and I almost never build things locally)

Also with cmake the usual way is to contain entire build (deps, intermediate files, output binaries) in current directory (+ subdirectories; hence "mkdir build; cd build; cmake ..") but I see some non standard approach is used here which pollutes outside dirs. Is that also the planned way?

**Comment by wavexx** [comment]
Consider cmake to be still experimental and unfinished at this time. See #3647 for some more progress, but we didn't verify the multi-language builds yet.

I'm always building using the cli, you don't need UIs, just have all the correct dependencies set.
Try running `./utils/bootstrap.py`: it should setup the `.dependencies` directory with avr-gcc-7.3.0 and prusa3dboards-1.0.5-2.

Once that is set, you can start the build with:

```
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE="../cmake/LocalAvrGcc.cmake" -DCMAKE_BUILD_TYPE=Release
```

It works the usual way.

**Comment by vintagepc** [comment]
As noted above, manual configuration can be done via the command line by specifying the appropriate toolchain file (cmake/LocalAVRGcc) and any other options. But given that most users are not likely to be command-line wizards it makes sense for there to be a mostly UI-driven option to reduce the support burden. Just about all the VS code UI does is pass the options from `.vscode/cmake-kits.json`

Additionally, at some point the pf-build scripts will also be updated to run cmake behind the scenes rather than maintaining four disparate ways of compiling the firmware. 

Lastly, the only non-"build" folder thing that is changed is the generation of the `build_gen` folder to facilitate a nicer UI layout. I'd previously tried to keep it in the 'build' folder but this leads to ugly and confusing pathing in the UI. Further complications include that this cannot break the existing build while it's brought up to speed, and some of the legacy marlin clunkiness regarding configuration handling. I'm all for being a purist but sometimes there are things where it makes sense to bend the rules for ease of use of the target audience.

**Comment by arekm** [comment]
Applied https://github.com/prusa3d/Prusa-Firmware/pull/3647. Afer cmake Makefile was created outside build directory (in top level dir). 

```
$ cd build
$ cmake .. -DCMAKE_TOOLCHAIN_FILE="../cmake/LocalAvrGcc.cmake" -DCMAKE_BUILD_TYPE=Release
-- Project version: 3.13.0
-- Project version with short suffix: 3.13.0+6389
CMake Warning at CMakeLists.txt:48 (MESSAGE):


  ***************** YOUR ATTENTION PLEASE *****************

  CMake support is experimental.  There is no guarantee at this time.  If you
  have problems you are encouraged to fall back to the tried-and-true
  methods.

  *********************** THANK YOU **********************

  We now return to your regularly scheduled Firmware Build.


Language maximum size (from config.h): 13568 bytes
-- Configuring done
-- Generating done
-- Build files have been written to: /home/users/arekm/.GIT/Prusa-Firmware
$ ls -l ../Makefile
-rw------- 1 arekm users 6179 Oct  2 20:58 ../Makefile
$ cd ..
$ make
[ 25%] Building CXX object tests/CMakeFiles/tests.dir/tests.cpp.o


[ 50%] Building CXX object tests/CMakeFiles/tests.dir/Example_test.cpp.o
[ 75%] Building CXX object tests/CMakeFiles/tests.dir/PrusaStatistics_test.cpp.o
[100%] Linking CXX executable tests
[100%] Built target tests
```

Probably some one more step is needed to build actual firmware. Right?

**Comment by vintagepc** [comment]
you're going to want to specify one of the targets, e.g. `make MK3S-EINSy10a_EN-only`.

**Comment by wavexx** [comment]
From the output there it's still building for the host system (ie, just the tests).
The output from cmake should look like this:

```
cmake .. -DCMAKE_TOOLCHAIN_FILE="../cmake/LocalAvrGcc.cmake" -DCMAKE_BUILD_TYPE=Release
-- Found Python3: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter
-- Project version: 3.13.0
-- Project version with short suffix: 3.13.0+6401
CMake Warning at CMakeLists.txt:48 (MESSAGE):


  ***************** YOUR ATTENTION PLEASE *****************

  CMake support is experimental.  There is no guarantee at this time.  If you
  have problems you are encouraged to fall back to the tried-and-true
  methods.

  *********************** THANK YOU **********************

  We now return to your regularly scheduled Firmware Build.

tc dir is /home/wavexx/Prusa-Firmware-mk3s/.dependencies/avr-gcc-7.3.0
tc dir is /home/wavexx/Prusa-Firmware-mk3s/.dependencies/avr-gcc-7.3.0
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
tc dir is /home/wavexx/Prusa-Firmware-mk3s/.dependencies/avr-gcc-7.3.0
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/wavexx/Prusa-Firmware-mk3s/.dependencies/avr-gcc-7.3.0/bin/avr-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
tc dir is /home/wavexx/Prusa-Firmware-mk3s/.dependencies/avr-gcc-7.3.0
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/wavexx/Prusa-Firmware-mk3s/.dependencies/avr-gcc-7.3.0/bin/avr-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Language maximum size (from config.h): 13568 bytes
Variant added: 1_75mm_MK25-RAMBo10a-E3Dv6full
Variant added: 1_75mm_MK25-RAMBo13a-E3Dv6full
Variant added: 1_75mm_MK25S-RAMBo10a-E3Dv6full
Variant added: 1_75mm_MK25S-RAMBo13a-E3Dv6full
Variant added: 1_75mm_MK3-EINSy10a-E3Dv6full
Variant added: 1_75mm_MK3S-EINSy10a-E3Dv6full
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wavexx/Prusa-Firmware-mk3s/x
```

**Pull request merged**
