### PR TITLE
add travis shellcheck test

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
This PR is a simple demonstration of adding a travis configuration to run `shellcheck` as a sh script linter but does not currently resolve any of the numerous warnings.  If the maintainers are open to adding such a test, I am willing to add sh syntax fixes to this PR.

**Comment by mkbel** [comment]
@XPila Can you decide if we want this?

**Comment by jhoblitt** [comment]
Ping?

**Comment by mkbel** [comment]
Thank you for your offer. We are refactoring language scripts to be more readable, feature rich and cross platform. So it would be waste of resources to polish it in current state.

**Comment by jhoblitt** [comment]
I'm not following the logic here... running shellcheck on ANY new shell scripts would be a good start towards making them "more readable, feature rich and cross platform".

**Comment by 3d-gussner** [comment]
@jhoblitt Thanks, but the travis build has been updated. Closing.

**Pull request closed without merging**
