### PR TITLE
M600 Q parameter enhancement

### PR DESCRIPTION
**Pull request by guykuo**
Added new, optional Q parameter to M600 Gcode.
Q parameter suppresses M600's first MSG_PRESS_TO_UNLOAD.

Why? Support for easier filament color change.
I have written this patch to support rainersc's nifty manual color change technique as described at
https://schlosshan.eu/blog/2019/03/02/prusa-i3-mk3-real-multicolour-prints-without-mmu/

He has an open issue describing the need for this enhancement.
https://github.com/prusa3d/Prusa-Firmware/issues/1471

Rainer has already tested a compiled firmware with this M600 Q parameter, and reports it works well.
https://shop.prusa3d.com/forum/user-mods-octoprint-enclosures-nozzles--f65/simple-way-to-print-in-real-multi-color-without-mm-t28186-s10.html

The new Q parameter allows message displayed by M117 to remain on screen rather than being immediately erased by M600's first MSG_PRESS_TO_UNLOAD. Without the ability to suppress the 1st message, users attempting his technique cannot see the message indicating which filament should be be inserted. The 1st M600 prompt destroys the message.

Follow up prompts by M600 are not suppressed. Omitting Q lets M600 work as normal. This does NOT affect MMU function.

Usage:
M117 Change to yellow filament
M600 Q

Although this is Rainer's issue, I have written this to get support of his elegant way of limited multi-color printing in official firmware. I view Rainer's technique as a fun, gateway to multi-color printing. Once a user becomes enamored with multicolor, an MMU is in their future.

MulticolorMK3-Samples

### CODE REVIEW

**Comment by guykuo** [comment]
Updated to be once more mergeable with head MK3 repository

**Comment by Eenie75** [comment]
This is awesome!  How do we get some traction?

**Comment by guykuo** [comment]
Not a single nibble from the Prusa side thus far. Pretty discouraging

**Comment by rainersc** [comment]
i am still using thie compiled fw i got from guykuo without any problems, but no progress on getting this merged/reviewed unluckily :(

**Comment by Panayiotis-git** [comment]
This is great! I've tried once such a multi-color print and all my messages were lost.
Even now I use the mmu2, this is a nice feature.

**Comment by guykuo** [comment]
BTW, my version on Github is current with 3.7.1 firmware

https://github.com/guykuo/Prusa-Firmware/tree/M600-Q-Parameter-Enhancement

**Comment by Matrixrs** [comment]
Sorry to see this was not having attention from PRUSA, It's a good way to do small color print and see the possibility it offer!  And it seems to change nothing to MMU.  I will buy an MMU at some point but this is just should be seens as bringing people into color print ...  Is there a way to have this in the latest firmware ''prusa3d_fw_MK3S_3_9_0-RC3_3401'' ?  I am not "ready" to start compile my own firmware... :O)

**Pull request closed without merging**
