### PR TITLE
Automatically adjust delta movements in xyzcal based on axis_steps_pe…

### PR DESCRIPTION
**Pull request by joncastillo**
…r_unit defined in prusa_configuration.h . This allows XY 0.9 stepper motors to utilize XYZ Calibration.

### CODE REVIEW

**Comment by joncastillo** [comment]
I have cancelled the pull request for now. Needs work as int16_t cannot contain coordinate values greater than 32767.

**Comment by DRracer** [comment]
@joncastillo thank you for your PR. Please keep in mind we are still working on improving the bitmap search and feature extraction. Anyway - after we are done we'll consider merging your PR as well.

**Comment by joncastillo** [comment]
> @joncastillo thank you for your PR. Please keep in mind we are still working on improving the bitmap search and feature extraction. Anyway - after we are done we'll consider merging your PR as well.

alright @DRacer, thank you. i'll work on it in the meantime, see if i can lessen code space.

**Review by nosRider1 — COMMENTED** [review]
I applied the source and tested it with a 0.9 degree stepper motor.
In addition, only 1 point operates normally, and 2-4 points return to 1 point and operate.
The bottom line is that you check 1 point 4 times and you get a calibration failure message.
It moves up to 2, 3, 4 points, but immediately returns to 1 point.

I'll ask you one more question.
For me, Extruder Motors and XY Stepper Motors are inconsistent. So I can't use the LA K value.
LA is applied in positions where the extruder motor is 1mm faster. Please let me know if there are any features that may be delayed.

**Comment by wavexx** [comment]
> For me, Extruder Motors and XY Stepper Motors are inconsistent. So I can't use the LA K value.
> LA is applied in positions where the extruder motor is 1mm faster. Please let me know if there are any features that may be delayed.

I'm not fully sure I get this. LA should work with any motor as long as the axis steps/mm is set correctly.

**Comment by nosRider1** [comment]
> > 저에게는 압출기 모터와 XY 스테퍼 모터가 일치하지 않습니다. 그래서 저는 LA K 값을 사용할 수 없습니다. 
> > LA는 압출기 모터가 1mm 빠른 위치에 적용됩니다. 지연 될 수있는 기능이 있으면 알려주세요.
> 
> 나는 이것을 얻는 지 완전히 확신하지 못합니다. LA는 축 스텝 / mm가 올바르게 설정되어있는 한 모든 모터에서 작동해야합니다.

Thank you.
I know what you're talking about.

**Comment by nosRider1** [comment]
I use a 0.9 degree stepper motor on the XY axis. So, I tried more than 10 tests. Only 1 point is calibrated. Hope this is well resolved.

Now, I am happy to print with a 0.9 degree stepper motor, and I am grateful to everyone who participates in the firmware development.

**Comment by joncastillo** [comment]
Hello @nosRider1 , sorry I didn't see your message. I haven't been active on the firmware source and the reason is that my einsy rambo died on me. Sadly, I overhauled my printer to use a 32-bit alternative which is no longer compatible with this firmware.

I tested these on the following settings:

#define DEFAULT_AXIS_STEPS_PER_UNIT   {200,200,3200/8,564.73}
#define TMC2130_USTEPS_XY   16        // microstep resolution for XY axes
#define TMC2130_USTEPS_Z    16        // microstep resolution for Z axis
#define TMC2130_USTEPS_E    32         // microstep resolution for E axis

The default_axis_steps_per_unit along with int32_t xyzcal_point_xcoords[4] are used to determine the location of the 4 points.

Does it not work for you?

**Comment by joncastillo** [comment]
> > > 저에게는 압출기 모터와 XY 스테퍼 모터가 일치하지 않습니다. 그래서 저는 LA K 값을 사용할 수 없습니다.
> > > LA는 압출기 모터가 1mm 빠른 위치에 적용됩니다. 지연 될 수있는 기능이 있으면 알려주세요.
> > 
> > 
> > 나는 이것을 얻는 지 완전히 확신하지 못합니다. LA는 축 스텝 / mm가 올바르게 설정되어있는 한 모든 모터에서 작동해야합니다.
> 
> Thank you.
> I know what you're talking about.

i think it is better that you take a video. it is not easy to understand through a translation. When using 0.9 steppers, AXIS_STEPS_PER_UNIT must be adjusted using Prusa’s online calculator.

This change allows calibration even when these hardcodes are adjusted.

**Comment by 3d-gussner** [comment]
Closing this PR as at this moment we don't support any 0.9° motors.

**Pull request closed without merging**
