### PR TITLE
tmc2130 optimalization, accurate homing and microstep linearity corre…

### PR DESCRIPTION
**Pull request by XPila**
…ction

dcode D12 removed (no longer needed)
homeaxis optimized + xy home calibration support
new eeprom variables
new lcd menu edit types (byte3, mres, wfac), new menu "Experimental"
currents adjusted

### CODE REVIEW

**Comment by TheBrigandier** [comment]
I was having very small (but very noticeable on glossy PETG) vertical lines on my prints, even printing at 10mm/s. Are there any changes in this beautiful load of code that may affect that? :D

**Comment by XPila** [comment]
@ff8jake this pullrequest solves three issues:
1. Accurate rehoming for crashdetection (calibratin required). In original implemenation some small "layer shifts" happends in case of detected crash.
2. Microstep linearity correction (calibration required). Without correction it produces some interference on surface.
3. Variable microsteping resoution for E axis (M350).

**Comment by XPila** [comment]
following pictures demonstrate microstep linearity correction:
1. three objects: left- correction calibrated, middle- near calibration, right- correction off
you can see diagonal moire on middle and right object
https://drive.google.com/open?id=1zvvM45FIPNhKrHC3fUzVP5l9I0UYY-Ih
2. detail - correction off
https://drive.google.com/open?id=1VoN1_opp2F3eji52rfmuCyGrA5p-mfqA
3. detail - near calibration
https://drive.google.com/open?id=1KuiIaqaSYnHU6ZyBf1HPliDJm100s2Fb
4. detail - calibrated
https://drive.google.com/open?id=1mFyjsa85SUyjSyO6f7P9umRR6O0tsj68

**Comment by TheBrigandier** [comment]
@XPila you may be my hero now. On your images, at 10mm/s the vertical lines I am experiencing match image #3. I hadn't noticed the moire, but definitely the same vertical "scratches". The difference in image #4 is great. Will flash this when I get home.

**Comment by XPila** [comment]
On previous images is correction enabled only for E axis. Calibration is not simple. E axis must be calibrated first.
I found some printers was out of range 1.08-1.12, fix is in last comit.
step by step for E axis:
1. Disable correction for all axes, print the sample gcode (diagonal moire should be visible).
2. Enable correction for E axis, good starting value is 1.100, print the sample. If you have luck, moire disappers.
3. Decrease correction by 0.01, print sample, compare it. Repeat this step until moire disappears.
4. Fine tune correction (+-0.005).

sample gcode:
https://drive.google.com/open?id=13WsC3BmIUCQ8Dj5qg8yiDOesO7mHO_iT

**Comment by TheBrigandier** [comment]
@XPila With Prusa Silver PLA, moire was present with E calibration off, and disappeared completely (best I can tell) at 1.100 per your suggestion. I then decided to give your "Recommended Settings" option (which set everything to 1.100) and quality on the sample gcode looks great! Going to try a Benchy next. 👍

**Comment by XPila** [comment]
@ff8jake you are lucky boy. Some printers differs and calibration is long time issue. This calibration is just temporary solution, I will add better calibration sample gcode.

**Comment by ghost** [comment]
has anyone put together more info on this? how to download? how tom install? where the calibration settings are? ect ect does this help solve some layer shift issues?

**Comment by XPila** [comment]
@Lemlurkerman I will add description for features in this pullrequest. Features will be available in 3.1.2. RC1 (next week).

**Comment by Panayiotis-git** [comment]
Does the logic of any of these fixes could apply in proportion to the MK2 version? Especially those that refer to diagonal moire-pattern.

**Comment by XPila** [comment]
@Panayiotis-git this fixes are only for MK3 with TMC2130 stepper drivers.

**Comment by heliotropik** [comment]
@XPila, Great work! 
While calibrating, I've had 2 issues.  Maybe those issues only apply to me or not.
1- When I tested X Axis at 0.920, my X Axis motor crashed. Selecting print or just selecting move X Axis from the settings menu will make it crash. Resulting in the other 2 Axis trying to home and Z Axis won't stop at 0 and furiously forcing it's way in the bed. 
2- When I selected E Resolution to 64, I haven't notice but the nozzle was just at the limit of extrusion temp. So when I confirmed the setting, it extruded some not hot enough plastic. When I went back to 32, I made sure it was to temp, but it didn't extrude any plastic.
Thanks!

**Comment by Panayiotis-git** [comment]
@XPila, since I experience moire-patterns on my MK2 prints, I was hoping that not the source but the logic applied to fix the issue for MK3, could by applied somehow to fix the issue on MK2.

**Comment by XPila** [comment]
@heliotropik
1. Value 0.920 makes the curve too steep, it has effect on smoothnes of motion. In this experimental version is range limited from 0.9 to 1.25, but real range is maybe from 1.02 to 1.12, outside of this range you can hear that motor does not move smoothly. Correction for XY can be adjusted also by hearing...
2. Switching resolution should not extrude (move the extruder motor). Maybe bug. I will try to reproduce.

**Comment by XPila** [comment]
@Panayiotis-git linearity correction need trinamic controller (MK3), it is not supported for allegro (MK2).

**Comment by 3dprintronics** [comment]
Hello Everybody,
I am tried installing non prusa stepper motors to my Mk3, but the sensorless homing does not work with them. Every time the X axis or Y axis home it shows (error in length). I think it has something to do with the sensorless sensitivity setting in the Mk3 firmware or the voltage to stepper motors. Is it that we can only use stepper motors from Prusa Research?. Any help in this regard will be really appreciated. Specs of Non Prusa stepper motor - Nema 17, 1.8-degree same size as prusa steppers.

Thanks

**Comment by adam6666** [comment]
Hello Everybody,
I am tried installing non prusa stepper motors to my Mk3, but the sensorless homing does not work with them. Every time the X axis or Y axis home it shows (error in length). I think it has something to do with the sensorless sensitivity setting in the Mk3 firmware or the voltage to stepper motors. Is it that we can only use stepper motors from Prusa Research?. Any help in this regard will be really appreciated. Specs of Non Prusa stepper motor - Nema 17, 1.8-degree same size as prusa steppers.

Thanks

**Comment by TheBrigandier** [comment]
@XPila Using 3.1.3, still seeing some moire, check these reflections out (single wall cube, translucent gold PLA):

https://youtu.be/w9ALO5tnVnk
https://youtu.be/dBUfuZIAdOg
https://youtu.be/WifUG5xj7oM
https://youtu.be/Thuy1ipYI5U
https://youtu.be/oDduj9O6j_w

Is it possible this needs to be optimized further from the values you guys arrived at from this experimental menu?

**Comment by stahlfabrik** [comment]
Hi @XPila 

has anything changed from the procedure for 3.2.0-RC2? is there a new/optimized calibration Gcode anywhere to be downloaded (you mentioned there will be a better one)?

Best regards

**Comment by stahlfabrik** [comment]
I am currently printing the gcode from above. Man, that takes a while:-) Is it recommended to print that completely? Or are - lets say 3cm - enough?

Edit: Looking at XPilas pictures I answered this question myself:-) It is fine to stop it after a few centimeters

**Comment by stahlfabrik** [comment]
Oh and do I understand it right, that only E value can be set now in 3.2.0-RC2?

**Comment by devilhunter84** [comment]
@adam6666 

Did you make any progress with the third party motors and sensorless homing?
I've run into the same thing. Sometimes sensorless homing works for non-prusa motors, but most often it does not. 
Can't figure out where the setting is in https://github.com/prusa3d/Prusa-Firmware/commit/f916e0f8797107e447d2814691bcd06871575f8b

edit: made a thread in case someone stumbles upon this, too
https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f64/sensorless-homing-with-third-party-motors-doesn-t--t17528.html#p82238

**Pull request merged**
