### PR TITLE
Fix long-press bug in sheets menu and cancels rename with long-press.

### PR DESCRIPTION
**Pull request by BeldrothTheGold**
This fixes issue #2179 and allows the user to cancel renaming sheets.

### CODE REVIEW

**Comment by DRracer** [comment]
@BeldrothTheGold basically a working approach, however let's generalize it - almost every other dialog suffers from this problem. Are you willing to work on this issues further?

**Comment by BeldrothTheGold** [comment]
> @BeldrothTheGold basically a working approach, however let's generalize it - almost every other dialog suffers from this problem. Are you willing to work on this issues further?

Absolutely interested! What did you have in mind?

**Comment by Panayiotis-git** [comment]
Does the fix referenced at the:

https://github.com/prusa3d/Prusa-Firmware/issues/1196#issuecomment-439501656

fix the problem?

**Comment by DRracer** [comment]
@BeldrothTheGold @Panayiotis-git wouldn't it be better to specify only the allowed scenarios when the long press should work? Looking at the code - it does the opposite.
The long press should only work on the status screen in 2 modes:
1. move z when not printing
2. do live-adj-z for the first few layers when printing
Does it make sense?

**Comment by leptun** [comment]
I think it should also do move-z / live-adjust-z when long-pressing in any of the menus (main menu, settings menu, etc.).

**Comment by BeldrothTheGold** [comment]
@DRracer 

> @BeldrothTheGold @Panayiotis-git wouldn't it be better to specify only the allowed scenarios when the long press should work? Looking at the code - it does the opposite.
>The long press should only work on the status screen in 2 modes:
>move z when not printing
>do live-adj-z for the first few layers when printing
>Does it make sense?

 and @leptun 

> I think it should also do move-z / live-adjust-z when long-pressing in any of the menus (main menu, settings menu, etc.).

These requests seem mutually exclusive.

**Comment by BeldrothTheGold** [comment]
Do we want to retain the current functionality where long-press in any menu will bring up the applicable Z adjustment, and only block this in cases where it causes issues? 

Or only bring up the Z adjustment while in the status menu? If this is the case would long press in menus then return to the previous menu by default?  Do nothing? 

@Panayiotis-git I will test this fix when I get home today.  I'll add it in a build without my commit to see if the bug which causes the UI to stop responding after a long-press in the rename menu is fixed. 

In anycase. I think it's still a good idea to have the long-press in an edit menu cancel the action and return to the previous menu.

**Pull request closed without merging**
