### PR TITLE
Update Marlin_main.cpp

### PR DESCRIPTION
**Pull request by ojrik**
MK3S Bug Printer type

### CODE REVIEW

**Comment by ojrik** [comment]
The error is in Firmware 3.6.0 for MK3S and MK2.5S. Variants added file for MK3S and MK2.5S from printer type. The file printers.h added the printer type MK3S 302, MK25S 252. In other files I did not find the configuration for MK3S and MK2.5S. At Marlin_main.cpp I added PRINTER_TYPE == PRINTER_MK3S. At ultralcd.cpp I added PRINTER_TYPE == PRINTER_MK25S.
My MK3S Printer will finish Z-Calibration.

**Comment by MRprusa3d** [comment]
Hello,

could you please specify for us, if have you:
a) MK3S 'assembled printer'
b) MK3S kit
c) MK3S upgrade kit (if, from which model)
d) some self-modification (if, from which model)

thanks

**Comment by ojrik** [comment]
Hello.
My version is from MK2S upgrade to MK3,
MK2S MMU upgrade to MK3 MMU2,
Now I'm waiting for the MK3S MMU2S upgrade
The parts I printed and are mounted so far without the IR Sensor.
The IR Sensor is replaced by the mechanical switch yet.

**Comment by ojrik** [comment]
Firmware 3.6.0 MK3S I had to block #define FAN SOFT PWM, Selftest voted an error on Print FAN.
I changed the Extruder STEPS from 32 to 16 is not a hot Extruder motor.

**Comment by 3d-gussner** [comment]
@PavelSindler Did you see this PR and https://github.com/prusa3d/Prusa-Firmware/pull/1600?
I think it could explain few Z-cal issues on MK3s as 
in the `calibrate_z_auto()` the `current_position[Z_AXIS] = Z_MAX_POS + 2.0;` is set for the MK3.
This should also apply to the MK3S.
In the current state it will use `current_position[Z_AXIS] = Z_MAX_POS + 9.0;` for the MK3S and may cause some issues.
I am sure there is a reason for the `if else` statement.

**Pull request closed without merging**
