### PR TITLE
#2477 Improved M-code control for stealth mode/normal mode

### LINKED ISSUE #1676: M915 Stealth Mode Code not Recognized when sent from octoprint terminal
When attempting to place printer into Silent Mode from terminal with code M915 it states it is an unknown code

### LINKED ISSUE #2477: [ENHANCEMENT]Stealth-mode/Normal-mode  M-code
**Printer type** - Mk3S
**MMU Upgrade** - MMU2S

As noted in #1676 , stealth/power mode is more than just motor currents now. MBL is painfully slow when in stealth mode (esp. 7x7), and very quick in high power mode. This is partly because of all the time spent switching modes before Z-probing.
  
**Describe the solution you'd like**

I can live with the added noise for a few minutes, so I'd be thrilled if it was possible to use an M-code to toggle between normal and silent modes. That way, one could change to high power before MBL, and back to stealth for the print. 

If you already have an M-code number in mind or a suggestion for a good one, I'd be happy to implement this myself.

### PR DESCRIPTION
**Pull request by vintagepc**
(Note, this is a re-factor/cherry pick of #2508 to resolve conflicts)

This closes #2477 and allows dynamic gcode mode changes, for example to get crash detect in risky print areas, or faster MBL:
```
M914
G28 W
G80
M915
```
Features & changes:
- Enable M914/915 for TMC2130 to allow setting stealth and normal mode via g-code.
- Optional "P" argument to write the change to EEPROM when using M code
- Optional 'R' argument to revert to EEPROM value.
- Default behaviour is temporary, i.e. any change is lost either on M84 or reboot.
- Fix possible logic hole causing FORCE_HIGH_POWER_MODE_START to not shift modes if PSU_Delta is defined and there's a stepper timeout before MBL (e.g. slow heating or high target temp)
- Updated stealth mode menus in Tune and Settings menu to indicate if an override is in place. (Menu shows "M915" or "M914" as appropriate. Chosen because no translation is required)
- Shared code for M914/5, partially shared with force_high_power_mode()

Picture, during MBL in stealth mode with an override:
IMG_0018

Closes #2477 
Closes #1676 
Replaces #2508

Flash usage:
235244 -> 235408 bytes = *164 bytes*

Did a quick test in MK404 and it still seems to be behaving as expected after the cherry-picks

### CODE REVIEW

**Review by 3d-gussner — APPROVED** [review]
Tested on MK404 and looks good.

**Review by 3d-gussner — APPROVED** [review]
Tested on MK404 and looks good.

**Comment by 3d-gussner** [comment]
- [ ] Update RepRap gcode wiki

**Comment by arekm** [comment]
Can octoprint know which mode (normal or stealth) is active ? (Related: https://github.com/prusa3d/Prusa-Firmware/pull/2735)

**Comment by gudnimg** [comment]
This possibly resolves https://github.com/prusa3d/Prusa-Firmware/issues/3418

**Comment by 3d-gussner** [comment]
> Can octoprint know which mode (normal or stealth) is active ? (Related: #2735)

Short answer yes you would be able to switch using OctoPrint by injecting the `M914` or `M915` gcode command. The PR2735 is still open and need to be re-reviewed.
This PR has as milestone FW 3.13.1, which will take some time before being  released (still waiting for FW 3.13.0 release). But if you are able to compile the firmware yourself feel free to try it, at own risks :wink:

**Comment by arekm** [comment]
> Short answer yes

Well, rather answer is no. Octoprint has no way to know what's current mode (if changed via printer lcd menu for example or something else sent g-code). Time to wait to 3.13.1 (and then improve some octoprint plugins that need to know which mode is active).

**Pull request merged**
