### PR TITLE
Fix compiler warning and add missing includes in unit test environment

### PR DESCRIPTION
**Pull request by gudnimg**
This PR fixes a few issues I noticed when attempting to create unit test for printer model checks in `util.cpp/h`.

### CODE REVIEW

**Comment by gudnimg** [comment]
I think it would be useful to start stubbing the EEPROM functions... they are easily getting in the way :)

**Comment by gudnimg** [comment]
Draft... I'm gonna add a few more simple fixes. (Like missing stdint include)

**Comment by gudnimg** [comment]
Opening PR up for review.

**Comment by gudnimg** [comment]
Note for future self...  try to remove `ultralcd.h` include from `util.cpp` or the code being unit tested. `ultralcd.h` is a can of "mock" and "stub" worms.

**Review by 3d-gussner — APPROVED** [review]

**Pull request merged**
