### PR TITLE
Fix grammatical errors

### PR DESCRIPTION
**Pull request by Snakzi**

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@Snakzi Thanks for your PR. Dankeschön , dass Du Dir die Zeit genommen hast.

**Review by 3d-gussner — APPROVED** [review]
Totally right.
Always appreciated an other pair of :eyes: looking at the translation. Great community.

**Review by 3d-gussner — CHANGES_REQUESTED** [review]
Sorry was too fast with the approval. Looking at https://app.travis-ci.com/github/prusa3d/Prusa-Firmware/jobs/587163567#L274-L289
The message exceeds the limits of c=20 r=4
```
      ₀₁₂₃₄₅₆₇₈₉₀₁₂₃₄₅₆₇₈₉
   1 |Autoloading filament|
   2 |is active, just     |
   3 |press the knob and  |
   4 |insert filament...  |

 translated text:

      ₀₁₂₃₄₅₆₇₈₉₀₁₂₃₄₅₆₇₈₉
   1 |Automatisches       |
   2 |Filament Laden ist  |
   3 |aktiv, Knopf drücken|
   4 |und Filament        |
   5 |einlegen...         |
```

```
      ₀₁₂₃₄₅₆₇₈₉₀₁₂₃₄₅₆₇₈₉
   1 |Automatisches Fila- |
   2 |ment Laden ist aktiv|
   3 |, Knopf drücken und |
   4 |Filament einlegen...|
```
"Automatisches Fila- ment Laden ist aktiv , Knopf drücken und Filament einlegen..."  sollte passen.

**Comment by DRracer** [comment]
rebased onto current upstream/MK3 for merging

**Comment by DRracer** [comment]
Ouch, the new text is one line longer than requested :thinking: 
```
[E]: Text is longer than definition on line 105: cols=20 rows=4 (rows diff=1)
 source text:
      ₀₁₂₃₄₅₆₇₈₉₀₁₂₃₄₅₆₇₈₉
   1 |Autoloading filament|
   2 |is active, just     |
   3 |press the knob and  |
   4 |insert filament...  |
 translated text:
      ₀₁₂₃₄₅₆₇₈₉₀₁₂₃₄₅₆₇₈₉
   1 |Automatisches       |
   2 |Filament Laden ist  |
   3 |aktiv, Knopf drücken|
   4 |und Filament        |
   5 |einlegen...         |
```

**Review by 3d-gussner — APPROVED** [review]

**Pull request merged**
