### PR TITLE
proper french language

### PR DESCRIPTION
**Pull request by cedricwalter**
Was not always proper french, all accents missing, some minor tweaks.

### CODE REVIEW

**Comment by leptun** [comment]
Thanks for submitting the PR.
Have you tested the firmware with these changes? I think the accents are filtered anyway as the display doesn’t support most of them.

**Comment by 3d-gussner** [comment]
@cedricwalter The LCD used on Prusa printers MK2/2.5/s/3/s cannot display éèáàöäüß and others correctly as the display has a Japanese ROM.

But I saw some proposes that make sense so please review your PR and remove all `´
Also some messages may not exceed some length to be displayed correctly on the LCD.
Most of them have a note c=xx r=yy where "c" stands for max length of characters per line/space and "r" stands for max lines are allowed.
There are still lot of message missing the c=xx r=yy information but that is in the planned to be fixed soon.

https://github.com/prusa3d/Prusa-Firmware/blob/MK3/lang/lang-import.sh import PO files and replaces these "special" characters.

**Review by DRracer — CHANGES_REQUESTED** [review]
Please note the accents are removed from all languages intentionally as they cause problems.
Also please make sure your other changes fit on the screen properly, our language specialists had quite a hard time choosing words and sentences so that it all works.

**Comment by 3d-gussner** [comment]
@cedricwalter Thanks again for your PR.
We have updated the French translation in https://github.com/prusa3d/Prusa-Firmware/pull/2646
Please close this Pull Request, if you agree that it is [solved] in the latest firmware release https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.9.0

**Pull request closed without merging**
