### PR TITLE
use fastio macros over slow Arduino gpio functions

### PR DESCRIPTION
**Pull request by craiglink**

### CODE REVIEW

**Comment by xchwarze** [comment]
Another improvement that is lost in time...

**Comment by wavexx** [comment]
LA1.5 does make changes in stepper.cpp obsolete.
I could review usage in fsensor.cpp as I did some work on it.
A lot has been improved in the lcd handling too.

We're getting there

**Comment by 3d-gussner** [comment]
@gudnimg Please have a look and if it still something to consider.

**Comment by gudnimg** [comment]
Fastio is used everywhere now. I think we changed a lot of it in 3.12

Closing this PR for now because Fastio is used everywhere in the current release

**Pull request closed without merging**
