### PR TITLE
Added Linear Advance port from Marlin 1.1.1

### PR DESCRIPTION
**Pull request by GurliGebis**
* Added Linear Advance port from Marlin 1.1.1
* Made some changes needed to make firmware compile if LIN_ADVANCE is disabled

This is split out from PR #93, with the TMC2130 parts removed.
I have also made some fixes to support compiling with LIN_ADVANCE disabled, so it can be merged without it being enabled as default yet.

### CODE REVIEW

**Comment by GurliGebis** [comment]
Also, it is rebased on top of version 3.0.11

**Comment by GurliGebis** [comment]
Also, this has been cleaned of the Einsy code from PR #93, since it is not the one being used in the MK2

**Comment by madhunm** [comment]
This suffers from the same problem as my fork/PR. When Linear Advance is enabled, the miniRambo does not boot.

**Comment by GurliGebis** [comment]
@madhunm what happens when you try and boot it?

**Comment by madhunm** [comment]
@GurliGebis the display has nothing. :)

I think this has to do with something in stepper.cpp; looking into it as I type this.

**Comment by GurliGebis** [comment]
@madhunm Let me know if there is anything I can do to help :)
It has been a while since I have written C++ code though

**Comment by GurliGebis** [comment]
@madhunm Did you get to take a look at what causes this? And how to recover from a bad firmware? (Not sure I would like to try this, if there is no way back) :)

**Comment by madhunm** [comment]
@GurliGebis I think I have sorted it out... Will submit a PR on your repo for review.

**Comment by GurliGebis** [comment]
@madhunm Seems like there is collision on everything due to line endings being Unix on your end, and DOS in upstream.
I'll try and see if I can merge it manually later

**Comment by GurliGebis** [comment]
@madhunm Have you tested that your code works?
Something makes me think line 1272 in planner.cpp is wrong, since it ignored the position_float array that is used in the "if defined" right above it.

Would it be possible for you to do the same changes you have done, on top of my repo? It is not easy to merge, and it looks like several of the LIN_ADVANCE code has been removed, and I'm not sure if it is by mistake or by ourpose?

**Comment by madhunm** [comment]
Will do it tonight. :)

**Comment by GurliGebis** [comment]
Great, thanks :)

**Comment by GurliGebis** [comment]
@madhunm Did you take a look at it?

**Comment by madhunm** [comment]
Still working on it. :-)

**Comment by GurliGebis** [comment]
Great, thanks :)
Did you get it to work?

**Comment by GurliGebis** [comment]
Closing, nothing is going to happen here, and someone else might be having more luck than me it seems :)

**Comment by theFPVgeek** [comment]
Actually there's been a lot of progress here:  https://github.com/Sebastianv650/Prusa-Firmware/tree/MK2-LIN_ADV-DEV

**Comment by GurliGebis** [comment]
Yep, that is why I'm closing this one :-D

**Pull request closed without merging**
