### PR TITLE
Add new Build System (PlatformIO)

### PR DESCRIPTION
**Pull request by danielalexis**
I've started adding a new build system

PlatformIO is cross-platform which would allow to be compiled on Mac, Windows and Linux without the need for different programs

I've managed to compile it sucessfully (Testing Needed)

I'll add instructions later!

### CODE REVIEW

**Comment by danielalexis** [comment]
Current MMU inst support but can be easily supported by changing platformio.ini

**Comment by danielalexis** [comment]
Instructions:
To install PlatformIO it's necessary the following:
- A Text Editor (The one's with PlatformIO integration are VS Code and Atom)
or
-Command-Line

**Comment by trouch** [comment]
You can get rid of the Firmware -> src move by using proper PIO settings ...
https://docs.platformio.org/en/latest/projectconf/section_platformio.html?highlight=src_dir#src-dir

```
[platformio]
src_dir      = Firmware
```

**Comment by danielalexis** [comment]
Done, ill have to implement tests later

**Comment by danielalexis** [comment]
Lets see if its successful

**Comment by danielalexis** [comment]
It seems to build everything just fine on my end

**Comment by danielalexis** [comment]
I must add here, that its still compatible with Arduino IDE and the others build system

**Comment by danielalexis** [comment]
Its also possible to add more Cross-platform support with Python and/or Atom

**Comment by 3d-gussner** [comment]
@danielalexis Thanks for this PR and as much I like the idea, but I think that Prusa will not change the build environment.

**Comment by danielalexis** [comment]
This would be a much better systemsince its cross-platform and can be integrated with IDE's, it also compiles much quicker.
This is the same Build System that Marlin now uses

**Comment by leptun** [comment]
It may be what marlin uses, but the PrusaFirmware build environment is supposed to be very different.
For starters, we need arduino 1.8.5 because of older gcc version. It has been the same for ages.
Last time I used newer arduino I got faster compiling and smaller hex file. The firmware worked, but I’ve encountered two very weird crashes with it. This leads me to believe there is some hidden bug that is uncovered by the newer gcc.
Prusa also has an ld script. Not sure if this was (or can) be implemented in the newer arduino version.

**Comment by DRracer** [comment]
@danielalexis thank you for your PR. For the in-house 8bit FW development we are not considering moving to other dev environments in near future.
However, the community may benefit from your work. Please feel free to update your PlatformIO integration for some time, let's see how the community reacts.

**Comment by danielalexis** [comment]
> It may be what marlin uses, but the PrusaFirmware build environment is supposed to be very different.
> For starters, we need arduino 1.8.5 because of older gcc version. It has been the same for ages.
> Last time I used newer arduino I got faster compiling and smaller hex file. The firmware worked, but I’ve encountered two very weird crashes with it. This leads me to believe there is some hidden bug that is uncovered by the newer gcc.
> Prusa also has an ld script. Not sure if this was (or can) be implemented in the newer arduino version.

Current PlatformIO uses AVR-GCC 5.4.0 while Arduino 1.8.5 uses 4.9.2, sadly, after doing some research i discovered that PlatformIO doesn't support Prusa Rambo with that version but I've seen some other people who tried to build and it was sucessful (but there was a bug with the lcd but later got fix https://github.com/prusa3d/Prusa-Firmware/pull/2183) so theres no reason for it to have those weird crashes.

About the LD script (i didnt see anything about a LD script on the README), it can be added. If its possible give it to me and I'll implement it.

**Comment by leptun** [comment]
You can look at how PF-build.sh creates the build environment from scratch. It also downloads the script.
This script is only for the multi-lang build scripts. It handles the reserved space in internal flash for languages

**Comment by danielalexis** [comment]
> You can look at how PF-build.sh creates the build environment from scratch. It also downloads the script.
> This script is only for the multi-lang build scripts. It handles the reserved space in internal flash for languages

I just saw it, it seems it only copies to a specific location and PlatformIO already has it in the right but im not sure

**Comment by danielalexis** [comment]
Ups, i was just keeping my branch up-to-date.
On another note, if this ends up merged which Travis CI tests should stay, the ones I designed or the ones already on the repo?

**Comment by brinkeb** [comment]
@danielalexis I get the following error: C:\Users\Username\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory
I can compile if I copy "pins_arduino.h" to the folder but I don´t know, if it is the correct file. Maybe you can add the file to your branch? Thanks! Great work so far!

**Comment by danielalexis** [comment]
> @danielalexis I get the following error: C:\Users\Username.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory
> I can compile if I copy "pins_arduino.h" to the folder but I don´t know, if it is the correct file. Maybe you can add the file to your branch? Thanks! Great work so far!

Did you clone my repository? If so make sure you're on the right branch (MK3) because currently the default branch is one im working on to give more printers support (Like Ender 3).

On the platformio.ini you have to define the variant or it wont compile and will give the error!

**Comment by danielalexis** [comment]
> @danielalexis I get the following error: C:\Users\Username.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory
> I can compile if I copy "pins_arduino.h" to the folder but I don´t know, if it is the correct file. Maybe you can add the file to your branch? Thanks! Great work so far!

Also i would love to have some feedback to see if your printer crashes or the lcd doesnt work, etc...

**Comment by brinkeb** [comment]
@danielalexis  Yes, I´ve cloned your repository and it´s the correct branch (MK3). Still get error message "pins_arduino.h: No such file or directory". Can you point me to the correct file "pins_arduino.h"? Of course I´ll give feedback if it works or if I have issues. THX!

**Comment by danielalexis** [comment]
> @danielalexis  Yes, I´ve cloned your repository and it´s the correct branch (MK3). Still get error message "pins_arduino.h: No such file or directory". Can you point me to the correct file "pins_arduino.h"? Of course I´ll give feedback if it works or if I have issues. THX!

Make sure your `platformio.ini` file has the following:
```

[platformio]
src_dir = Firmware
default_envs = prusa_rambo
build_dir = build/ 

[env:prusa_rambo]
platform = atmelavr
board = prusa_rambo
framework = arduino
board_build.variant = prusa_einsy_rambo 
build_flags = -w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections
```

The line that fixes your error is:
 `board_build.variant = prusa_einsy_rambo`

**Comment by brinkeb** [comment]
@danielalexis  Error is not fixed, sorry. I can copy and paste "pins_arduino.h" to the folder but since I have about 50 files named "pins_arduino.h" on my harddisk I don´t know what´s the correct one.

**Comment by danielalexis** [comment]
Currently Im not at a computer.
But on the meantime can you post the entirety of the logs into a file and upload it here?

**Comment by brinkeb** [comment]
> Executing task: C:\Users\Bernd Brinkert\.platformio\penv\Scripts\platformio.exe run <


Processing prusa_rambo (platform: atmelavr; board: prusa_rambo; framework: arduino)
-------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/prusa_rambo.html
PLATFORM: Atmel AVR 2.0.0 > Prusa RAMBo
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 252KB Flash
PACKAGES:
 - framework-arduino-avr-prusa_rambo 1.0.1      
 - toolchain-atmelavr 1.50400.190710 (5.4.0)
Converting Firmware.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling build\prusa_rambo\src\BlinkM.cpp.o
Compiling build\prusa_rambo\src\ConfigurationStore.cpp.o
Compiling build\prusa_rambo\src\Dcodes.cpp.o
Compiling build\prusa_rambo\src\Firmware.ino.cpp.o
Compiling build\prusa_rambo\src\MarlinSerial.cpp.o
Compiling build\prusa_rambo\src\Marlin_main.cpp.o
Compiling build\prusa_rambo\src\Sd2Card.cpp.o
Compiling build\prusa_rambo\src\SdBaseFile.cpp.o
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\BlinkM.cpp:5:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\ConfigurationStore.cpp:3:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\cmdqueue.h:4,
                 from Firmware\Dcodes.cpp:5:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\MarlinSerial.cpp:23:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
In file included from C:\Users\BERNDB~1\AppData\Local\Temp\tmpkqu1kcfb:1:0:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
*** [build\prusa_rambo\src\ConfigurationStore.cpp.o] Error 1
*** [build\prusa_rambo\src\BlinkM.cpp.o] Error 1
*** [build\prusa_rambo\src\Dcodes.cpp.o] Error 1
*** [build\prusa_rambo\src\Firmware.ino.cpp.o] Error 1
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\Marlin_main.cpp:48:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\Sd2Card.cpp:20:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
*** [build\prusa_rambo\src\MarlinSerial.cpp.o] Error 1
*** [build\prusa_rambo\src\Marlin_main.cpp.o] Error 1
*** [build\prusa_rambo\src\Sd2Card.cpp.o] Error 1
In file included from Firmware\system_timer.h:6:0,
                 from Firmware\Marlin.h:19,
                 from Firmware\SdBaseFile.cpp:21:
C:\Users\Bernd Brinkert\.platformio\packages\framework-arduino-avr-prusa_rambo\cores\prusa_rambo/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory

**********************************************************************
* Looking for pins_arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pins_arduino.h"
* Web  > https://platformio.org/lib/search?query=header:pins_arduino.h
*
**********************************************************************

compilation terminated.
*** [build\prusa_rambo\src\SdBaseFile.cpp.o] Error 1
================================== [FAILED] Took 0.81 seconds ==================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by danielalexis** [comment]
It must be a problem with your Installation. I've compiled sucessfully and Travis C.I. also compiles sucessfully.
Can you please reinstall your PlatformIO?

**Comment by brinkeb** [comment]
Actually the easiest way is to copy the missing file into the folder. Do you have a github- link or weblink to the correct file "pins_arduino.h"? THX

**Comment by danielalexis** [comment]
The file is suppose to come with PlatformIO, só your Installation must be
broken




A sábado, 27/06/2020, 11:57, brinkeb <notifications@github.com> escreveu:

**Comment by danielalexis** [comment]
@brinkeb I just cloned the repo and it compiled sucessfully without issues, it must be your PlatformIO installation. Repeat the steps on my README.md

**Comment by brinkeb** [comment]
@danielalexis  I´ll do a new installation of platform.io on a different PC/ Notebook tomorrow. I´ll give feedback.

**Comment by brinkeb** [comment]
@danielalexis  Works with new installation of platform.io on my other notebook now. I will flash the hexfile to the printer later and give feedback. Thanx for the help!

**Comment by danielalexis** [comment]
> @danielalexis Works with new installation of platform.io on my other notebook now. I will flash the hexfile to the printer later and give feedback. Thanx for the help!

Ok, nce. Is everything going ok with the printer?

**Comment by brinkeb** [comment]
@danielalexis  I can flash the hexfile via pruslicer without problems. But LCD shows only senseless stuff or crashes. Tested with Zaribo 320 MK3s and Firmware 3.9.0. Tested with OLED display and stock display.
lcd

**Comment by danielalexis** [comment]
> @danielalexis I can flash the hexfile via pruslicer without problems. But LCD shows only senseless stuff or crashes. Tested with Zaribo 320 MK3s and Firmware 3.9.0. Tested with OLED display and stock display.
> lcd

It seems it has the same error has the newer arduino IDE's. I go trough the LCD code and see what could be causing it

**Comment by danielalexis** [comment]
I have been looking and cant seem to figure out what it is, i've also searched online and found people with similar problems, theire problems were due to pins conflicts.
Maybe we should contact the Marlin Team to see how they did it with their firmware.
Since this was the main problem with the newer Arduino IDE's if we get a fix not only PlatformIO will get compatiblity but also the newer Arduino IDE's!

**Comment by brinkeb** [comment]
@danielalexis  I´ll try to compile again this evening and I´ll set set LANG_MODE to 0 in "Firmware/config.h". Maybe worth a try.

**Comment by brinkeb** [comment]
@danielalexis  Setting LANG_MODE to 0 in config.h solved the problem. LCD is working without issues now (even OLED). First print (xyz cube) looks good.

**Comment by danielalexis** [comment]
> @danielalexis Setting LANG_MODE to 0 in config.h solved the problem. LCD is working without issues now (even OLED). First print (xyz cube) looks good.

Cool, i've updated the file so the lcd is now fixed!

**Comment by danielalexis** [comment]
> Ups, i was just keeping my branch up-to-date.
> On another note, if this ends up merged which Travis CI tests should stay, the ones I designed or the ones already on the repo?

@3d-gussner @leptun @DRracer any updates on this?

**Comment by danielalexis** [comment]
Can we get any update on this?

Also @brinkeb how's the printer doing?

**Comment by brinkeb** [comment]
@danielalexis  everything works fine so far. No issues with firmware 3.9.0. Waiting for firmware 3.9.1 now.

**Comment by danielalexis** [comment]
I'll be closing this issue but will still provide updates from time to time on my repo!

**Pull request closed without merging**
