### PR TITLE
Add a threshold distance to Z calibration

### PR DESCRIPTION
**Pull request by Eriobis**
Allow a distance threshold when Z calibration is finding the bed

### CODE REVIEW

**Comment by leptun** [comment]
Umm... @Eriobis I don't see how your changes affect anything in the firmware. `HOME_Z_SEARCH_THRESHOLD` isn't used anywhere.

**Comment by Eriobis** [comment]
> Umm... @Eriobis I don't see how your changes affect anything in the firmware. `HOME_Z_SEARCH_THRESHOLD` isn't used anywhere.

Yeah ... while fixing the commit I omitted the part of the code that works with that ... I'll push a fix

**Comment by DRracer** [comment]
@Eriobis thank you for your PR.
@leptun good catch, I was wondering where should the new constants be used in the code. Now it makes sense. May be we could save some cycles (and code size) if the coordinates weren't compared as floats.

**Comment by Eriobis** [comment]
I didn't want to go with a big threshold, but it make sens to have a +/-1mm threshold and only use integers.
Even at 4mm I don't think the nozzle could touch the bed and damage something. The goal here, if i'm not mistaken, is only to make sure the probe works before moving and damaging the bed.

I'm sorry I don't have time to take a deeper look at this issue, I just found really odd that my printer was failing calibration after my mk2.5 upgrade and that I've been printing for >2 years without any issue :P.

**Comment by DRracer** [comment]
@Eriobis thats ok, we'll look into it ;)

**Review by MRprusa3d — APPROVED** [review]

**Pull request merged**
