### PR TITLE
remove unused swspi

### PR DESCRIPTION
**Pull request by craiglink**
these files aren't used for any builds

### CODE REVIEW

**Comment by MRprusa3d** [comment]
... software SPI library is needed for some future usage ...

**Comment by craiglink** [comment]
The code doesn’t even compile because of some syntax errors. If it’s going to stick around, those should be fixed

**Comment by MRprusa3d** [comment]
... we have now corrected (yet unpublished) version - see "PAT9130" PR for example ...

**Comment by DRracer** [comment]
@craiglink would you mind closing this PR?

**Pull request closed without merging**
