### PR TITLE
fix pio build

### PR DESCRIPTION
**Pull request by bgiot**
Fix UI issue when building firmware 3.8.0 with pio

### CODE REVIEW

**Comment by leptun** [comment]
@bgiot Are all thesw formatting changes necessary? It will break any lcd related PRs that are not merged yet and are planned for 3.9. Did you try #2181? I find these PRs simmilar, except the fact that mine also fixes some warnings and yours fixes formatting. I’d prefer if formatting was fixed last, functionality being a priority.

@DRracer do you agree?

**Comment by bgiot** [comment]
Sorry, formatting done automatically by editor...

**Comment by cimoalpacino** [comment]
As far as i can tell, the only change is in function lcd_putchar. Instead of being declared as void it's now int.

**Comment by leptun** [comment]
A fix has been merged. You can close this PR now.

**Comment by DRracer** [comment]
@leptun you are so fast, I was about to write the same ;)

**Comment by DRracer** [comment]
@bgiot anyway, thanks for reporting and giving a PR ;)

**Comment by bgiot** [comment]
Thanks all!

**Pull request closed without merging**
