### PR TITLE
Ignore, accidentally PR'd to wrong repo

### PR DESCRIPTION
**Pull request by PaulGD03**

### CODE REVIEW

**Comment by PaulGD03** [comment]
Sorry I wanted to push this into my Repo, not the main haha

**Comment by leptun** [comment]
It’s nice to see that you use so many of my PRs. :)

**Comment by PaulGD03** [comment]
> It’s nice to see that you use so many of my PRs. :)

I'm too impatient to wait for your work to get pushed into the head repo haha ^^

**Comment by leptun** [comment]
@PaulGameDev you forgot to update EEPROM_LAST_ITEM with the BearCalibration mode. Also I see that you are trying to read the stored eeprom value when declaring the global variable for bearMode calibration. You should declare it with a value of 0 and then read the value from eeprom during setup(). Also I’m not sure how you planned to toggle the value. Have a look at how the mmu stealth mode is implemented or rPI port toggle. It’s primarly found in ultralcd.cpp, but you can also find them in other files.

Or even better, have a look at how I did the backlight toggle mode.

**Comment by leptun** [comment]
Also did you update the build environment with the required changes for the tone reintroduction? You can find the info in my PR.

**Comment by PaulGD03** [comment]
> @PaulGameDev you forgot to update EEPROM_LAST_ITEM with the BearCalibration mode. Also I see that you are trying to read the stored eeprom value when declaring the global variable for bearMode calibration. You should declare it with a value of 0 and then read the value from eeprom during setup(). Also I’m not sure how you planned to toggle the value. Have a look at how the mmu stealth mode is implemented or rPI port toggle. It’s primarly found in ultralcd.cpp, but you can also find them in other files.
> 
> Or even better, have a look at how I did the backlight toggle mode.

Ah yea, I'm currently trying to redo it in a better way, thanks for the tips.



> Also did you update the build environment with the required changes for the tone reintroduction? You can find the info in my PR.

https://github.com/PaulGameDev/Arduino_Boards includes the neccesary changes ^^

**Comment by 3d-gussner** [comment]
@PaulGameDev What have changed in the Arduino Boards?
https://github.com/prusa3d/Arduino_Boards/compare/master...leptun:master ?

Checkout my https://github.com/3d-gussner/Arduino_Boards/tree/V1.0.2 it is ready for PR and as soon @leptun Tone https://github.com/prusa3d/Prusa-Firmware/pull/2149 will be implemented I will add it as well. It is planed for FW3.9

**Comment by PaulGD03** [comment]
> @PaulGameDev What have changed in the Arduino Boards?
> [prusa3d/Arduino_Boards@master...leptun:master](https://github.com/prusa3d/Arduino_Boards/compare/master...leptun:master) ?
> 
> Checkout my https://github.com/3d-gussner/Arduino_Boards/tree/V1.0.2 it is ready for PR and as soon @leptun Tone #2149 will be implemented I will add it as well. It is planed for FW3.9

Yea, I changed the timer2 to timer4 like leptun, but for some reason the arduino ide didn't want to install leptun's repo, so I redid it for myself. I'll definitely checkout your V1.0.2, but currently the modifications I did to my repo work just fine with the changes I have made to my arduino_boards fork ^^

**Pull request closed without merging**
