### PR TITLE
Fixing some typos. Semantic issues

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@kant The LCD has a Japanese character ROM and so can't display special chars like ä,ö,ü,β,ì,í,á and so on. So I guess the chances are low get this pull request merged.

**Comment by kant** [comment]
Understood. Kudos, anyway!

**Comment by 3d-gussner** [comment]
@kant  Long time no update here. Can you please close this PR?

**Comment by kant** [comment]
Closed at your request!

**Pull request closed without merging**
