### PR TITLE
⚡️🐛🚧New pinda temperature drift calibration

### LINKED ISSUE #2121: [3.8.0-RC1 MK3S] - automatic temp cal. goes on forever
### Issue
After updating printer, before anything else, a temperature calibration was started. Knowing it would take a while I left the printer and heard the beep. When returning the printer was still doing step 6/6 and went on for about 30 min before i shut it down.

### HW
MK3S MMU2S

### PR DESCRIPTION
**Pull request by leptun**
This is an updated implementation of the New temperature calibration that can be found here: #552
Fixes #2121

### CODE REVIEW

**Comment by vintagepc** [comment]
Perhaps I'm biased but this seems like a nice opportunity to include #2203 if temp compensation is becoming more meaningful :-)

**Comment by leptun** [comment]
@vintagepc
The UI is planned to be improved a lot (anyway, by me ;) ).
The only reason for this PR is that on some testing printers the calibration lasted 24h... Since it needed improvements, why not update that old PR? The implementation is both superior to the current design and it uses less resources (flash/sram).
Me and @3d-gussner did tests on this PR yesterday and we will publish our results here once we finish.

If you do any kind of testing, would you mind posting your results here? This way we can identify and fix any flaw we can find. I tried to keep the transition to this PR and back (downgrade) as smooth as possible for the end user, so if you find any way of breaking something really bad, please report.

**Comment by vintagepc** [comment]
I recall seeing complaints for folks where it just never finished because the PINDA never heated up to temp.... but that's probably a tangential issue. My near future is pretty booked up at the moment (doing adhesion testing on PC sheets) so I can't really make any changes that knowingly alter Z behaviour/MBL etc. 
If this is still open when I finish that I may be able to commit some time to testing it.

**Comment by leptun** [comment]
Yes, that’s one of the aims of this PR.
The old temperature calibration data should be unaltered and you can just return to the old firmware without any other change.
There’s no need to rush on your part. There will probably be a few more weeks before this is merged. Any feedback is appreciated ;)

**Comment by vintagepc** [comment]
👍 Heh... I could use a second printer for tinkering and debugging... but I'd rather save the $750 for when the XL gets released... 💸

**Comment by leptun** [comment]
I’m also waiting for the XL to get released. I’m so excited that Prusa finally releases a CoreXY machine.

**Comment by vintagepc** [comment]
I'm ready... but I'm pretty sure my wallet is not. XD 
_*wonders whom he has to get friendly with to join the public beta testing crowd*_

**Comment by leptun** [comment]
I don’t think you would receive one unless you worked on the 32bit fw. Anyway, that’s what I think they would do.

**Comment by vintagepc** [comment]
Quite possible, though for the Mini I think they just picked pre-orders of a few well known members. I have the skills as I do this sort of stuff in my day job, (but no Mini either)  We shall see what the future brings... (and I'll stop derailing this PR 😆 )

**Comment by 3d-gussner** [comment]
Here some tests and results:

### Tests
- Test in office with temp around 21°C with factory reset MK3s and MK3 3.9.0-RC1-3272 Commit Hash: 0b1358ec before this PR
```
SENDING:M861 ?
PINDA cal status: 1
index, temp, ustep, um
n/a, 35, 0, 0.00
0, 40, 0, 0.00
1, 45, 0, 0.00
2, 50, 0, 0.00
3, 55, 0, 0.00
4, 60, 0, 0.00
```
```
SENDING:G75
40  0.0041  0.0042  0.0043  0.0044  0.0045  0.0046  0.0047  0.0048  0.0049  0.0050  0.0051  0.0052  0.0053  0.0054  0.0055  0.0056  0.0057  0.0058  0.0059  0.0060  0.0061  0.0062  0.0063  0.0064  0.0065  0.0066  0.0067  0.0068  0.0069  0.0070  0.0071  0.0072  0.0073  0.0074  0.0075  0.0076  0.0077  0.0078  0.0079  0.0080  0.0081  0.0082  0.0083  0.0084  0.0085  0.0086  0.0087  0.0088  0.0089  0.0090  0.0091  0.0092  0.0093  0.0094  0.0095  0.0096  0.0097  0.0098  0.0099  0.00100  0.00101  0.00102  0.00103  0.00104  0.00105  0.00106  0.00107  0.00108  0.00109  0.00110  0.00ok
```
- Test in office with temp around 21°C with Mk3+PR2534  3.9.0-RC1-3273 Commit Hash: 976a2103

```
SENDING:G76
echo:Enqueing to the front: "G28 W0"
tmc2130_home_enter(axes_mask=0x04)
tmc2130_home_exit tmc2130_sg_homing_axes_mask=0x04
tmc2130_home_enter(axes_mask=0x01)
  0 step=13 mscnt= 222
tmc2130_home_exit tmc2130_sg_homing_axes_mask=0x01
tmc2130_home_enter(axes_mask=0x02)
echo:busy: processing
  0 step=33 mscnt= 543
tmc2130_home_exit tmc2130_sg_homing_axes_mask=0x02
echo:busy: processing
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
PINDA probe calibration start
PINDA temp(C):29.062500, Z position(um):130.000000
PINDA temp(C):35.041668, Z position(um):156.666670
PINDA temp(C):40.744484, Z position(um):169.166670
PINDA temp(C):46.562500, Z position(um):185.833330
PINDA temp(C):51.151318, Z position(um):187.500000
PINDA temp(C):55.906250, Z position(um):195.833330
PINDA temp(C):60.671875, Z position(um):211.666660
PINDA temp(C):64.825523, Z position(um):224.166670
Measurement finished, fit complete!
Quadratic coefficient(E-6 (um/K)):-15576.984000
Linear coefficient(E-6 (um/K)):3847598.800000
Temperature calibration done. Continue with pressing the knob.
```
```
SENDING:M861 ?
cal_active=1
cal_status=1
cal_version=1
temp_pinda=30C temp_shift=-52um
temp_pinda=35C temp_shift=-37um
temp_pinda=40C temp_shift=-24um
temp_pinda=45C temp_shift=-11um
temp_pinda=50C temp_shift=0um
temp_pinda=55C temp_shift=11um
temp_pinda=60C temp_shift=21um
temp_pinda=65C temp_shift=30um
temp_pinda=70C temp_shift=39um
temp_pinda=75C temp_shift=47um
temp_pinda=80C temp_shift=54um
temp_pinda=85C temp_shift=61um
temp_pinda=90C temp_shift=66um
temp_pinda=95C temp_shift=71um
temp_pinda=100C temp_shift=75um
temp_pinda=105C temp_shift=78um
temp_pinda=110C temp_shift=81um
```
```
SENDING:G75
40  -0.0241  -0.0242  -0.0243  -0.0244  -0.0145  -0.0146  -0.0147  -0.0148  -0.0049  -0.0050  0.0051  0.0052  0.0053  0.0154  0.0155  0.0156  0.0157  0.0258  0.0259  0.0260  0.0261  0.0262  0.0363  0.0364  0.0365  0.0366  0.0367  0.0368  0.0469  0.0470  0.0471  0.0472  0.0473  0.0474  0.0575  0.0576  0.0577  0.0578  0.0579  0.0580  0.0581  0.0682  0.0683  0.0684  0.0685  0.0686  0.0687  0.0688  0.0689  0.0790  0.0791  0.0792  0.0793  0.0794  0.0795  0.0796  0.0797  0.0798  0.0799  0.07100  0.08101  0.08102  0.08103  0.08104  0.08105  0.08106  0.08107  0.08108  0.08109  0.08110  0.08ok
```
1st_layer_cal_PINDA_37C
PINDA at 37°C
1st_layer_cal_PINDA_38C
PINDA at 38°C
1st_layer_cal_PINDA_43C
PINDA at 43°C

- Test in garage with temp around 16°C with Mk3+PR2534  3.9.0-RC1-3273 Commit Hash: 976a2103
```
SENDING:M861 ?
cal_active=1
cal_status=1
cal_version=1
temp_pinda=30C temp_shift=-14um
temp_pinda=35C temp_shift=-7um
temp_pinda=40C temp_shift=-3um
temp_pinda=45C temp_shift=0um
temp_pinda=50C temp_shift=0um
temp_pinda=55C temp_shift=-1um
temp_pinda=60C temp_shift=-4um
temp_pinda=65C temp_shift=-10um
temp_pinda=70C temp_shift=-17um
temp_pinda=75C temp_shift=-26um
temp_pinda=80C temp_shift=-37um
temp_pinda=85C temp_shift=-50um
temp_pinda=90C temp_shift=-66um
temp_pinda=95C temp_shift=-83um
temp_pinda=100C temp_shift=-102um
temp_pinda=105C temp_shift=-123um
temp_pinda=110C temp_shift=-146um
```
```
SENDING:G75
40  -0.0041  -0.0042  -0.0043  -0.0044  -0.0045  -0.0046  -0.0047  -0.0048  0.0049  0.0050  -0.0051  -0.0052  -0.0053  -0.0054  -0.0055  -0.0056  -0.0057  -0.0058  -0.0059  -0.0060  -0.0061  -0.0162  -0.0163  -0.0164  -0.0165  -0.0166  -0.0167  -0.0168  -0.0169  -0.0270  -0.0271  -0.0272  -0.0273  -0.0274  -0.0275  -0.0376  -0.0377  -0.0378  -0.0379  -0.0480  -0.0481  -0.0482  -0.0483  -0.0584  -0.0585  -0.0586  -0.0587  -0.0688  -0.0689  -0.0690  -0.0791  -0.0792  -0.0793  -0.0894  -0.0895  -0.0896  -0.0997  -0.0998  -0.0999  -0.10100  -0.10101  -0.11102  -0.11103  -0.11104  -0.12105  -0.12106  -0.13107  -0.13108  -0.14109  -0.14110  -0.15ok
```
1st_layer_cal_PINDA_19-20C
PINDA at 19-20°C

### Feedback
- During the test in the garage the nozzle scratch the bed in the beginning of the 1st layer calibration.
Nozzle_in_Bed_in garage
- Also the PINDA calibration struggled a lot while the garage door was open. After closing the door the test performed better.
- In the office ~21°C the PINDA calibration was going from 1/8 to 8/8 steps.
- In the garage ~16°C the PINDA calibration started with 1/8 to 8/8 but then added two additional tests 9/9 and 10/10
- The Z lift between the cool down was different 1st around 200mm and later it got lower and lower 9/9 somewhere around 5.75mm. This has been already fixed by @leptun .

- If looks like running the PINDA cal in warmer environment and later move it to a colder place generates some issues:
  - The layer height compensation isn't as good compared to hotter PINDA where the temp drift compensation worked fine
  - Still don't know how the scratch in the bed came, but as it happened after i moved the printer in the colder place, I tend to say that that was the reason.

Possible best practice: (Has to be tested and reviewed by others)
- Do the PINDA temp calibration in the coldest enviroment
- If your printer environment temperatures fluctuates during the seasons, re-run the PINDA temp cal when it gets colder.

**Comment by leptun** [comment]
I'm still confused how the bed scratch happened.

As for the "Raising and lower and lower Z" issue, this behavior is expected, but not to such an extent as to raising to 200mm. I fixed the behavior by constraining the output of the calculation that was generating the raise distance.

The "9/9" and "10/10" is expected. Normally, the calibration can only register 8 points, but sometimes it is possible to register more of them if conditions are good. This way the upper/lower range becomes more precise.

The cold environment might be an issue. It seems that the extrapolated values in that range are not precise enough. The only solutions I can think of are preheating the pinda in case it is too cold (this should be quite quick as the temperature difference would be high).
The real solution is making sure the user starts the calibration with the lowest pinda temperature they are going to use.
Calibrating in a cold environment and than using it in a hot one should not be a problem.

**Comment by 3d-gussner** [comment]
Maybe Prusa can test this PR in the freezer container they got ;-)

**Pull request closed without merging**
