### PR TITLE
Correctly show XFLASH initialization errors

### PR DESCRIPTION
**Pull request by wavexx**
Remove the first serial message, which cannot be displayed since serial
is not available yet.

Move both the serial message and display after
serial/temperature/planner is setup, so that we can use
lcd_show_fullscreen_message_and_wait_P properly.

### CODE REVIEW

**Review by leptun — APPROVED** [review]
The idea looks good, but I have some doubts about this claim:
> Remove the first serial message, which cannot be displayed since serial
is not available yet.

The serial should already be enabld at that point (see right above the xflash stuff). Below it is the farm mode exceptions which yes, do in fact reinitialize the serial port again, but I wouldn't consider that the end of the world. In any case, if everything works, then I don't have anything against this change.

**Comment by wavexx** [comment]
@3d-gussner can you test this? We should be able to simulate this with MK404

**Comment by 3d-gussner** [comment]
I will do tomorrow

**Comment by leptun** [comment]
Random question: where is the travis build?

**Comment by 3d-gussner** [comment]
> Random question: where is the travis build?

I had in the past similar issue that travis didn't run. I forced another change and reverted it, but that isn't ideal.
If I have PRs where travis fails, I create a fresh new worktree/branch and copy and commit the changes again. That worked for me at least few times.

**Review by 3d-gussner — APPROVED** [review]
Tested on MK404 (with simulated broken xflash) and the LCD warning message now waits for acknowledge with knob click. Before this PR the message disappears quite fast.    
The serial out put `XFLASH not responding` has been there before.
Also the the serial output generates `echo:busy: paused for user` to keep connection to host systems like Octoprint alive.

**Pull request merged**
