### PR TITLE
TM: PTC model support

### PR DESCRIPTION
**Pull request by wavexx**
This is a first attempt to support runtime PTC heating elements such as the Revo. There is no full calibration support yet.

We expose two existing model simulation parameters: the dampening filter and model lag as M310 "D" and "L" respectively, as they need to be tuned for a faster response. Besides parameter handling, there is no actual runtime cost to these.

As usual, to keep things fast we have to cheat. To actual PTC heating element has a quadratic response according to the datasheet, but we actually add just a new linear term to the power estimation:

2023-01-26T235657

The data above was actually carved out of the Revo datasheet image using "g3data" btw. 

It *should* be enough, and the values I got from the graph seem to match in behavior the logs we have on #3636. It defaults to an identity, so existing calibration data will work unchanged.

The new U/V/D/L parameters seem to be pretty consistent across samples, which is good.

Since the calibration doesn't handle the new terms yet it needs to be "primed" for the new values so that C/R can be done by the existing calibration function.

The starting values for the Revo Six seem to be `P40 U-0.0014 V1.05 D0.15 L270`.
With this in mind, it should be possible to test this by doing:

```
M310 S0 ; disable the model if hasn't been yet
M310 P40 U-0.0014 V1.05 D0.15 L270 ; set Revo parameters
M310 A F0 ; calibrate C/R
M310 S1 ; enable the model
```

**I wasn't able to test this on any hardware yet**. I'm only basing this on the sample logs, so I'm not sure if this works as it is or requires further tweaks. It's also unknown whether the existing warning/error threshold still make sense (from the logs they should still fall within range), since this needs a practical test.

### CODE REVIEW

**Comment by wavexx** [comment]
The following is a build for the MK3S of the above PR (in english only) for those that like bleeding edge untested software:

[FW3.13.0+6900-MK3S-EINSy10a_ENGLISH.zip](https://github.com/prusa3d/Prusa-Firmware/files/10514260/FW3.13.0%2B6900-MK3S-EINSy10a_ENGLISH.zip)

It is based on FW 3.13, so this *isn't* a stable release (notably, there's no working MMU in this build). If you want to test this, please bear in mind that you might need to reset the printer settings when going back to 3.12 or use any other version.

If you want to test this on a printer with a Revo, do the following:

- Start with the old FW loaded and disable the model if you didn't already (``M310 S0`` followed by ``M500``).
- Pre-cool the hotend to <35C to avoid potential warnings.
- Flash the new FW.
- Using a serial logger (octoprint with timestamps preferably), run in sequence:

```
M310 P40 U-0.0014 V1.05 D0.15 L270
M310 A F0
```

Until this point nothing should fail. Calibration should spit the updated model parameters. Please save the output log and attach it here when posting feedback.

Then, enable the model with `M310 S1`. Here's an initial check list:

- Preheat for PLA: does it warn/error out while heating?
- If ok, wait for at least 60 seconds at temperature. Errors?
- If ok, try cooling down and wait for <35C. Errors?

If the above is passing, you need to ensure the model still triggers as it should. Since the revo is shielded, you should use the wet q-tip method. Follow the instructions in: https://github.com/prusa3d/Prusa-Firmware/pull/3552 and count how many seconds it needs before (and if) it triggers. Don't burn the q-tip (use more water if you want to insist, but don't stay on the hotend for longer than 60s). We have no idea what should be the error thresholds there yet.

If it seems to work, you can save the current status with `M500` and try to print.

**Comment by ltlowe** [comment]
Is there benefit to trying theses commands on 3.12.1, or are your additional commits needed in order for it to function correctly?

**Comment by ltlowe** [comment]
Nevermind. I had a look and see that the test firmware is required for U,V,D, and L.
I would do some testing, but I have an MMU and don't want to go 3.12.1 -> 3.13  and back if settings need to be reset.

**Comment by plampix** [comment]
I'm willing to try this, but rather not reset my printer either if not needed. Is it possible to get a build that does support the MMU2?

**Comment by wavexx** [comment]
At this moment going from this and back to 3.12.1 doesn't require a reset (printer state should be unchanged).

**Comment by cnlson** [comment]
@wavexx > At this moment going from this and back to 3.12.1 doesn't require a reset (printer state should be unchanged).

ok, what about going back to 3.11? if i wouldn't need to reset i would do it. OR, do i need to upgrade to 12.1 give you the output from my revo, then upgrade to this to be able to downgrade without reset?

**Comment by wavexx** [comment]
> ok, what about going back to 3.11? if i wouldn't need to reset i would do it. OR, do i need to upgrade to 12.1 give you the output from my revo, then upgrade to this to be able to downgrade without reset?

This should also work right now. The problem when working with these betas can happen later when upgrading to something that doesn't exist right now, like 3.12.2 where there can be some new change where I'm currently storing the new settings. These new parameters are not set in stone yet. In that case the upgrade can be screwed and you should be prepared. I can't foresee changes in the future release, so this is why I'm putting a word of caution.

Note that if you're on linux we now have tools to save/restore the eeprom settings that would make this trivial, like:

````
# save all current settings
./tools/dump_eeprom /dev/ttyACM0 > settings-311.dump

# play around with any beta FW, than flash back the original

# restore the old settings
./tools/update_eeprom -f /dev/ttyACM0 settings-311.dump
````

These should also work on osx (untested), but I can't help to do the same on windows.

**Comment by cnlson** [comment]
> > ok, what about going back to 3.11? if i wouldn't need to reset i would do it. OR, do i need to upgrade to 12.1 give you the output from my revo, then upgrade to this to be able to downgrade without reset?
> 
> This should also work right now. The problem when working with these betas can happen later when upgrading to something that doesn't exist right now, like 3.12.2 where there can be some new change where I'm currently storing the new settings. These new parameters are not set in stone yet. In that case the upgrade can be screwed and you should be prepared. I can't foresee changes in the future release, so this is why I'm putting a word of caution.
> 
> Note that if you're on linux we now have tools to save/restore the eeprom settings that would make this trivial, like:
> 
> ```
> # save all current settings
> ./tools/dump_eeprom /dev/ttyACM0 > settings-311.dump
> 
> # play around with any beta FW, than flash back the original
> 
> # restore the old settings
> ./tools/update_eeprom -f /dev/ttyACM0 settings-311.dump

ok, so, before updating to a new release firmware, downgrade to 12.1? 
The printer is hooked up to a RPI running octoprint, is there a way to dump the eeprom settings to the pi's sd?

**Comment by wavexx** [comment]
> ok, so, before updating to a new release firmware, downgrade to 12.1?

That's not generally enough (12.1 will not magically erase the space of settings that doesn't know about).

> The printer is hooked up to a RPI running octoprint, is there a way to dump the eeprom settings to the pi's sd?

Not automatically at least. It's possible by using the `D3` gcode (that the scripts mentioned above are using), and would actually be nice to have some plugin for octoprint that does that, but I don't see anything that already exists.

**Comment by cnlson** [comment]
> 

@wavexx what would the gcode commands be?

**Comment by wavexx** [comment]
It's really not the best place to explain this. `D3` needs to be uppercase, but then to restore the settings you need a script to rewrite it again (https://github.com/prusa3d/Prusa-Firmware/blob/e39f2d132e7d0e63837698f494e9ff6a9bc604d8/tools/update_eeprom#L32)

**Comment by plampix** [comment]
[calibration.txt](https://github.com/prusa3d/Prusa-Firmware/files/10521636/calibration.txt)

Heat up to PLA :heavy_check_mark: 
Steady temp for > 60s :heavy_check_mark: 
Cool down < 35 :heavy_check_mark: 
Heat up to PETG :heavy_check_mark: 
Steady temp for > 60s :heavy_check_mark: 

Anomaly detected after 3 seconds with a wet q-tip, M112 triggered after 4 seconds.

**Comment by cnlson** [comment]
i just flashed the firmware and immediately forgot to do the terminal thing. so i got an error with a piercing beep.
reset
reconnected to octoprint, started the logging and did the commands you put above
it heated the hot end to 230 for some time and then turned on the fan
i am waiting to run the pla and other tests. 
right now it says tm cool down <50

i wish we could be chatting rather than posting back and forth. any suggestions? i don't have fb but i do have zoom on this computer

edit TM; refine c est
assuming time to test pla and other tests
Edit, nope back up to 230

**Comment by wavexx** [comment]
@plampix nice! Seems to trigger pretty fast, but that's not a bad thing. The next step is to print something then.

**Comment by plampix** [comment]
> @plampix nice! Seems to trigger pretty fast, but that's not a bad thing. The next step is to print something then.

Q-tip might have been a bit too wet. And my .6 nozzle doesn't have the silicone sock on it (ruined it due to some well known issues with the early heatercores). So changing nozzles at the moment will probably require a recalibration.

**Comment by cnlson** [comment]
Heat up to PLA ✔️
Steady temp for > 60s ✔️
Cool down < 35 ✔️
Heat up to PETG ✔️
Steady temp for > 60s ✔️
[calibration white thermister revo 6.txt](https://github.com/prusa3d/Prusa-Firmware/files/10521950/calibration.white.thermister.revo.6.txt)

anomaly was detected very quickly 1-3 seconds



i keep getting this error so i will be reverting to 3.11

> MMU NOT RESPONDING
> Prusa.io/04401
> FI:0 FS:1 F?
> 0230"
> >Reset MMU

i do not have an mmu btw

**Comment by plampix** [comment]
> anomaly was detected very quickly 1-3 seconds
> 
> i keep getting this error so i will be reverting to 3.11
> 
> > MMU NOT RESPONDING
> > Prusa.io/04401
> > FI:0 FS:1 F?
> > 0230"
> > > Reset MMU
> 
> i do not have an mmu btw

Hmm, weird. I do have one, and the first thing the firmware mentioned is I should update the MMU firmware. Then it asked me if I wanted to disable the MMU (probably a keep enabled option as well, though that didn't display correctly). I'll be staying on this firmware until I really need my MMU.

**Comment by wavexx** [comment]
Yeah FW 3.13 expects a new firmware which is not available yet. You can go to "Settings" and disable the MMU. Then the error will be gone.

**Comment by cnlson** [comment]
> 
@wavexx 
wierd, i don't recall that setting before and i don't have an mmu

12 minute print of petg completed no errors (other than the mmu one)

**Comment by cnlson** [comment]
@wavexx want to point out there are a lot more people who would do this if they did not lose all their settings. (jesus saves) So if you could either add that to the firmware to save settings to the sd (best option) or make a utility to do it (second best) or an octoprint plugin (not guaranteed to help everyone) you would have a lot more volunteers. 

sheet profiles and live z are i think the most important things. but there might be others.

**Comment by darraghbr** [comment]
Is working alright for me at the moment, no errors up until the q-tip test at which point it gave me an error in around 5 seconds.

I did get an MMU error, so I turned that off. 

[serialDB3p13.log](https://github.com/prusa3d/Prusa-Firmware/files/10522161/serialDB3p13.log)

I also printed most of a PETG Benchy with no issues or errors, please find attached the (extremely boring) log

[3DBenchy_PETG.log](https://github.com/prusa3d/Prusa-Firmware/files/10523264/3DBenchy_PETG.log)

**Comment by wavexx** [comment]
A plugin for octoprint would be awesome for saving the settings, but I have my hands dirty on sooo many projects I don't want to add another one to the pile right now :P - If there is *anyone* which has some experience with octoprint that could help here?

**Comment by cnlson** [comment]
> A plugin for octoprint would be awesome for saving the settings, but I have my hands dirty on sooo many projects I don't want to add another one to the pile right now :P - If there is _anyone_ which has some experience with octoprint that could help here?

if i had a vote it would be in the settings saving to the sd card that everyone has

**Comment by wavexx** [comment]
@cnlson I would tend to agree but we're pretty tight on space so every feature that we can offload allows us to merge some other more frequently needed feature, it's a constant fight

**Comment by plampix** [comment]
@wavexx Would be great to have that feature in PrusaSlicer though.

**Comment by wavexx** [comment]
@plampix yup, can you request it in a PrusaSlicer issue? Saving the settings before a FW upgrade makes a lot of sense to me.

**Comment by cnlson** [comment]
@wavexx Will you Post an updated beta with the warning rather than error for testing?

**Comment by alexiri** [comment]
All the tests passed! I disabled Octoprint's [`M112` response on error](https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1407006155) and the wet q-tip was detected in about 3 seconds (around 16:30:24). I then printed (starting at 16:32:38) for 1 hour with PLA and there were no errors at all (other than the MMU, which I forgot to disable).

[serial.log.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527769/serial.log.zip)

**Comment by wavexx** [comment]
Two more beta builds:

- FW 3.13: [FW3.13.0+6902-MK3S-EINSy10a_ENGLISH.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527851/FW3.13.0%2B6902-MK3S-EINSy10a_ENGLISH.zip)
- FW 3.12: [Firmware-3.12-ptc.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527852/Firmware-3.12-ptc.zip)

Both include the octoprint fix. The 3.12 should have functional MMU, but I didn't test it. The branch lives at https://github.com/wavexx/Prusa-Firmware/tree/tm_ptc312 for the moment.

**Comment by cnlson** [comment]
@wavexx any reason to choose 3.13 over 3.12 or vice versa?

**Comment by wavexx** [comment]
I do most of the development for the 3.13, then only move the change for 3.12 if necessary or when finished as it's essentially _double_ work. In this case I'm trying to get as much feedback as possible, so if you need the MMU, use 3.12, otherwise using 3.13 helps us for testing the next release as well.

**Comment by cnlson** [comment]
> I do most of the development for the 3.13, then only move the change for 3.12 if necessary or when finished as it's essentially _double_ work. In this case I'm trying to get as much feedback as possible, so if you need the MMU, use 3.12, otherwise using 3.13 helps us for testing the next release as well.

should move the download link to the beginning of the thread so people are not downloading the obsolete version

**Comment by cnlson** [comment]
> I do most of the development for the 3.13, then only move the change for 3.12 if necessary or when finished as it's essentially _double_ work. In this case I'm trying to get as much feedback as possible, so if you need the MMU, use 3.12, otherwise using 3.13 helps us for testing the next release as well.

it appears i must have to do the steps to enable the model again? right now i cannot even preheat without the scream of pain from the printer
[FW3.13.0+6902.txt](https://github.com/prusa3d/Prusa-Firmware/files/10532878/FW3.13.0%2B6902.txt)

edit added log from calibration for comparison with original [FW3.13.0+6902.txt](https://github.com/prusa3d/Prusa-Firmware/files/10532878/FW3.13.0%2B6902.txt)

has initial tm :errors also

**Comment by wavexx** [comment]
> it appears i must have to do the steps to enable the model again? right now i cannot even preheat without the scream of pain from the printer

Can you be more specific? You flashed 3.13.0-6902 and you get errors again?
Nothing should have changed between these two builds.

**Comment by cnlson** [comment]
@wavexx I had to do the calibration all over again and enable the new
model. It doesn't stick between firmware flashes
[serial.log](https://github.com/prusa3d/Prusa-Firmware/files/10540436/serial.log)

actually it seems like it did not stick between prints. I went to do a second print and got the tm errors again so i redid the calibration and enabled again and now it will print. 
[serial (1).log](https://github.com/prusa3d/Prusa-Firmware/files/10540445/serial.1.log)

**Comment by cnlson** [comment]
[serial (2).log](https://github.com/prusa3d/Prusa-Firmware/files/10542164/serial.2.log)
90 minute print

**Comment by ClarenceTK** [comment]
> Two more beta builds:
> 
> * FW 3.13: [FW3.13.0+6902-MK3S-EINSy10a_ENGLISH.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527851/FW3.13.0%2B6902-MK3S-EINSy10a_ENGLISH.zip)
> * FW 3.12: [Firmware-3.12-ptc.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527852/Firmware-3.12-ptc.zip)
> 
> Both include the octoprint fix. The 3.12 should have functional MMU, but I didn't test it. The branch lives at https://github.com/wavexx/Prusa-Firmware/tree/tm_ptc312 for the moment.

Tried to flash that updated firmware and it was fubared. Most likely have something to do with running a Mk2.5s. But just know it was tried.

**Comment by cnlson** [comment]
> > Two more beta builds:
> > 
> > * FW 3.13: [FW3.13.0+6902-MK3S-EINSy10a_ENGLISH.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527851/FW3.13.0%2B6902-MK3S-EINSy10a_ENGLISH.zip)
> > * FW 3.12: [Firmware-3.12-ptc.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527852/Firmware-3.12-ptc.zip)
> > 
> > Both include the octoprint fix. The 3.12 should have functional MMU, but I didn't test it. The branch lives at https://github.com/wavexx/Prusa-Firmware/tree/tm_ptc312 for the moment.
> 
> Tried to flash that updated firmware and it was fubared. Most likely have something to do with running a Mk2.5s. But just know it was tried.

Dude, the firmware says mk3 einsy. Hope you can recover your mk2

**Comment by ClarenceTK** [comment]
> > > Two more beta builds:
> > > 
> > > * FW 3.13: [FW3.13.0+6902-MK3S-EINSy10a_ENGLISH.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527851/FW3.13.0%2B6902-MK3S-EINSy10a_ENGLISH.zip)
> > > * FW 3.12: [Firmware-3.12-ptc.zip](https://github.com/prusa3d/Prusa-Firmware/files/10527852/Firmware-3.12-ptc.zip)
> > > 
> > > Both include the octoprint fix. The 3.12 should have functional MMU, but I didn't test it. The branch lives at https://github.com/wavexx/Prusa-Firmware/tree/tm_ptc312 for the moment.
> > 
> > 
> > Tried to flash that updated firmware and it was fubared. Most likely have something to do with running a Mk2.5s. But just know it was tried.
> 
> Dude, the firmware says mk3 einsy. Hope you can recover your mk2

Yeah I noticed that after rereading the change longs for the 5th time. on the MK2.5/S it does not have the thermal protection addition that they added in the MK3 lineup. Wish they would have made it a bit more clear that if you are a MK2.5 user you don't need to worry about the issues with thermal protection and the revo.

**Comment by cnlson** [comment]
@wavexx are we done?

**Comment by cnlson** [comment]
@wavexx @3d-gussner so today randomly after a print 45 minutes ago it is now thermal erroring again.

WTF is going on?

Send: N14 M104 S230*81
Recv: ok
Send: N15 M109 S230*93
Recv: LCD status changed
Recv: T:53.8 E:0 W:?
Recv: T:53.9 /230.0 B:21.8 /0.0 T0:53.9 /230.0 @:127 B@:0 P:0.0 A:28.4
Recv: echo:busy: processing
Recv: T:54.1 E:0 W:?
Recv: T:56.9 E:0 W:?
Recv: TM: error |-2.110583|>1.200000
Recv: LCD status changed
Recv: TM: error triggered!
Recv: LCD status changed
Recv: ok
Send: N16 G1 E-18 F2100*59
Recv: echo:enqueing "G1 E-1.000 F2700"
Recv: // action:paused
Printer signalled that it paused, switching state...
Changing monitoring state from "Printing" to "Pausing"
Recv: echo:Printer stopped due to errors. Supervision required.
Recv: T:59.4 /0.0 B:21.9 /0.0 T0:59.4 /0.0 @:0 B@:0 P:0.0 A:29.4
Recv: TM: error |-3.779521|>1.200000
Recv: echo:busy: processing
Recv: TM: error |-5.762495|>1.200000
Recv: T:61.8 E:0 W:2
Recv: TM: error |-8.041177|>1.200000
Recv: TM: error |-10.593581|>1.200000
Recv: TM: error |-13.404225|>1.200000
Recv: T:65.6 E:0 W:3
Recv: TM: error |-16.427269|>1.200000
Recv: TM: error |-19.669659|>1.200000
Recv: T:67.7 /0.0 B:22.1 /0.0 T0:67.7 /0.0 @:0 B@:0 P:0.0 A:28.6
Recv: TM: error |-23.111900|>1.200000
Recv: TM: error |-26.108120|>1.200000
Recv: echo:busy: processing
Recv: T:69.1 E:0 W:3
Recv: TM: error |-28.692501|>1.200000
Recv: TM: error |-30.913324|>1.200000
Recv: TM: error |-32.806889|>1.200000
Recv: TM: error |-34.394077|>1.200000
Recv: T:70.5 E:0 W:2
Recv: TM: error |-35.701725|>1.200000
Recv: TM: error |-36.756023|>1.200000
Recv: T:70.7 /0.0 B:22.1 /0.0 T0:70.7 /0.0 @:0 B@:0 P:0.0 A:28.5
Recv: TM: error |-37.571163|>1.200000
Recv: echo:busy: processing
Recv: T:70.8 E:0 W:3
Recv: TM: error |-38.195660|>1.200000
Recv: TM: error |-38.616123|>1.200000
Recv: TM: error |-38.871277|>1.200000
Recv: TM: error |-38.977650|>1.200000
Recv: T:70.5 E:0 W:3
Recv: TM: error |-38.950317|>1.200000
Recv: TM: error |-38.807884|>1.200000
Recv: T:70.2 /0.0 B:22.0 /0.0 T0:70.2 /0.0 @:0 B@:0 P:0.0 A:28.7
Recv: TM: error |-38.539749|>1.200000
Recv: TM: error |-38.208046|>1.200000
Recv: echo:busy: processing
Recv: T:69.8 E:0 W:3
Recv: TM: error |-37.765190|>1.200000
Recv: TM: error |-37.267902|>1.200000
Recv: TM: error |-36.702702|>1.200000
Recv: TM: error |-36.078777|>1.200000
Recv: T:69.1 E:0 W:3
Recv: TM: error |-35.417542|>1.200000
Recv: TM: error |-34.710991|>1.200000
Recv: T:68.7 /0.0 B:22.0 /0.0 T0:68.7 /0.0 @:0 B@:0 P:0.0 A:28.5
Recv: TM: error |-33.969852|>1.200000
Recv: echo:busy: processing
Recv: T:68.5 E:0 W:2
Recv: TM: error |-33.205891|>1.200000
Recv: TM: error |-32.409451|>1.200000
Recv: TM: error |-31.614027|>1.200000
Recv: TM: error |-30.789585|>1.200000
Recv: T:67.7 E:0 W:3
Recv: TM: error |-29.963371|>1.200000
Recv: TM: error |-29.127430|>1.200000
Recv: T:67.4 /0.0 B:22.0 /0.0 T0:67.4 /0.0 @:0 B@:0 P:0.0 A:28.4
Recv: TM: error |-28.296410|>1.200000
Recv: TM: error |-27.463495|>1.200000
Recv: echo:busy: processing
Recv: T:67.0 E:0 W:3
Recv: TM: error |-26.636980|>1.200000
Recv: TM: error |-25.818945|>1.200000
Recv: TM: error |-25.007494|>1.200000
Recv: T:66.5 E:0 W:2
Recv: TM: error |-24.200680|>1.200000
Recv: TM: error |-23.409590|>1.200000
Recv: T:66.2 /0.0 B:22.0 /0.0 T0:66.2 /0.0 @:0 B@:0 P:0.0 A:28.4
Recv: TM: error |-22.631542|>1.200000
Recv: TM: error |-21.863886|>1.200000
Recv: echo:busy: processing
Recv: T:65.9 E:0 W:2
Recv: TM: error |-21.115183|>1.200000
Recv: TM: error |-20.376661|>1.200000
Recv: TM: error |-19.647364|>1.200000
Recv: TM: error |-18.939344|>1.200000
Recv: T:65.4 E:0 W:3
Recv: TM: error |-18.258366|>1.200000
Recv: TM: error |-17.589294|>1.200000
Recv: T:65.1 /0.0 B:22.1 /0.0 T0:65.1 /0.0 @:0 B@:0 P:0.0 A:28.4
Recv: TM: error |-16.941959|>1.200000
Recv: echo:busy: processing
Recv: TM: error |-16.293875|>1.200000
Recv: T:64.9 E:0 W:3
Recv: TM: error |-15.690823|>1.200000
Recv: TM: error |-15.090359|>1.200000
Recv: TM: error |-14.496919|>1.200000
Recv: T:64.6 E:0 W:2
Recv: TM: error |-13.950120|>1.200000
Recv: TM: error |-13.399820|>1.200000
Recv: T:64.3 /0.0 B:22.0 /0.0 T0:64.3 /0.0 @:0 B@:0 P:0.0 A:28.7
Recv: TM: error |-12.874864|>1.200000
Recv: TM: error |-12.365285|>1.200000
Recv: echo:busy: processing
Recv: T:64.0 E:0 W:3
Recv: TM: error |-11.863434|>1.200000
Recv: TM: error |-11.388146|>1.200000
Recv: TM: error |-10.931143|>1.200000
Recv: TM: error |-10.482646|>1.200000
Recv: T:63.6 E:0 W:2
Recv: TM: error |-10.053890|>1.200000
Recv: TM: error |-9.648043|>1.200000
Recv: T:63.3 /0.0 B:22.0 /0.0 T0:63.3 /0.0 @:0 B@:0 P:0.0 A:28.5
Recv: // action:cancel
Cancelling on request of the printer...
Changing monitoring state from "Pausing" to "Cancelling"
Recv: TM: error |-9.234482|>1.200000
Recv: TM: error triggered!
Recv: // action:cancel
Cancelling on request of the printer...
Recv: echo:Printer stopped due to errors. Supervision required.
Recv: tmc2130_home_enter(axes_mask=0x04)
Recv: TM: error |-8.858766|>1.200000
Recv: TM: error |-8.487606|>1.200000
Recv: TM: error |-8.128561|>1.200000
Recv: TM: error |-7.785053|>1.200000
Recv: tmc2130_home_exit tmc2130_sg_homing_axes_mask=0x04
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: N17 M108*28
Recv: Error:Line Number is not Last Line Number+1, Last Line: 15
Recv: Resend: 16
Recv: ok
Send: N16 G1 E-18 F2100*59
Recv: TM: error |-7.450989|>1.200000
Recv: TM: error |-7.139234|>1.200000
Recv: T:62.7 /0.0 B:22.0 /0.0 T0:62.7 /0.0 @:0 B@:0 P:0.0 A:28.6
Recv: TM: error |-6.820910|>1.200000
Recv: echo:busy: paused for user
Recv: TM: error |-6.522707|>1.200000
Recv: TM: error |-6.251309|>1.200000
Recv: TM: error |-5.981305|>1.200000
Recv: TM: error |-5.716547|>1.200000
Recv: TM: error |-5.475611|>1.200000
Recv: TM: error |-5.235071|>1.200000
Recv: TM: error |-4.993198|>1.200000
Recv: T:62.0 /0.0 B:22.1 /0.0 T0:62.0 /0.0 @:0 B@:0 P:0.0 A:28.7
Recv: TM: error |-4.785664|>1.200000
Recv: echo:busy: paused for user
Recv: TM: error |-4.564221|>1.200000
Recv: TM: error |-4.359557|>1.200000
Recv: TM: error |-4.170949|>1.200000
Recv: TM: error |-3.988371|>1.200000
Recv: TM: error |-3.806025|>1.200000
Recv: TM: error |-3.633328|>1.200000
Recv: T:61.3 /0.0 B:22.0 /0.0 T0:61.3 /0.0 @:0 B@:0 P:0.0 A:28.5
Recv: TM: error |-3.469889|>1.200000
Recv: echo:busy: paused for user
Recv: TM: error |-3.317196|>1.200000
Recv: TM: error |-3.172922|>1.200000
Recv: TM: error |-3.025515|>1.200000
Recv: TM: error |-2.877065|>1.200000
Recv: TM: error |-2.746356|>1.200000
Recv: TM: error |-2.623224|>1.200000
Recv: T:60.7 /0.0 B:22.0 /0.0 T0:60.7 /0.0 @:0 B@:0 P:0.0 A:28.4
Recv: TM: error |-2.511083|>1.200000
Recv: echo:busy: paused for user
Recv: TM: error |-2.392634|>1.200000
Recv: TM: error |-2.281311|>1.200000
Recv: TM: error |-2.167473|>1.200000
Recv: TM: error |-2.071818|>1.200000
Recv: TM: error |-1.982274|>1.200000
Recv: TM: error |-1.885503|>1.200000
Recv: TM: error |-1.789369|>1.200000
Recv: T:60.0 /0.0 B:22.0 /0.0 T0:60.0 /0.0 @:0 B@:0 P:0.0 A:28.5
Recv: TM: error |-1.715773|>1.200000
Recv: TM: error cleared
Recv: echo:busy: paused for user
Recv: TM: error |-1.644800|>1.200000
Recv: TM: error |-1.556575|>1.200000
Recv: TM: error |-1.479223|>1.200000
Recv: TM: error |-1.419032|>1.200000
Recv: TM: error |-1.359280|>1.200000
Recv: TM: error |-1.295428|>1.200000
Recv: T:59.3 /0.0 B:22.0 /0.0 T0:59.3 /0.0 @:0 B@:0 P:0.0 A:28.6
Recv: TM: error |-1.225430|>1.200000
Recv: // action:cancel
Cancelling on request of the printer...
Recv: tmc2130_home_enter(axes_mask=0x04)
Recv: TM: error |-1.225430|>1.200000
Recv: tmc2130_home_exit tmc2130_sg_homing_axes_mask=0x04
Communication timeout during an active resend, resending same line again to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.

**Comment by cnlson** [comment]
@wavexx @3d-gussner what do i need to do to get your attention?

**Comment by 3d-gussner** [comment]
Sorry, we may not be able to react as fast as we want all the time.

**Comment by 3d-gussner** [comment]
We really appreciate the help of the community and really try hard to get E3d Revo supported. Please keep in mind that we try to support a 3rd party product and this isn't an easy task to do, it takes time, some effort and of course the help of the community.
The thermal model for the v6 have been tested on tons of printers internally, but we don't have all kind of mods and just cannot test all combinations the community has.

**Comment by wavexx** [comment]
@cnlson sorry about the slow reply, but wasn't able to get to this in the last few days. Regarding your failed print: can you post the gcode used and the model (3mf if possible) used to slice it?

Since you have octoprint attached, what you can do that would help tremendously is to log the entire print by adding:

```
M310
M155 S1 C3
D70 S1
```

as your start gcode and print with this all the time. If you get an error, you can then attach the entire serial log (which can be quite large), the gcode and the model and we can analyze in detail what went wrong. For example, it would be useful to know if re-printing the same stuff results in the same error at the 40min mark?

**Comment by cnlson** [comment]
> @cnlson sorry about the slow reply, but wasn't able to get to this in the last few days. Regarding your failed print: can you post the gcode used and the model (3mf if possible) used to slice it?
> 
> Since you have octoprint attached, what you can do that would help tremendously is to log the entire print by adding:
> 
> ```
> M310
> M155 S1 C3
> D70 S1
> ```
> 
> as your start gcode and print with this all the time. If you get an error, you can then attach the entire serial log (which can be quite large), the gcode and the model and we can analyze in detail what went wrong. For example, it would be useful to know if re-printing the same stuff results in the same error at the 40min mark?
@3d-gussner I'm not looking for concierge service, but I'm reporting an issue. It appears that when you create and enable a profile for the revo it sticks only for a random amount of time before it reverts and tm errors again. In the example above I printed without error, then 30 minutes later I went to preheat to change filament and it immediately errored. So something is causing the calibration to be discarded at random intervals. I've had it happen 3 times so far

**Comment by cnlson** [comment]
fark.... i missed the last line. m500. ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh. 
i am my own worst enemy. I will rerun calibration, enable it, and then save it.

<pounding head on desk emoji>

**Comment by cnlson** [comment]
Once applying m500 no more intermittent tm errors

**Review by DRracer — APPROVED** [review]

**Comment by Morcegolas** [comment]
@wavexx the commands M310 is to run inside Octoprint? I’m considering upgrading to Revo because I change nozzles a lot and need to change my HotEnd but I found this problem related to the new firmware.

**Comment by wavexx** [comment]
@Morcegolas yes. Note that this change hasn't been published in any official release yet, however it has been merged for the next release.

With this change, you'll still have to run this gcode to setup the printer:

```
M310 S0 ; disable the model if hasn't been yet
M310 P40 U-0.0014 V1.05 D0.15 L270 ; set Revo parameters
M310 A F0 ; calibrate C/R
M310 S1 ; enable the model
M500 ; save
````

**Pull request merged**
