### PR TITLE
Added German/Deutsch and Dutch/Nederlands and FIX

### PR DESCRIPTION
**Pull request by 3d-gussner**
- Added German and Dutch languages, to make it easier to non-english speaking persons, especially kids, to operate the MK2.
- Fixed compiling issue with new 3.0.3.10RC1 feature 'MSG_PAPER'.
- Changed baudrate to 250000 to get file transfers via USB bit faster.
- These files contain the original PID settings, but i added my to have them even after a hard reset.

-Deutsch und Niederländisch als Sprachen hinzugefügt, um nicht Englisch sprechenden Menschen, speziell Kindern, den Gebrauch vom MK2 zu erleichtern.

-Nederlands en Duits als talen toegevoegd, om mensen die niet Engels spreken, speciaal kinderen, de gebruik van de MK2 gemakkelijker te maken.

### CODE REVIEW

**Comment by 3d-gussner** [comment]
Have still some issues with the LCD menue

**Comment by PavelSindler** [comment]
Thank you very much. We will add German version. We will probably not support Dutch/Nederlands in near future.

**Comment by 3d-gussner** [comment]
Hi Pavel, thanks for the comment! You are doing a great job.
Some German and Dutch speaking persons are reviewing my translations. As soon we all agree, i will make the pull request again.
It would be great if you add German but even better also Dutch.
I/we will track the Github for changes and translate new MSGs.
As i wrote: It should help kids and 'grown-up-kids' to operate the printer bit easier.

**Comment by PavelSindler** [comment]
Hello, we added initial version of German language to our new firmware. We took your version and changed some messages to make the length suitable for LCD display and corrected some special characters.
I understand your point. I know that it would be good to add as many languages as possible. It is easy to add languages, but it can be demanding to support many languages and reflect all changes. in the future.

**Pull request closed without merging**
