### PR TITLE
Add SK language support

### PR DESCRIPTION
**Pull request by ingbrzy**

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@ingbrzy Thanks for the PR
Please compile the firmware with `PF-build.sh` before creating a PR.

At this moment there are several issues with the translation lengths see
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L601-L737
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L916-L1052
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L1231-L1367
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L1546-L1682
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L1861-L1997
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L2176-L2312
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L2511-L2647
- https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L2846-L2982

Also the changes you made to the `lang*.sh` are mostly correct, except that the build of community languages moved to the end of the scripts and `lang-community.sh` should contain the `lang-build.sh sk`

**Comment by 3d-gussner** [comment]
@ingbrzy Have you contacted info@prusd3d.com about the community language support?
There should be some rules how/when community languages are accepted.

I don't know them but it would make sense:
- At least two community members review and approve the language.
- Commitment of these community members to update/support/maintain the language.

**Comment by ingbrzy** [comment]
@3d-gussner thank you for your reply.. I will fix issues which you have found and contact info@prusa3d.com for details..

**Comment by 3d-gussner** [comment]
@ingbrzy please search in the source code for `QR` and `qr` and you should find some hints where to do what.

**Comment by ingbrzy** [comment]
@3d-gussner all issues fixed and SK language moved into community translations.. Thank you for your help!

**Comment by 3d-gussner** [comment]
Saw some of your changes.
Please revert the c=x r=y values as we spend days to review the code and determine the max lengths of each message.
You need to shorten your translations to fit the defined limits.

**Comment by 3d-gussner** [comment]
Also no need to update the po files in the PR as these will be updated just before the releases or by Prusa.

Great that you try to get another community language added. Shows that we have to update the how to add new language documentation.

**Comment by ingbrzy** [comment]
> Saw some of your changes.
> Please revert the c=x r=y values as we spend days to review the code and determine the max lengths of each message.
> You need to shorten your translations to fit the defined limits.

can not be used c=20 as max character limit for one line? some translations are less than 20, so should fit well into one line..

example
https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L705
https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L713
https://travis-ci.com/github/prusa3d/Prusa-Firmware/builds/227712469#L721

**Comment by 3d-gussner** [comment]
There are several locations where messages are shorter, like lcd menu is limited to max 18. Toggle messages are also limited as status messages are. 

As said before we spent days to determine the max lengths reviewing the source code and lcd layout. 

Please don't change these as your PR will fail the review/approval.

If you find a message that has incorrect limits by checking the source code and lcd layout, feel free to report it.

**Comment by ingbrzy** [comment]
> There are several locations where messages are shorter, like lcd menu is limited to max 18. Toggle messages are also limited as status messages are.
> 
> As said before we spent days to determine the max lengths reviewing the source code and lcd layout.
> 
> Please don't change these as your PR will fail the review/approval.
> 
> If you find a message that has incorrect limits by checking the source code and lcd layout, feel free to report it.

OK clear.. reverted it back and fixed translation.. maybe add it to Add_new_language.md as warning for the future translations..

**Comment by 3d-gussner** [comment]
@ingbrzy Hi, we started to implement community translations in FW 3.11.0
If you are still interested in this please try to get it in the [MK3_3.11.0](https://github.com/prusa3d/Prusa-Firmware/tree/MK3_3.11.0) branch.
Please use this branch as a base and let me know if i can help you with anything.
We also need a 2nd maintainer to review the community languages, so if you know someone willing/commit to this task.

**Comment by ingbrzy** [comment]
> @ingbrzy Hi, we started to implement community translations in FW 3.11.0 If you are still interested in this please try to get it in the [MK3_3.11.0](https://github.com/prusa3d/Prusa-Firmware/tree/MK3_3.11.0) branch. Please use this branch as a base and let me know if i can help you with anything. We also need a 2nd maintainer to review the community languages, so if you know someone willing/commit to this task.

OK.. I will close this PR and create a new one for 3.11 branch

**Pull request closed without merging**
