### PR TITLE
Save a few bytes of RAM by moving homing_feedrate to PROGMEM

### PR DESCRIPTION
**Pull request by mdjurfeldt**
Save a few bytes of RAM by moving homing_feedrate to PROGMEM.

### CODE REVIEW

**Comment by DRracer** [comment]
@mdjurfeldt thank you for your PR. It makes sense at the first look, even though there are changes all over Marlin_main.cpp.
My primary concern is: reading a byte from RAM takes 2 cycles, reading a byte from PROGMEM takes 3 cycles.

So a question for you - since some of the calls may be time critical (I know there is an extra call to a common implementation to save a huge amount of code), what is your opinion on slowing the code even further by these extra CPU cycles?

**Comment by 3d-gussner** [comment]
@mdjurfeldt As this PR is stale and no answer provided I close it.

**Comment by mdjurfeldt** [comment]
@3d-gussner Right. I'm sorry but I never got the time to dig into this. On the top of my head I'm simply not competent enough to answer your question. I would have to do a lot of analysis. It seems like your judgement is that it could slow down code critically, so I won't object to your closing of this PR.

**Comment by 3d-gussner** [comment]
Thanks for your PR and understanding I closed it.
If you think it is still a valid PR reopen it and answer the question.

It was stale for so long and I am trying to get the open PRs down.

**Pull request closed without merging**
