### PR TITLE
optimisation: use `disable_heater()` in more places

### PR DESCRIPTION
**Pull request by gudnimg**
This is just an idea. Needs to be verified.

Change in memory:
Flash: -84 bytes
SRAM: 0 bytes

### CODE REVIEW

**Review by 3d-gussner — CHANGES_REQUESTED** [review]
Please rebase

**Comment by gudnimg** [comment]
Rebased to sync with MK3 branch (297 commits)

**Comment by gudnimg** [comment]
The change in power panic needs to be tested carefully.

**Review by 3d-gussner — APPROVED** [review]
Checked and makes sense

**Pull request merged**
