### PR TITLE
Continuous builds on Travis CI

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile the firmware on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload a ZIP file to a temporary download URL on transfer.sh (available for 14 days). The download URL is toward the end of each Travis CI build log of each build (see below for how to set up automatic uploading to your GitHub Releases page).

For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so.

Merging this will have the following advantages:

* Builds will be done in a reproducible environment, not on some developer's local machine
* Each `git push` will be built and will be available for download within minutes
* For each Pull Request, Travis CI will check if the source is still buildable, and mark the PR with _red_ or _green_ depending on the result
* People who want to clone this repository will also clone the Travis CI configuration which enables them to build their own branches on Travis CI too, without the need to set up the Arduino IDE on their local machines
* The exact steps for building are precisely documented in the `.travis.yml` file

__Please note:__ Instead of storing the builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be visible on the Releases page of your project. This is what I recommend. See https://docs.travis-ci.com/user/deployment/releases/. If you want to do this for continuous builds, also see https://github.com/probonopd/uploadtool.

### CODE REVIEW

**Comment by probonopd** [comment]
Happily printing with firmware compiled this way.

**Comment by GurliGebis** [comment]
Looks nice, and a great idea :)
Lets hope it will get merged...

**Comment by PavelSindler** [comment]
Great idea. Thank you. We are currently researching it and it seems that we will start using it soon :-)

**Comment by lekoder** [comment]
@probonopd I was about to set-up Travis myself this weekend. Great job!

**Comment by 3d-gussner** [comment]
@probonopd This PR have been inactive for long time, can you please close it? And Travis CI has been implemented at least for MK3 branch.

**Comment by 3d-gussner** [comment]
@DRracer no reaction from owner, guess it is outdated and can be closed.

**Comment by probonopd** [comment]
Are continuous builds for MK2 available somewhere?

**Comment by 3d-gussner** [comment]
Closed as MK2 branch isn't maintained anymore. Thanks

**Pull request closed without merging**
