### PR TITLE
ENCODER PULSES and STEPS Re-aligned with Clicks

### PR DESCRIPTION
**Pull request by TheZeroBeast**
Tested and confirmed working on MK3. Menu options now are aligned with encoder clicks/positions.

In response to Issue #365

### CODE REVIEW

**Comment by camlesom** [comment]
If the MK3 is using the same encoder from the MK2 then this would be correct, the Configuration.h file for the MK2 has the exact same values shown [here](https://github.com/prusa3d/Prusa-Firmware/blob/f91ace6fec924d3c20d0cc4f765da3d64dce7fcb/Firmware/Configuration.h#L481). Can also find the related commit here 93400ea.

**Comment by Panayiotis-git** [comment]
Agree with camlesom.

The case that the encoder's clicks most of the times do not correspond to exactly 4 pulses and the accurate positioning of the encoder, according to clicks, is rather erratic, is another issue!
It would have been better if the encoder had a 1:1 ratio for the pulses/click.

**Review by camlesom — APPROVED** [review]

**Review by camlesom — CHANGES_REQUESTED** [review]
Too many changes made in this PR, would recommend rebasing to head of MK3 branch and opening a new PR for other changes (leaving only the encoder changes in this PR).

**Comment by TheZeroBeast** [comment]
Hi Cameron,

Sorry, I’m fixing this up in the next few hours and branching. Still new to github.

PullRequest will be back to the iniatial two lines for encoder step changes.

Regards,
Robert McKenzie

**Comment by TheZeroBeast** [comment]
Recreating pull-request.

**Pull request closed without merging**
