### PR TITLE
Remove numbers from level 1 headers in readme

### LINKED ISSUE #2750: [QUESTION] Why are there numbers in front of some headers?
In `README.md`, there are numbers in front of the `Automated tests`, `Documentation` and `FAQ` headers, but not `Build` and `Table of contents`. Why are there numbers in front of some, but not all level 1 headers? Also, why do these numbers start at 3, instead of 1?

### PR DESCRIPTION
**Pull request by awenelo**
The headers `Automated tests`, `documentation` and `FAQ` all have numbers like they are part of a list. However, These numbers start at 3 and don't appear to correlate to anything else.

Fixes #2750

### CODE REVIEW

**Comment by DRracer** [comment]
@awenelo in fact, the numbers do correspond to something. The level of headers is not kept consistent though:
1. Development environment preparation
2. Source code compilation

**Comment by awenelo** [comment]
The Linux build has its own numbering from 1-5, and in between the `Windows > Using Arduino` section of readme and the `Automated Tests` section is `Using Linux subsystem under Windows 10 64-bit` and `Using Git-bash under Windows 10 64-bit`. I feel like the numbering system is really confusing right now, and not having a numbered list spread out across the page with multiple unnumbered headers in between is the simplest way to help with that.

**Comment by DRracer** [comment]
Marking as 3.10 - we shall improve the whole doc page

**Comment by 3d-gussner** [comment]
@awenelo Thanks for the PR, but we have updated the README. Closing

**Pull request closed without merging**
