### PR TITLE
Fix flash size check

### PR DESCRIPTION
**Pull request by mkbel**

### CODE REVIEW

**Comment by 3d-gussner** [comment]
Hi @mkbel I tested it with PF-build.sh including your v1.0.2 and compiling under Ubuntu 64 bit Windows subsystem works fine. Only scary thing is that it shows now 99% used under Linux. Also under Windows 10 64 bit with git-bash everything is okay. But here it shows 97% used. Here some results i got:

- Ubuntu Windows subsystem
`Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
Build options changed, rebuilding all
Sketch uses 251974 bytes (99%) of program storage space. Maximum is 253952 bytes.
Global variables use 6116 bytes of dynamic memory.`

```
Building mutli language firmware 1


config.sh started
 Arduino main folder: OK
 Arduino builder: OK
 AVR gcc tools:
   objcopy OK
   objdump OK
 Output folder: OK
 Objects folder: OK
 Generated elf file: OK
 Generated hex file: OK
config.sh finished with success


lang-build.sh started
lang=en
count=347
offs=710
size=9883
lang=cz
count=347
offs=710
size=9833
lang=de
count=347
offs=710
size=10960
lang=es
count=347
offs=710
size=10888
lang=fr
count=347
offs=710
size=11016
lang=it
count=347
offs=710
size=10926
lang=pl
count=347
offs=710
size=10307
lang-build.sh finished with success
config.sh started
 Arduino main folder: OK
 Arduino builder: OK
 AVR gcc tools:
   objcopy OK
   objdump OK
 Output folder: OK
 Objects folder: OK
 Generated elf file: OK
 Generated hex file: OK
config.sh finished with success
postbuild.sh started
 checking files:
  folder  OK
  elf     OK
  objects OK
 running progmem.sh...OK
 running textaddr.sh...OK
 checking textaddr.txt...NG! - some texts not found in lang_en.txt!
  missing text ignored!
 extracting binary...OK
 updating binary:
  primary language ids...OK
  primary language signature...OK
 converting to hex...OK
  secondary language data...Updating languages:
 Czech  : OK
 German : OK
 Italian: OK
 Spanish: OK
 French : OK
 Polish : OK
 converting to hex...OK

postbuild.sh finished with success

Copying multi language firmware for MK3/Einsy board to Hex-files folder

fw-clean.sh started
 removing 'text.sym'...OK
 removing 'progmem1.lss'...OK
 removing 'progmem1.hex'...OK
 removing 'progmem1.chr'...OK
 removing 'progmem1.var'...OK
 removing 'progmem1.txt'...OK
 removing 'textaddr.txt'...OK
 removing 'firmware.bin'...OK
 removing 'firmware.hex'...OK
 removing 'firmware_cz.hex'...OK
 removing 'firmware_de.hex'...OK
 removing 'firmware_es.hex'...OK
 removing 'firmware_fr.hex'...OK
 removing 'firmware_it.hex'...OK
 removing 'firmware_pl.hex'...OK
 removing 'progmem.out'...OK
 removing 'textaddr.out'...OK
 removing 'update_lang_cz.out'...OK
 removing 'update_lang_de.out'...OK
 removing 'update_lang_es.out'...OK
 removing 'update_lang_fr.out'...OK
 removing 'update_lang_it.out'...OK
 removing 'update_lang_pl.out'...OK
 removing 'lang.bin'...OK
 removing 'lang.hex'...OK
fw-clean.sh finished with success
lang-clean.sh started
 removing 'lang_en.tmp'...OK
 removing 'lang_en.bin'...OK
 removing 'lang_en.dat'...OK
 removing 'lang_cz.tmp'...OK
 removing 'lang_cz.bin'...OK
 removing 'lang_cz.dat'...OK
 removing 'lang_de.tmp'...OK
 removing 'lang_de.bin'...OK
 removing 'lang_de.dat'...OK
 removing 'lang_es.tmp'...OK
 removing 'lang_es.bin'...OK
 removing 'lang_es.dat'...OK
 removing 'lang_fr.tmp'...OK
 removing 'lang_fr.bin'...OK
 removing 'lang_fr.dat'...OK
 removing 'lang_it.tmp'...OK
 removing 'lang_it.bin'...OK
 removing 'lang_it.dat'...OK
 removing 'lang_pl.tmp'...OK
 removing 'lang_pl.bin'...OK
 removing 'lang_pl.dat'...OK
lang-clean.sh finished with success
```

- Windows 10 with git-bash:
`Start to build Prusa Firmware under Windows...
Using variant 1_75mm_MK3S-EINSy10a-E3Dv6full
Build options changed, rebuilding all
Sketch uses 247036 bytes (97%) of program storage space. Maximum is 253952 bytes.
Global variables use 6052 bytes of dynamic memory.
`

```
Building mutli language firmware 1


config.sh started
 Arduino main folder: OK
 Arduino builder: OK
 AVR gcc tools:
   objcopy OK
   objdump OK
 Output folder: OK
 Objects folder: OK
 Generated elf file: OK
 Generated hex file: OK
config.sh finished with success


lang-build.sh started
lang=en
count=347
offs=710
size=9883
lang=cz
count=347
offs=710
size=9833
lang=de
count=347
offs=710
size=10960
lang=es
count=347
offs=710
size=10888
lang=fr
count=347
offs=710
size=11016
lang=it
count=347
offs=710
size=10926
lang=pl
count=347
offs=710
size=10307
lang-build.sh finished with success
config.sh started
 Arduino main folder: OK
 Arduino builder: OK
 AVR gcc tools:
   objcopy OK
   objdump OK
 Output folder: OK
 Objects folder: OK
 Generated elf file: OK
 Generated hex file: OK
config.sh finished with success
postbuild.sh started
 checking files:
  folder  OK
  elf     OK
  objects OK
 running progmem.sh...OK
 running textaddr.sh...OK
 checking textaddr.txt...NG! - some texts not found in lang_en.txt!
  missing text ignored!
 extracting binary...OK
 updating binary:
  primary language ids...OK
  primary language signature...OK
 converting to hex...OK
  secondary language data...Updating languages:
 Czech  : OK
 German : OK
 Italian: OK
 Spanish: OK
 French : OK
 Polish : OK
 converting to hex...OK

postbuild.sh finished with success

Copying multi language firmware for MK3/Einsy board to Hex-files folder

fw-clean.sh started
 removing 'text.sym'...OK
 removing 'progmem1.lss'...OK
 removing 'progmem1.hex'...OK
 removing 'progmem1.chr'...OK
 removing 'progmem1.var'...OK
 removing 'progmem1.txt'...OK
 removing 'textaddr.txt'...OK
 removing 'firmware.bin'...OK
 removing 'firmware.hex'...OK
 removing 'firmware_cz.hex'...OK
 removing 'firmware_de.hex'...OK
 removing 'firmware_es.hex'...OK
 removing 'firmware_fr.hex'...OK
 removing 'firmware_it.hex'...OK
 removing 'firmware_pl.hex'...OK
 removing 'progmem.out'...OK
 removing 'textaddr.out'...OK
 removing 'update_lang_cz.out'...OK
 removing 'update_lang_de.out'...OK
 removing 'update_lang_es.out'...OK
 removing 'update_lang_fr.out'...OK
 removing 'update_lang_it.out'...OK
 removing 'update_lang_pl.out'...OK
 removing 'lang.bin'...OK
 removing 'lang.hex'...OK
fw-clean.sh finished with success
lang-clean.sh started
 removing 'lang_en.tmp'...OK
 removing 'lang_en.bin'...OK
 removing 'lang_en.dat'...OK
 removing 'lang_cz.tmp'...OK
 removing 'lang_cz.bin'...OK
 removing 'lang_cz.dat'...OK
 removing 'lang_de.tmp'...OK
 removing 'lang_de.bin'...OK
 removing 'lang_de.dat'...OK
 removing 'lang_es.tmp'...OK
 removing 'lang_es.bin'...OK
 removing 'lang_es.dat'...OK
 removing 'lang_fr.tmp'...OK
 removing 'lang_fr.bin'...OK
 removing 'lang_fr.dat'...OK
 removing 'lang_it.tmp'...OK
 removing 'lang_it.bin'...OK
 removing 'lang_it.dat'...OK
 removing 'lang_pl.tmp'...OK
 removing 'lang_pl.bin'...OK
 removing 'lang_pl.dat'...OK
lang-clean.sh finished with success
```

I will make a pull request to your pull request or doesn't make that any sense?

**Comment by mkbel** [comment]
Thank you @3d-gussner. I wasn't able to locate rambo/hardware/avr/1.0.1/boards.txt file in windows Arduino for the first sight, so I thought the board is not there.

**Comment by 3d-gussner** [comment]
I use the Arduino IDE in portable mode so it is separated from the default Arduino paths. Just to make sure it is dedicated to Prusa-Firmware build. All needed files stored under /portable/....
During testing and being busy with other Arduino projects like ESP32 is saw that these additional libraries, boards could get mixed.

**Comment by mkbel** [comment]
It sounds like great idea. I will try to convert Linux build environment to portable Arduino.

**Pull request closed without merging**
