### PR TITLE
Update Spanish diacritics

### PR DESCRIPTION
**Pull request by 3d-gussner**

### CODE REVIEW

**Review by leptun — APPROVED** [review]
Language seems to build correctly from PO files. I removed the `ñ` symbol from the FontTable since it's unused.

**Comment by 3d-gussner** [comment]
I will update the changes suggested by @misan tomorrow morning. :hugs:

**Comment by leptun** [comment]
If it includes `ñ` characters, let me know and I'll drop the fontTable commit

**Comment by 3d-gussner** [comment]
Here the output of all Spanish messages
[ES.txt](https://github.com/prusa3d/Prusa-Firmware/files/12904575/ES.txt)

**Comment by leptun** [comment]
@3d-gussner I've dropped that commit since I think it would be better if I prepared a single PR with all the FontTable changes.

**Comment by 3d-gussner** [comment]
@leptun Okay, just wondered why my last changes failed to push.

**Comment by 3d-gussner** [comment]
See video https://github.com/prusa3d/Prusa-Firmware/pull/3383

**Pull request merged**
