### PR TITLE
Fix an issue on multilang builds where first two characters are not rendered

### PR DESCRIPTION
**Pull request by gudnimg**

### CODE REVIEW

**Review by 3d-gussner — APPROVED** [review]

**Review by DRracer — CHANGES_REQUESTED** [review]
Good point, but we should make the text a MSG_TOOLCHANGE_COUNT and have it translated like the rest of our messages.

**Comment by leptun** [comment]
I agree with David. The string should be placed in messages.c with ISTR and then be retrieved here with _T. I'm not sure I understand, but why was _O used here anyway? It looks like a string you might want translated, so I don't see the reason to have it with _O.

**Comment by gudnimg** [comment]
> I agree with David. The string should be placed in messages.c with ISTR and then be retrieved here with _T. I'm not sure I understand, but why was _O used here anyway? It looks like a string you might want translated, so I don't see the reason to have it with _O.

The _O was a mistake on my part as I didnt test on multilang build. 

The menu item as I implemented was only supposed to be temporary/placeholder so I didnt really bother with translations.

**Comment by DRracer** [comment]
@gudnimg since your temporary placeholder became the production solution, let's translate that string as well :wink:

**Review by DRracer — APPROVED** [review]

**Pull request merged**
