### PR TITLE
Clarify temperature and PID calibration menu items. Name the Wizard

### PR DESCRIPTION
**Pull request by thess**
Having trouble remembering which PID calibration setup is for which device? This change clearly identifies the device to be calibrated. Also, I found out the "Wizard" is a "Setup Wizard" -- so I changed that too. (No Unicorns appeared)

"Tenp. calibration"   --> "PINDA temp. cal."
"PID calibration" --> "Extruder PID cal."

"Wizard" --> "Setup Wizard"

Hope this helps some of us forgetful types.

### CODE REVIEW

**Review by GurliGebis — APPROVED** [review]

**Comment by GurliGebis** [comment]
This is a small, but needed change :)

**Comment by PavelSindler** [comment]
There is only extruder PID calibration. Heatbed PID calibration is not added to calibration menu. It ususally take some time to heat or cool down heatbed so usually there are no temperature fluctuations because of this inertia. So PID calibration for heatbed takes a lot of time and brings no visible improvement.
Temp. calibrations is experimantal function which serves for decreasing PINDA probe temperature dependency.

**Comment by thess** [comment]
Ah, I see - I had thought the PINDA calibration was just an M304 wrapper. My mistake.
I updated the menu items and pushed a mod - see edited topic.

**Comment by thess** [comment]
@PavelSindler -- OK?

**Comment by Sebastianv650** [comment]
I like the change, added it to https://github.com/Sebastianv650/Prusa-Firmware.
It will be up to date again from now on :)

**Pull request closed without merging**
