### PR TITLE
Lang 381 fixes 4

### PR DESCRIPTION
**Pull request by DRracer**
Finalized texts for FW 3.8.1 with one exception - one sentence is intentionally left untranslated, because the whole translations BIN file was larger than 64KB.

### CODE REVIEW

**Review by XPila — APPROVED** [review]

**Comment by 3d-gussner** [comment]
@DRracer You skipped https://github.com/prusa3d/Prusa-Firmware/pull/2291/commits/5c2b573415a19d57353463856017919e7376ffac .
Is there another limit we have to be careful with?
I thought as the Einsy stores its translations in the external 2Mb flash and the miniRambo just has to deal with one additional language being stored in internal flash.

**Comment by mkbel** [comment]
@3d-gussner sizeof Pointer to translation is 2B, so it can't point beyond 2^16 B

**Comment by mkbel** [comment]
Theoretically it would be possible to use bigger pointers, but table with pointers to translated strings would grow.

**Comment by leptun** [comment]
Language table usage will decrease once the Toggles PR gets merged later on. Then it would be possible to include everything

**Comment by mkbel** [comment]
> I thought as the Einsy stores its translations in the external 2Mb flash

I think it is 256kB.

**Comment by leptun** [comment]
The external flash is 2mB, while the atmega2560 flash is 256kB.

**Comment by 3d-gussner** [comment]
Yes it is a 2Mb/Mega bit = 256KB kilo bytes external flash [W25X20CLUXIGTR-ND](https://github.com/ultimachine/Einsy-Rambo/blob/master/board/Project%20Outputs/Assembly/BOM-Grouped_Einsy%20Rambo_1.1a.xls)

**Comment by DRracer** [comment]
@3d-gussner @leptun I'm counting on the toggle items patch to save external flash (and much needed space in the internal flash too). For now let's stick with those 64KB, we may improve the translations further on with better indices (i.e. >2B long) or similar approaches. Then there might be even more languages in the future.

**Comment by 3d-gussner** [comment]
I have on my MK3s printer all stock languages + Dutch running and all of them (Czech and Polish bit hard for me to understand) work fine. No glitches on LCD nothing strange.

Have to test my https://github.com/prusa3d/Prusa-Firmware/pull/2223 and the updated to compare.

**Comment by DRracer** [comment]
@3d-gussner interesting, and PrusaSlicer flashes the firmware fine without failing?

**Comment by 3d-gussner** [comment]
What has to stay 64KB?
After running `lang-build.sh` script before merge newest MK3 commits I see following results:
- `lang_en.bin` is 9752 bytes
- `lang_cz.bin` is  9560 bytes
- `lang_de.bin` is 10751 bytes
- `lang_es.bin` is  10580 bytes
- `lang_fr.bin` is  10716 bytes
- `lang_nl.bin` is 10108 bytes
- `lang_it.bin` is 10627 bytes
- `lang_pl.bin` is 9923 bytes

CZ+DE+ES+FR+IT+PL are 62157 bytes
CZ+DE+ES+FR+NL+IT+PL are 72265 bytes

**Comment by 3d-gussner** [comment]
> @3d-gussner interesting, and PrusaSlicer flashes the firmware fine without failing?

@DRracer I get a verification error during PrusaSlicer Firmware Update. BUT the firmware works fine.

**Comment by DRracer** [comment]
@3d-gussner that was my primary concern, I didn't have time to investigate the problem deeply. It seemed to work properly but I simply couldn't count on it.
Let's investigate it in FW 3.9 in more detail, shall we?

**Comment by 3d-gussner** [comment]
My `lang.bin` file is 72265 bytes, and as said it works fine.

**Comment by leptun** [comment]
@DRracer Does prusaSlicer do some kind of check on the hex file or is it avrdude that’s complaining when verifying after upload?
If it’s avrdude, then I hope that everything uploads correctly and that it’s only a verification issue.

Also, any news on a standalone firmware updater that supports the external flash? It’s quite annoying having to use it instead of a plugin in octoprint that uses avrdude.

**Comment by 3d-gussner** [comment]
> @3d-gussner that was my primary concern, I didn't have time to investigate the problem deeply. It seemed to work properly but I simply couldn't count on it.
> Let's investigate it in FW 3.9 in more detail, shall we?

Good idea. I will update my Dutch PR to newest version including the skipped messages you have, and test all languages (with all i mean to me kind of understandable).

I tried to look into PrusaSlicer Firmware Uploader as I think it would be great if we had a Prusa-Firmware OctoPrint plug-in.
I saw that the `avrdude` code has been slightly modified to accept an additional parameter `w0` is ??? write to internal flash and `w1` is write to external flash ???

Didn't dive too much into the code, but still think that would be a great OctoPrint Plug-In. Maybe somebody from the PrusaSlicer development team could have a look ;-)

**Comment by 3d-gussner** [comment]
@leptun ^^^ :-)

**Comment by 3d-gussner** [comment]
Last comment about >64kb `lang.bin` file: 
The firmware including Dutch language translation is used by ~100+ users (another fork I try to support). And only complain is the verification message.

**Comment by 3d-gussner** [comment]
@DRracer @mkbel Another Question:
How does Prusa generates the release hex files, as these we can download have always `1_75mm_MK3-EINSy10a-E3Dv6full` in the last line?
When I compile the firmware using `PF-build.sh` I don't have that.

**Comment by 3d-gussner** [comment]
Here the results of MK3_DUTCH Prusa Firmware Upload Log
```
avrdude-slic3r -v -p atmega2560 -c wiring -P COM8 -b 115200 -D -U flash:w:0:<Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex:i

avrdude-slic3r: Version 6.3-20160220-prusa3d, compiled on Sep 16 2019 at 11:15:49
                Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
                Copyright (c) 2007-2014 Joerg Wunsch


                Using Port                    : COM8
                Using Programmer              : wiring
                Overriding Baud Rate          : 115200
                AVR Part                      : ATmega2560
                Chip Erase delay              : 9000 us
                PAGEL                         : PD7
                BS2                           : PA0
                RESET disposition             : dedicated
                RETRY pulse                   : SCK
                serial program mode           : yes
                parallel program mode         : yes
                Timeout                       : 200
                StabDelay                     : 100
                CmdexeDelay                   : 25
                SyncLoops                     : 32
                ByteDelay                     : 0
                PollIndex                     : 3
                PollValue                     : 0x53
                Memory Detail                 :

                                         Block Poll               Page                       Polled
                  Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
                  flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
                  lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
                  signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

                Programmer Type : Wiring
                Description     : Wiring
                Programmer Model: AVRISP
                Hardware Version: 15
                Firmware Version Master : 2.10
                Vtarget         : 0.0 V
                SCK period      : 0.1 us

avrdude-slic3r: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude-slic3r: Device signature = 0x1e9801 (probably m2560)
avrdude-slic3r: safemode: hfuse reads as D0
avrdude-slic3r: safemode: efuse reads as FD
avrdude-slic3r: reading input file "<Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex"
avrdude-slic3r: writing flash (241368 bytes):

Writing | ################################################## | 100% 41.88s

avrdude-slic3r: 241368 bytes of flash written
avrdude-slic3r: verifying flash memory against <Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex:
avrdude-slic3r: load data flash data from input file <Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex:
avrdude-slic3r: input file <Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex contains 241368 bytes
avrdude-slic3r: reading on-chip flash data:

Reading | ################################################## | 100% 30.90s

avrdude-slic3r: verifying ...
avrdude-slic3r: 241368 bytes of flash verified

avrdude-slic3r: safemode: hfuse reads as D0
avrdude-slic3r: safemode: efuse reads as FD
avrdude-slic3r: safemode: Fuses OK (E:FD, H:D0, L:FF)

avrdude-slic3r done.  Thank you.

avrdude-slic3r -v -p atmega2560 -c arduino -P COM8 -b 115200 -D -u -U flash:w:1:<Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex:i

avrdude-slic3r: Version 6.3-20160220-prusa3d, compiled on Sep 16 2019 at 11:15:49
                Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
                Copyright (c) 2007-2014 Joerg Wunsch


                Using Port                    : COM8
                Using Programmer              : arduino
                Overriding Baud Rate          : 115200
                AVR Part                      : ATmega2560
                Chip Erase delay              : 9000 us
                PAGEL                         : PD7
                BS2                           : PA0
                RESET disposition             : dedicated
                RETRY pulse                   : SCK
                serial program mode           : yes
                parallel program mode         : yes
                Timeout                       : 200
                StabDelay                     : 100
                CmdexeDelay                   : 25
                SyncLoops                     : 32
                ByteDelay                     : 0
                PollIndex                     : 3
                PollValue                     : 0x53
                Memory Detail                 :

                                         Block Poll               Page                       Polled
                  Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
                  flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
                  lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
                  signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

                Programmer Type : Arduino
                Description     : Arduino
                Hardware Version: 3
                Firmware Version: 6.2
                Vtarget         : 0.3 V
                Varef           : 0.3 V
                Oscillator      : 28.800 kHz
                SCK period      : 3.3 us

avrdude-slic3r: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude-slic3r: Device signature = 0x1e9801 (probably m2560)
avrdude-slic3r: reading input file "<Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex"
avrdude-slic3r: writing flash (75558 bytes):

Writing | ################################################## | 100% 8.96s

avrdude-slic3r: 75558 bytes of flash written
avrdude-slic3r: verifying flash memory against <Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex:
avrdude-slic3r: load data flash data from input file <Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex:
avrdude-slic3r: input file <Firmware Path>\Prusa-Firmware\PF-build-hex\FW381-RC1-Build2852\BOARD_EINSY_1_0a\FW381-RC1-Build2852-1_75mm_MK3S-EINSy10a-E3Dv6full.hex contains 75558 bytes
avrdude-slic3r: reading on-chip flash data:

Reading | ################################################## | 100% 8.49s

avrdude-slic3r: verifying ...
avrdude-slic3r: verification error, first mismatch at byte 0x10000
                0x00 != 0x11
avrdude-slic3r: verification error; content mismatch

avrdude-slic3r done.  Thank you.

```

**Pull request merged**
