### PR TITLE
Fix build error when `TMC2130_SERVICE_CODES_M910_M918` is enabled

### LINKED ISSUE #3284: [BUG] TMC2130_SERVICE_CODES_M910_M918 breaks compiling
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3S
**Printer firmware version**- Prusa-Firmware-3.10.1-RC1 but also didnt work with the official 3.10 Version

**Describe the bug**
When i uncomment "#define TMC2130_SERVICE_CODES_M910_M918" in Configuration_prusa.h i get this error
  
image

when its commented out, everything works. 
in FW version 3.9.3 everything worked when uncommenting this

### PR DESCRIPTION
**Pull request by gudnimg**
Fixes #3284

### CODE REVIEW

**Comment by DRracer** [comment]
@gudnimg could you please rebase this PR onto MK3_3.10.1? Or cherry pick against MK3_3.10.1? Thank you.
A simple change of bases in github web interface would have introduced way too may changes.

**Review by 3d-gussner — APPROVED** [review]
I can confirm that this fixes the compile issue as well it is working (tested `M913`)

Putty log to MK404 sending `M913` gcode and get the values
```
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2021.11.18 12:29:48 =~=~=~=~=~=~=~=~=~=~=~=
start
;S
SN update failed
echo: 3.10.1-5175
PowerUp
echo: Last Updated: Nov 18 2021 12:29:08 | Author: (none, default config)
Compiled: Nov 18 2021
echo: Free Memory: 2053  PlannerBufferBytes: 1760
echo:Hardcoded Default Settings Loaded
adc_init
Extruder fan type: NOCTUA
CrashDetect ENABLED!
FSensor ENABLED (sensor board revision:unknown state)
Sending 0xFF
echo:SD card ok
LCD status changed
M913MMU not responding - DISABLED

tmc2130_print_currents()
	H	R
X	16	16
Y	20	20
Z	35	35
E	30	30
ok
```

**Comment by gudnimg** [comment]
I created a new PR with a cherry pick: https://github.com/prusa3d/Prusa-Firmware/pull/3304

**Comment by DRracer** [comment]
@gudnimg great, merged #3304 into 3.10.1

**Comment by gudnimg** [comment]
@DRracer Should I close this PR? I assume you will merge 3.10.1 branch into MK3 later?

**Comment by 3d-gussner** [comment]
@gudnimg Normally when Prusa makes a final release it will be merged into the the development `MK3` see https://github.com/prusa3d/Prusa-Firmware/pull/3141

**Pull request closed without merging**
