### PR TITLE
Wait a little bit longer for MMU2 to pull out the filament

### PR DESCRIPTION
**Pull request by workinghard**
Sometimes MMU2 is too slow, let's wait a little bit longer. Issue is described in #2086

### CODE REVIEW

**Comment by workinghard** [comment]
Is there any timeline for review? This is still an issue.

**Comment by smurfix** [comment]
Unfortunately nobody at Prusa seems to look after MMU2 code. Nod good, that.

**Comment by workinghard** [comment]
@smurfix True. Not even such a small contributions are being merged or even commented. I’m staying at the older firmware version with my changes. That works for me.

**Comment by 3d-gussner** [comment]
@workinghard Thanks, but please checkout MMU FW 3.0.0. Closing.

**Pull request closed without merging**
