### PR TITLE
Remove unused `Sound_Save()` function declaration

### PR DESCRIPTION
**Pull request by gudnimg**
I noticed there is no defined function called `Sound_Save()`

### CODE REVIEW

**Comment by gudnimg** [comment]
Why are all the functions `extern`? I noticed this in other files also like `ultralcd.h`, it looks like we can drop the `extern` keyword everywhere... am I missing something?

**Comment by leptun** [comment]
Is there any difference between c and c++ when it comes to the `extern` keyword in headers? I mean, will c break if we remove the `extern`?

**Comment by gudnimg** [comment]
> Is there any difference between c and c++ when it comes to the `extern` keyword in headers? I mean, will c break if we remove the `extern`?

There is no difference I’m aware of between C and C++ when it comes to the `extern` keyword. 

`extern` is usually used only for variables to make them available to other files as global. When the function declaration is included with a header file then the `extern` keyword (on a function) is not needed since external linkage is the default behaviour. So long as we have all the right `#include`’s I don’t see how removing `extern` can break things. 🤔 

But if there is no header file between two `.cpp` files then it is my understanding that `extern` can be used but I think that should be avoided if possible.

**Comment by wavexx** [comment]
The default has always been "extern" on gcc. There's no difference between c/c++ in this regard, except when combined with the "inline" keyword, which is a weird thing to do anyway. And const globals in c++ if I'm not mistaken, which is not an issue normally.

You can change the default using -fvisibility or some pragma, so that all functions/classes behave as "static", and you explicitly need to use extern instead to make the function visible outside the current module.

I think extern was probably used by some with experience with some other compiler/os.

**Review by DRracer — APPROVED** [review]
Confirmed, there is no implementation for Sound_Save(), it makes sense to remove this relict of the past.

**Pull request merged**
