### PR TITLE
Build Prusa-Firmware on Linux 64-bit and Windows 64-bit

### PR DESCRIPTION
**Pull request by 3d-gussner**
#### Why did I do that?
As a Windows user I compile quite often the firmware to test new features and lot of variants. The manual compiling takes a long time and human (me) errors can happen.
Also many users struggle to get the build environment right and we get lot of questions about that.

So i looked into the https://github.com/mkbel/PF-build-env and build a Windows 10 64-bit version myself https://github.com/3d-gussner/PF-build-env/releases . It works great.

Next step was to improve the `PF-build.sh` to prevent human errors and make it more "smart" and user friendly.

Also wrote a Github Wiki https://github.com/3d-gussner/Prusa-Firmware/wiki/How-to:-Build-Prusa-Firmware to help users.

#### Added features and improvements
- Checking for OS and 64-bit
  - download `PF-build-env` relative to OS (Linux by @mkbel / Windows by @3d-gussner)
- Advanced checking of the build environment
- Improved user interaction
  - Selection which variant to compile or ALL
  - Selection if multi-language or English_only version should be build
- Check the development status (GOLD/RC/BETA/ALPHA...)
- Unique output folders and `.hex` file names including FW version/build/variant
- Auto zip for miniRAMbo based multi language `.hex` files

#### Testing internal and external
After testing with Windows 10 git-bash and later Linux subsystem myself I decided to ask few other members in the community and got lot of feedback and help.
You can see in the `PF-build.sh` the iterations/changes have been made.

Tested environment:
- Windows 10 64-bit with git-bash (me and others) using my PF-build-env for Windows
- Windows 10 64-bit with Linux subsystem and Ubuntu (me and others) using mkbel his Linux PF-build-env
- Linux 64-bit in VM (others) using mkbel his Linux PF-build-env

**Generating 22 multi language variants  (82 `.hex` files) took me ~33min and additional ~14min for the EN_ONLY.**

Hope Prusa is willing to give this a try to test it and maybe even merge that PR.

Thanks to all testers and especially to @ropaha who helped a lot with the code.

### CODE REVIEW

**Comment by mkbel** [comment]
Can I add link to your issue tracker to build instructions for Linux subsystem and Git-bash before merging this? You can review proposed changes there https://github.com/prusa3d/Prusa-Firmware/pull/1543/commits/a4cf31b104de1dea83b25a844cdc9bcc03f1a777

**Comment by 3d-gussner** [comment]
@mkbel No Problem to add my issue tracker for that one. Glad you tried it and are willing to approved it.

**Comment by mkbel** [comment]
Thank you for your contribution very much.

**Comment by mkbel** [comment]
@3d-gussner It make sense to add folder structure description. In Linux build there is already such description. You can open new pull request with such description and I will look onto that. I have noticed, in your previous comment for script PF-build.sh it creates:
../build-env
but in script build.sh it is created inside Prusa-Firmware folder.
./build-env

It would be nice if both scripts would behave similar.
That is the question what placement of build-env is better.
My philosophy when doing this for the first time for project MM-control-01 was to put everything what is possible to create inside project folder to create inside. And to put outside only what is necessary for some other reason. 

Reason to put build folder outside of project folder was, that MM-control-01 project uses cmake and out-of-source build is preferred way for cmake and I am using Eclipse CDT as my editor and Eclipse CDT project file must be generated out of folder with top cmakelist.txt in order to work.

I also put unpacked build environment folder outside project folder, so build environment could be shared with more project in the future.

And I used same structure for Prusa-Firmware so it could potentially switch to cmake in a future without changing folder structure.

This is also reason why I didn't bother with windows build environment, I hoped for cmake, which is cross-platform. I am not very happy how language variants are made using bash and that changes in stock Arduino are needed. I think that such changes are unnecessary and could be made in board definition. But yeah, at least language builds are now available for both platforms and you can't imagine how much effort it was to get working build instructions for language builds from its author.

**Comment by 3d-gussner** [comment]
@mkbel Sorry for the late answer.
Why did i choose to put the `build-env` folder outside the source code folder:

- Most users will download the `source.zip` from the release notes and these are saved by default to `c:\users\<user-name>\Downloads`
- Most will unzip it to an folder with the same name as the zip.
  - Example: `Prusa-Firmware-3.5.3.zip` will be unzipped to `c:\users\<user-name>\Downloads\Prusa-Firmware-3.5.3`
  - But they probably have already a folder `c:\users\<user-name>\Downloads\Prusa-Firmware-3.5.1` or others. And will have newer versions the same way
- Placing the `build-env` outside the source folder has the advantage that the `PF-build-env-Linux64-$BUILD_ENV.zip` and `PF-build-env-Win-$BUILD_ENV.zip` will be download **once** (depending on their version) and not with every new firmware release.
- The `build.sh` checks if the folder `PF-build-env-Linux64-$BUILD_ENV` outside of the source folder exists to prevent unnecessary unzipping time. So I thought why not saving download time/MBs by placing the `build-env` also outside. 

Looked also in the MM-control-01 build-env but didn't use it yet that much.

The language part took some time to understand how everything works, and still it isn't 100% clear how the process works.
- `lang-build.sh` generates the necessary `bin` files to be merged by
- `fw-build.sh`
- `lang-export.sh` uses `lang_en.txt` and the compiled code to generate the `po` files under `/lang/po`
  - using `Poedit` makes it quite easy to check the translations and add new once
  - but how to use `/lang/po/new` is still not completely clear to me, as it is used by `lang-import.sh` script to generate the new `lang_en_<country_code>.txt` files
  - how the `lang-add.sh` is used and what the syntax of the `lang_add.txt` has to be, is also unclear to me.

I started a while ago to add other languages to the MK2 firmware as I want to make the use of a 3D printer easier to non-native english speaking persons.
As i live in Belgium we mis the Dutch translation and other helped to even add Portuguese which was nice.
Most users will be fine with English, but kids that aren't that comfortable with it appreciate the 3D printer   talking to them in their language :-)

**Pull request merged**
