### PR TITLE
MMU logging improvements

### PR DESCRIPTION
**Pull request by wavexx**
Improve the debugging experience by removing repeated ACK responses from the serial:

- Update "S0" CRC on replies so that the message is properly silenced.
- Do the same for "ok" responses.

### CODE REVIEW

**Comment by gudnimg** [comment]
Comparing the output to MK3 branch something looks wrong. There are empty lines probably due to the \n added by `MMU2_ECHO_MSGLN` or `MMU2_ERROR_MSGLN`

Maybe these aren't needed anymore:
```
tmp[size + 1] = '\n';
tmp[size + 2] = 0;
```

**BEFORE:**

```
09:03:52.349 -> start
09:03:54.156 -> echo: 3.13.0-ALPHA1-6054
09:03:54.156 -> echo:MMU2:>S0*c6.
09:03:54.156 -> ResetRetryAttempts
09:03:54.156 -> SpoolJoin is On
09:03:54.156 -> echo: Last Updated: 1970-01-01 00:00:00 | Author: (none, default config)
09:03:54.156 -> echo: Free Memory: 2479  PlannerBufferBytes: 1776
09:03:54.156 -> TM: stored calibration invalid, resetting
09:03:54.156 -> echo:Stored settings retrieved
09:03:54.309 -> adc_init
09:03:54.309 -> Hotend fan type: NOCTUA
09:03:55.313 -> CrashDetect ENABLED!
09:03:56.216 -> Sending 0xFF
09:03:56.216 -> echo:SD card ok
09:04:00.715 -> // action:dump_available
09:04:00.715 -> echo:MMU2:>S0*c6.
09:04:02.706 -> echo:MMU2:>S0*c6.
09:04:04.728 -> echo:MMU2:>S0*c6.
09:04:06.734 -> echo:MMU2:>S0*c6.
09:04:06.734 -> echo:MMU2:<S0 A2*37.
09:04:06.734 -> echo:MMU2:>S1*ad.
09:04:06.734 -> echo:MMU2:<S1 A1*21.
09:04:06.734 -> echo:MMU2:>S2*10.
09:04:06.734 -> echo:MMU2:<S2 A5*e.
09:04:06.734 -> echo:MMU2:>S3*7b.
09:04:06.734 -> echo:MMU2:<S3 A2ec*d7.
09:04:06.734 -> echo:MMU2:>Wb 5*33.
09:04:06.734 -> echo:MMU2:<Wb A*5c.
09:04:06.734 -> echo:MMU2:>f0*21.
09:04:06.734 -> echo:MMU2:<f0 A*c5.
09:04:06.734 -> echo:MMU2:>Q0*ea.
09:04:06.734 -> echo:MMU2:<X0 F0*87.
09:04:06.734 -> echo:MMU2:>R8*81.
09:04:06.734 -> echo:MMU2:<R8 A0*8d.
09:04:06.734 -> echo:MMU2:>R1b*9e.
09:04:06.734 -> echo:MMU2:<R1b Aff*bf.
09:04:06.781 -> echo:MMU2:>R1c*88.
09:04:06.781 -> echo:MMU2:<R1c Aff*60.
09:04:06.781 -> echo:MMU2:>R4*7b.
09:04:06.781 -> echo:MMU2:<R4 A423*eb.
09:04:06.781 -> echo:MMU2:>R1a*f5.
09:04:06.781 -> echo:MMU2:<R1a A0*41.
09:04:07.784 -> echo:MMU2:>Q0*ea.
09:04:07.784 -> echo:MMU2:<X0 F0*87.
```


**AFTER:**

```
09:10:49.540 -> start
09:10:51.296 -> echo: 3.13.0-ALPHA1-6054
09:10:51.296 -> echo:MMU2:>S0*c6.
09:10:51.296 -> 
09:10:51.296 -> ResetRetryAttempts
09:10:51.296 -> SpoolJoin is On
09:10:51.296 -> echo: Last Updated: 1970-01-01 00:00:00 | Author: (none, default config)
09:10:51.343 -> echo: Free Memory: 2467  PlannerBufferBytes: 1776
09:10:51.343 -> TM: stored calibration invalid, resetting
09:10:51.343 -> echo:Stored settings retrieved
09:10:51.426 -> adc_init
09:10:51.426 -> Hotend fan type: NOCTUA
09:10:52.439 -> CrashDetect ENABLED!
09:10:53.360 -> Sending 0xFF
09:10:53.401 -> echo:SD card ok
09:10:57.874 -> // action:dump_available
09:11:03.874 -> echo:MMU2:<S0 A2*37.
09:11:03.874 -> echo:MMU2:>S1*ad.
09:11:03.874 -> 
09:11:03.874 -> echo:MMU2:<S1 A1*21.
09:11:03.874 -> echo:MMU2:>S2*10.
09:11:03.874 -> 
09:11:03.874 -> echo:MMU2:<S2 A5*e.
09:11:03.874 -> echo:MMU2:>S3*7b.
09:11:03.874 -> 
09:11:03.874 -> echo:MMU2:<S3 A2ec*d7.
09:11:03.914 -> echo:MMU2:>Wb 5*33.
09:11:03.914 -> 
09:11:03.914 -> echo:MMU2:<Wb A*5c.
09:11:03.914 -> echo:MMU2:>f0*21.
09:11:03.914 -> 
09:11:03.914 -> echo:MMU2:<f0 A*c5.
09:11:03.914 -> echo:MMU2:>Q0*ea.
09:11:03.914 -> 
09:11:03.914 -> echo:MMU2:<X0 F0*87.
09:11:03.914 -> echo:MMU2:>R8*81.
09:11:03.914 -> 
09:11:03.914 -> echo:MMU2:<R8 A0*8d.
09:11:03.914 -> echo:MMU2:>R1b*9e.
09:11:03.914 -> 
09:11:03.914 -> echo:MMU2:<R1b Aff*bf.
09:11:03.914 -> echo:MMU2:>R1c*88.
09:11:03.914 -> 
09:11:03.914 -> echo:MMU2:<R1c Aff*60.
09:11:03.914 -> echo:MMU2:>R4*7b.
```

**Comment by gudnimg** [comment]
I've also not seen the "ok" flood the serial. When do you see that happen?

**Review by gudnimg — CHANGES_REQUESTED** [review]
See comment above.

**Comment by wavexx** [comment]
> tmp[size + 1] = '\n';

Indeed, removed it as it's now automatically inserted. The flood happens if an original or incompatible FW is loaded onto the mmu2, until it times out.

Looks like there is still a ton of polling being shown with an updated FW though, so the serial output is hardly readable IMHO.

**Comment by gudnimg** [comment]
Looks good to me now. I'm a bit concerned about the increase in SRAM usage:

Flash increase: 20 bytes
SRAM increase: 15 bytes

Can we reduce this somehow? It's probably the static variable that is remembering the last response. IMO I don't think we should do this on the MK3S side as it doesn't really solve the problem. Why is the MMU sending repeated responses?

**Comment by wavexx** [comment]
I think we can split the PR. The newline/checksum fixe (which is something which was always there) should actually reduce flash/sram. Leave the response suppression for later.

**Comment by gudnimg** [comment]
Is the 'ok' maybe coming from MK3 printer when its using `OldMMUFWDetector `in Error state? Searching for "ok". Maybe there is a bug there. I don't see any place where the new MMU FW is sending `ok`


```
case DecodeStatus::Error:{
            // consume old MMU FW's data if any -> avoid confusion of protocol decoder
            auto old = oldMMUh4x0r.Detect(c);
            if( old == OldMMUFWDetector::State::Matched ){
                // hack bad FW version - BEWARE - we silently assume that the first query is an "S0"
                // The old MMU FW responds with "ok\n" and we fake the response to a bad FW version at this spot
                rsp = ResponseMsg(RequestMsg(RequestMsgCodes::Version, 0), ResponseMsgParamCodes::Accepted, 0);
                return MessageReady;
```

**Comment by wavexx** [comment]
Mmh this indeed looks like the only place this can come from

**Comment by gudnimg** [comment]
> Leave the response suppression for later.

Here is my attempt for this particular issue. https://github.com/prusa3d/Prusa-Firmware/pull/3819

**Comment by wavexx** [comment]
Updated to be mostly a clean-up PR. This cleanups the \n/MMU_ECHO functions. Saves 44 bytes of flash, plus 1 of sram too.

**Review by gudnimg — APPROVED** [review]

**Review by DRracer — APPROVED** [review]

**Pull request merged**
