### PR TITLE
Update Norwegian community translation PFW-1296

### PR DESCRIPTION
**Pull request by pkg2000**
Norwegian Translation

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@trondkla Thanks for the contribution to the Norwegian community translation, can you please "approve" with a comment the changes made here?

**Review by trondkla — APPROVED** [review]
Solid work, I think this will be splendid for the new generation of tinkerers :)

**Comment by trondkla** [comment]
@3d-gussner The changes made was more consistant usage of the same word for bed and ejecting / loading filament.
Some tricky words that had to be as precise as possible, but still be inside the restrictions for lengths :)

**Comment by 3d-gussner** [comment]
> Solid work, I think this will be splendid for the new generation of tinkerers :)

One of the reasons I started years ago to translate the firmware to Dutch as kids in maker spaces had issues using the printer in English.

**Comment by wavexx** [comment]
Note that I would merge #3471 first, then apply the changes on top.

I'm not sure whether this changed, but if it this, resolving the conflict the other way around will be hard.

**Comment by 3d-gussner** [comment]
Closing this in favor of https://github.com/prusa3d/Prusa-Firmware/pull/3508 which is based on this one

**Pull request closed without merging**
