### PR TITLE
PFW-1049: Enable print fan while waiting for cooldown

### PR DESCRIPTION
**Pull request by leptun**
As the title says, this PR enables the print fan when waiting for nozzle and bed to cool down.
After they are cooled it goes back to its initial speed.

### CODE REVIEW

**Comment by wavexx** [comment]
Does it make it faster in your case?
I timed this a couple of times and couldn't see any difference.

**Comment by leptun** [comment]
In my case it cools the hotend much faster this way. It depends on ambient temperature, as a cold environment makes it faster. In my case it is <20*C

**Comment by Panayiotis-git** [comment]
Are you using hotend silicon socks?

**Comment by leptun** [comment]
I am using stock Mk3. No sock.

**Comment by wavexx** [comment]
On Mon, Apr 15 2019, Voinea Alex wrote:
> I am using stock Mk3. No sock.

I'm using the sock, so that might be the reason.

**Comment by leptun** [comment]
@PavelSindler do you plan to merge this PR or should I just close it?

**Comment by leptun** [comment]
@DRracer  Do you consider merging this PR? If not, let me know and I'll close it.

**Comment by DRracer** [comment]
@leptun yes, we'll look at it, please keep it open for now

**Comment by DRracer** [comment]
@lepun Are you sure that setting the print fan to full speed after the print has finished is a good idea for "warpy" plastics like ABS or ASA (even thought the head is in parking position after the print)? I'd rather prefer having these ABS printout cooled down slowly without too much airflow around. Such approach has given me the best results so far. What is your experience?

**Comment by leptun** [comment]
@DRracer You misunderstood what this PR is doing. 

This PR changes the lcd_wait_for_cool_down() function. This is used for waiting for nozzle/bed cooldown before starting a calibration. For example, this way if you do a selftest and then you run xyz calibration it cools down and starts the next calibration faster, as the fan blows on the nozzle till it cools it to 50deg.

This does not affect normal printing, only calibrations.

**Comment by leptun** [comment]
Testing: Preheat printer, start XYZ calibration. (any hotend temp over 50 should me enough)

**Review by DRracer — APPROVED** [review]

**Pull request merged**
