### PR TITLE
Add Eject Option To Filament Load Message

### LINKED ISSUE #4643: [ENHANCEMENT]Filament load needs to be 3 state
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S, MK3,

**Is your enhancement related to a problem? Please describe.**
  Load filament has 2 options was a filament loaded correctly Yes / No.

It is not sufficient enough. Many times I get into a situation when fillament stuck and both answers are irelevant.
You will need to immediatelly eject.

The situation might be bad cut fillament and stuck, wrong temperature and so on.

The answer Yes is the lie, but it only allows to further fillament eject.

The correct answer No makes a situation even worse.

**Describe the solution you'd like**
There is a neccessity to add 3rd option **eject**.

### PR DESCRIPTION
**Pull request by sarusani**
Add a third option ("eject") to the "Filament extruding & with correct color?" message.

Closes https://github.com/prusa3d/Prusa-Firmware/issues/4643

The third_choice text was rendered incorrectly. (Only showed the first letter of the text because the position was hardcoded.)
I made sure the third_choice text will be offset to the left, but not overlap with the second_choice text.

This uses quite a lot of mem, any help in optimizing is appreciated 😸

### CODE REVIEW

**Comment by gudnimg** [comment]
I wonder if we can save memory by converting the following arguments into a single `struct` and adding `third_col` parameter. And that way force the caller to specify the column. 🤔

`void lcd_show_choices_prompt_P(uint8_t selected, const char *first_choice, const char *second_choice, uint8_t second_col, const char *third_choice)`

**Comment by 3d-gussner** [comment]
> I wonder if we can save memory by converting the following arguments into a single `struct` and adding `third_col` parameter. And that way force the caller to specify the column. 🤔
> 
> `void lcd_show_choices_prompt_P(uint8_t selected, const char *first_choice, const char *second_choice, uint8_t second_col, const char *third_choice)`

The biggest cost +196 bytes is https://github.com/prusa3d/Prusa-Firmware/pull/4644/files#diff-5fbfdca43c192573e31d8e78d255c510fb6e213b118cf38173277ec2a2163880R2261-R2269

The last part only costs additional +32 bytes https://github.com/prusa3d/Prusa-Firmware/pull/4644/files#diff-5fbfdca43c192573e31d8e78d255c510fb6e213b118cf38173277ec2a2163880R3047-R3053

**Comment by gudnimg** [comment]
> The biggest cost +196 bytes is https://github.com/prusa3d/Prusa-Firmware/pull/4644/files#diff-5fbfdca43c192573e31d8e78d255c510fb6e213b118cf38173277ec2a2163880R2261-R2269

In that case I wonder if some of the function calls are being inlined. You can try adding `__attribute__((noinline))` to the definition and see if that helps. None of these are time critical.

**Comment by gudnimg** [comment]
I looked a bit into this flash usage, and I suspect this is due to the compiler not able to optimise the code like it could before. `third_choice` was always set to `nullptr` before, but now you give it a value which complicates things. I've pretty much ruled out inlining.

**Comment by 3d-gussner** [comment]
@gudnimg Any idea if that can be optimized?

**Comment by 3d-gussner** [comment]
@sarusani Please rebase the PR and solve the conflicts.

**Review by 3d-gussner — APPROVED** [review]
Tested with MK404 :heavy_check_mark: 

Tue Apr  9 18:50:31 2024

**Comment by 3d-gussner** [comment]
@gudnimg Do you think we can save any bytes here? If not please approve.

**Pull request merged**
