### PR TITLE
German transation

### PR DESCRIPTION
**Pull request by 3d-gussner**
Hi, tried to use as many as possible translation from Marlin.

### CODE REVIEW

**Comment by PavelSindler** [comment]
There are max. lengths and number of lines prolonged to values which are wrong. For example:
`#define(length=20,lines=3) MSG_CONFIRM_CARRIAGE_AT_THE_TOP	"Are left and right Z~carriages all up?"`
In this case, max. number of lines is 2.
There are probably more cases like that.

**Comment by 3d-gussner** [comment]
@PavelSindler Thanks for pointing these out. These have to be confirmed and it would be better not having scrolling messages, get it. Gonna check which these are and add a comment NOT to change the limits.
Also try to squeeze in these the translation in.

**Comment by thess** [comment]
@3d-gussner - When making pull-requests, please consider using the following advice excerpted from the documentation of another project I work on. It is intended to help folks make pull-requests which are concise and easier to work with. Perhaps this may be of some help to the Prusa Firmware project in general and could be incorporated into the github sources (along with some useful build docs).
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests
### Advice on pull requests:

Pull requests are the easiest way to contribute changes to git repos at Github. They are the preferred contribution method, as they offer a nice way for commenting and amending the proposed changes.

* You need a local "fork" of the Github repo.
* Use a "feature branch" for your changes. That separates the changes in the pull request from your other changes and makes it easy to edit/amend commits in the pull request. Workflow using "feature_x" as the example:
  - Update your local git fork to the tip (of the master, usually)
  - Create the feature branch with `git checkout -b feature_x`
  - Edit changes and commit them locally
  - Push them to your Github fork by `git push -u origin feature_x`. That creates the "feature_x" branch at your Github fork and sets it as the remote of this branch
  - When you now visit Github, you should see a proposal to create a pull request

* If you later need to add new commits to the pull request, you can simply commit the changes to the local branch and then use `git push` to automatically update the pull request.

* If you need to change something in the existing pull request (example: Resolve upstream merge conflicts), you can use `git push -f` to overwrite the original commits. That is easy and safe when using a feature branch. Example workflow:
  - Checkout the feature branch by `git checkout feature_x`
  - Edit changes and commit them locally. If you are just updating the commit message in the last commit, you can use `git commit --amend` to do that
  - If you added several new commits or made other changes that require cleaning up, you can use `git rebase -i HEAD~X` (X = number of commits to edit) to possibly squash some commits. Easy to follow instructions are provided by git.
  - Push the changed commits to Github with `git push -f` to overwrite the original commits in the "feature_x" branch with the new ones. The pull request gets automatically updated

**Comment by 3d-gussner** [comment]
@thess Thanks for the great advice and link.

I keep the master branch synced to the upstream and don't change anything there anymore.
For each idea/change i create a different worktree from the master folder using "git worktree add -b <idea/change> ../<idea.change>" and make there the changes. At this moment i have 12 branches each for a change to be able to make more clear pull requests.
Updates/commits from the upstream master i merge to the different branches to keep them up to date and solve possible conflicts.

**Pull request closed without merging**
