### PR TITLE
German language added, updated spanish language messages, checking if…

### PR DESCRIPTION
**Pull request by PavelSindler**
… Z live adjust is in allowed range, chcecking for invalid gcodes added, fixed bug in total print time, fixed selftest to avoid false triggering, added auto home after selftest, removed farm mode menu feature, added experimental functions for checking bed properties

### CODE REVIEW

**Comment by 3d-gussner** [comment]
Hi Pavel,

just saw that you pulled the German language. Few people and i were busy to translate to German and Dutch, and finally we are done.
Today i had 10+ firmware uploads to get it nice on the LCD screen. Just send another pull request. The MSGs should now look good on the LCD screen. Please consider to get the updates.
In the "old" version i tried to get "äöü" in the translation by using \x81 \x84 end so on. But these are not show correctly on the LCD so i had to go for "ä=ae", "ö=oe" and "ü=ue".

**Comment by bubnikv** [comment]
@3d-gussner The issue with Dutch and other languages is, we don't have any Dutch speaking person on board, so we will have a difficulty to keep the translations up to date.

**Comment by PavelSindler** [comment]
Hello, 
I' ve just repiled to you in your closed pull request: https://github.com/prusa3d/Prusa-Firmware/pull/39
German messages which were added by us are updated version of what you made for us in your closed pull request. I will check your new pull request and update german messages in next firmware version. Thank you very much.

**Comment by 3d-gussner** [comment]
Hi,
the worst is that the äöü is not working just looks bad on the LCD screen. I saw somewhere 'Italian/Spanish or Czech' using special characters but i think that these also do not working.
I closed it because some people complained and we worked on a new one. That is v0.9, which gets v1.0 as soon you add it.
We have to thank you adding the languages to make kids and other people easier to use the great printer.

**Comment by 3d-gussner** [comment]
@bubnikv I understand that you cannot speak every language in the world! Me and few people from the prusa3dhangout.slack.com group like to help with the translation to Dutch and German. Whatever you decide i will try to update the German and Dutch language_<xx>.h files as soon you update the repository. BTW: Thanks for answering.

**Comment by 3d-gussner** [comment]
@Foxandxss Hi, i run the language.pl and got lot off warnings because of the string length. You can check my fork where i also updated all other languages, so the perl script runs with MUCH less warnings. If you think that the translation isn't good, than do a pull request. They excepted my.

**Comment by Foxandxss** [comment]
My prusa will arrive in a few days. I will make some changes, try on the machine and make a PR.

**Comment by 3d-gussner** [comment]
@Foxandxss Hope you will enjoy it! I did 10+ fw uploads to see if the translation fit nicely on the screen, had some minor changes to do.

**Pull request merged**
