### PR TITLE
Fix MK3 compilation issue with Arduino 1.8.x

### PR DESCRIPTION
**Pull request by 3d-gussner**
see https://github.com/prusa3d/Prusa-Firmware/issues/614#issuecomment-385034066

### CODE REVIEW

**Comment by 3d-gussner** [comment]
Sorry missed that there is already a PR https://github.com/prusa3d/Prusa-Firmware/pull/620

**Comment by maximlevitsky** [comment]
Note that even with my fix, there are still issues with arduino 1.8.x. I noticed that menu has some strange update issue (some garbage is left on scrolling) and probably more. Currently use arduino 1.6.8

**Comment by ryall** [comment]
Also repaired the issue my side.

**Comment by mkbel** [comment]
Thank you for pointing to this hard to find error.

**Pull request merged**
