### PR TITLE
Added TMC2130 Support and Linear Advance from Marlin 1.1.1

### PR DESCRIPTION
**Pull request by madhunm**
Fixed more N00B errors when uploading changed files. Hence PR#92 was closed.

### CODE REVIEW

**Comment by GurliGebis** [comment]
Why port the TMC2130 driver when the RAMBo has A4982 stepper drivers? (Just curious)

**Comment by udvlp** [comment]
Can you separate the Linear Advance and TMC2130 Support in two different pull requests?

**Comment by GurliGebis** [comment]
I'll take a look at spliting the Linear Advance logic into a separate tree, rebased from 3.0.11 .
No promises if it will work, but I'll give it a try.

**Comment by fiveangle** [comment]
I think because the author's fork targets the mini-Rambo Einsy board (which would be an awesome upgrade for the Mk3)

https://github.com/ultimachine/Einsy-Rambo/tree/0.3a

**Comment by 3d-gussner** [comment]
I tried to split the LIN_ADVANCE and TMC2130 support.
- 1st issue: Arduino 1.6.8 has issues during compiling 'note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11' 
- So i tried to use Arduino 1.8.2
  - added 'https://raw.githubusercontent.com/ultimachine/ArduinoAddons/master/package_ultimachine_index.json' to preferences
  - download RAMBo in the boards manager and restart Arduino 1.8.2
- 2nd issue: Next warning during compiling was that 'stk500boot_v2_mega2560.hex' is missing
  - So i copied 'bootloaders' folder from Arduino 1.6.8 portable folder to Arduino 1.8.2 '%USERPROFILE%\AppData\Local\Arduino15\packages\rambo\hardware\avr\1.0.0' abd restarted Arduino 1.8.2
  - and i could compile the firmware with no warnings at all... Have to check later if it is working.

If you like check my Github
https://github.com/3d-gussner/Prusa-Firmware
https://github.com/3d-gussner/Prusa-Firmware/commit/9c201c4dd64026584628f7673f59d90a767d77b8


**BTW: My fork expects a Filament runout sensor being connected to P3 on the miniRAMbo, if that is not connected the printer will not print!!!**

**Comment by GurliGebis** [comment]
I have fixed the issues and rebased it on 3.0.11 over here: https://github.com/prusa3d/Prusa-Firmware/pull/99

**Comment by GurliGebis** [comment]
C++ 11 support works fine, you just have to make sure the platform.txt changes has been applied.

**Comment by 3d-gussner** [comment]
Thanks @GurliGebis ... have to check later the differences between your change and my.
Could you compile it with Arduino 1.6.8 ?
Did you tried it already on your printer? If so, how is it going?

**Comment by GurliGebis** [comment]
Yep, compiles fine with 1.6.8, that is what I used to test it on.
I haven't flashed it to my printer yet, since I want some more time on it with the stock settings (I only finished assembling it two days ago) :-)

@grooperdude , can you give it try with the changes from #99 on top of the 3.0.11 tree, and see if it works as expected for you? (Remember to copy the variant config to Configuration_prusa.config after applying the patch)

**Comment by GurliGebis** [comment]
@3d-gussner Here is what I did:

1: Follow the instructions here: https://github.com/prusa3d/Prusa-Firmware/issues/29#issuecomment-268985294 - just download the zip version and extract it somewhere - stop when you get to 3b.
2: Clone my git repo and checkout the LinearAdvance branch.
3: Continue from step 3b above, taking the files from my git repo.
4: Open the sketch, change to use the RAMBo board, and build it.

**Comment by madhunm** [comment]
Closing this PR until issues with Linear Advance are resolved.

Currently, enabling Linear Advance is causing the miniRambo to not boot.

**Pull request closed without merging**
