### PR TITLE
Fix shifted languages. Use \n and \x0a

### PR DESCRIPTION
**Pull request by leptun**
Cleaner PR with the changes in #2020 

@DRracer Changed in all languages

### CODE REVIEW

**Review by mkbel — APPROVED** [review]

**Comment by maximlevitsky** [comment]
I confirm that this fixed all the language issues that LCD update created, at least from my side.

**Comment by 3d-gussner** [comment]
I try to prepare a languages fix for 3.8.1-RC1 and it looks like that `lang-export.sh` has problems with messages contain `\n` instead of `\x0`
I found these two messages:
- `Crash detection can\x0abe turned on only in\x0aNormal mode` 
- `WARNING:\x0aCrash detection\x0adisabled in\x0aStealth mode`
When they have `\n` instead of `\x0a` and the `lang-export.sh`cannot find the correct file and lines.

The `Firmware.pot` and `Firmware_xx.po` files look like that:
```
# MSG_CRASH_DET_ONLY_IN_NORMAL c=20 r=4
#:
msgid "Crash detection can\nbe turned on only in\nNormal mode"
msgstr ""

```
instead of
```
# MSG_CRASH_DET_ONLY_IN_NORMAL c=20 r=4
#: ultralcd.cpp:4431
msgid "Crash detection can\x0abe turned on only in\x0aNormal mode"
msgstr ""
```

Also searching for `\n` in notepad++ or other editors is impossible as it is `LF`

**Comment by 3d-gussner** [comment]
@leptun Hi, did you get this comment above i wrote?

**Comment by leptun** [comment]
@3d-gussner the one about broken export script with \x0a and \n? I don’t know how to fix this script. @DRracer might do. As for searching in notepad++, use \\\x0a and \\\n in the search bar.

**Comment by 3d-gussner** [comment]
@leptun The notepad++ search issue was my bad as I have changed from (normal) to (extended)
- When I search in notepad++ (Normal) i can search for "\x0a and \n"
- When I search in notepad++ (Extended) I have to use "\\\x0a and \\\n"
sorry for that.


@DRracer 
The `lang-export.sh` script has still the bug that the last message isn't generated in `Firmware.pot` and `Firmware_xx.po` files, if it doesn't end with two `LF`. And now it also struggles also with `\n` to find the correct file and line.

As I was preparing the PR for missing translations https://github.com/prusa3d/Prusa-Firmware/issues/2254 I struggled again in the hole translation procedure:
- 1st the "bug" i commented here
- but also after using POEdit to make the translations and using `lang-import.sh` script the `/lang/lang_en_xx.txt` files are quite different to the new generated `/lang/po/new/lang_en_xx.txt` files
  - As non-translated messages in `/lang/lang_en_xx.txt` have `"\x00"` and the `/lang/po/new/lang_en_xx.txt`have `""`

Example
- `/lang/lang_en_de.txt`
```
#
"Crash detected. Resume print?"
"Crash erkannt. Druck fortfuehren?"

#
"Crash"
"\x00"

#MSG_CURRENT c=19 r=1
"Current"
"Aktuelles"

```
- vs. `/lang/po/new/lang_en_de.txt`

```
#
"Crash detected. Resume print?"
"Crash erkannt. Druck fortfuehren?"

#
"Crash"
""

#MSG_CURRENT c=19 r=1
"Current"
"Aktuelles"

```

What am I doing wrong?
How does Prusa translate the messages?
Can i use POEdit (free version available) or do I have to use PhraseApp (phraseapp.com) (starts from 140$/month)?
Or do I have to translate directly into the `lang_en_xx.txt` files?

**Pull request merged**
