### PR TITLE
🚧 Update .pot and .po files using new Python scripts

### PR DESCRIPTION
**Pull request by gudnimg**
PR is based on top of https://github.com/prusa3d/Prusa-Firmware/pull/3754

### CODE REVIEW

**Comment by 3d-gussner** [comment]
The `./update-pot.py` and `./update-po.py` scripts are working on Linux after changing the rights to be executed.
The `./update.pot.sh` doesn't work anymore on Linux with the changes made to `lang-extract.py` script.

On Windows 10 with Python3.9 and 
```
PS D:\Data\Prusa-Firmware\MK3> pip list 
Package    Version
---------- ---------
pathlib    1.0.1    
pip        22.3.1   
polib      1.1.1    
pyelftools 0.28     
regex      2022.7.25
setuptools 49.2.1
```
`.\update-po.py` works fine but `.\update-pot.py` or more `lang-extract.py` fails with this error:
```
PS D:\Data\Prusa-Firmware\MK3\lang> .\update-pot.py
Traceback (most recent call last):
  File "D:\Data\Prusa-Firmware\MK3\lang\lang-extract.py", line 330, in <module>
    exit(main())
  File "D:\Data\Prusa-Firmware\MK3\lang\lang-extract.py", line 278, in main
    if not Path(path).exists():
  File "C:\Program Files\Python39\lib\pathlib.py", line 1407, in exists
    self.stat()
  File "C:\Program Files\Python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '..\\..\\Firmware\\[a-zA-Z]*.[ch]*'
Command '['python', 'lang-extract.py', '--no-missing', '-s', '-o', './Firmware.pot', PureWindowsPath('../../Firmware/[a-zA-Z]*.[ch]*'), PureWindowsPath('../../Firmware/mmu2/[a-zA-Z]*.[ch]*')]' returned non-zero exit status 1.
```

- [ ] Change Linux rights to execute the new scripts
- [ ] Create a `requirements.txt` for python libs to be installed
- [ ] Update `lang/README.md`
- [ ] Remove the pot and po files commits.

**Comment by gudnimg** [comment]
I'm not able to reproduce this error, but I suspect the error is here: `'..\\..\\Firmware\\[a-zA-Z]*.[ch]*'` where `..\\..\\` should be `../../`

----

> PS D:\Data\Prusa-Firmware\MK3> pip list 
> Package    Version
> ---------- ---------
> pathlib    1.0.1    
> pip        22.3.1   
> polib      1.1.1    
> pyelftools 0.28     
> regex      2022.7.25
> setuptools 49.2.1

`pathlib` doesn't need to be installed via pip anymore, as the package is now part of Python (Python's standard library).

**Comment by gudnimg** [comment]
The Python scripts are added here https://github.com/prusa3d/Prusa-Firmware/pull/3754, this PR (3766) was just to demonstrate the output from the scripts.

**Comment by gudnimg** [comment]
Closing this PR in favor of https://github.com/prusa3d/Prusa-Firmware/pull/3754

**Pull request closed without merging**
